### ISSUE TITLE
Ability to tag photos

### ISSUE THREAD

**Issue by alexkutsan** [bpatrik/pigallery2#104]
It would be nice to have some kind of tags/albums not related to the directory structure, stored in db of pigallery.

**Comment by bpatrik** [comment]
Hi

this is related to these issues: #38 and  #45.

In short: There is no short/mid time plan to support tag modification on the UI. On the other hand I'm considering adding logical albums that would be basically a shortcut to search results.

**Comment by alexkutsan** [comment]
:+1:
