### ISSUE TITLE
First run as sudo

### ISSUE THREAD

**Issue by onlycparra** [bpatrik/pigallery2#115]
**Describe the bug**
I couldn't run the server once installed, the problem was that it uses the port 80, which is [only usable by root](https://unix.stackexchange.com/questions/10735/allowing-a-user-to-let-listen-to-a-port-below-1024). Therefore, I had to run it as sudo `sudo npm start`. Go to pigallery2 settings, toggle the "advanced" switch, change the port (to 8080, for example) and restart the server. Now it can run as normal user.

Maybe this detail can be mentioned in the instructions.

**Environment:**
 - HW: Raspberry Pi 3 B+
 - OS: clean installation of "Raspbian Buster with desktop", release 2019-09-26. Updated to the date of the post.

**Used app version:**
 - from release v1.70, following the installation instructions of the repository.

Thanks.

**Comment by bpatrik** [comment]
Thanks for the note, I'll add it to the Readme

**Comment by bpatrik** [comment]
I've updated the readme. Closing this.
Thanks for the report.
