### ISSUE TITLE
Unable to get docker container to start - error with mountpoint not found

### ISSUE THREAD

**Issue by nabeelmoeen** [bpatrik/pigallery2#116]
**Describe the bug**
Hi, I am trying to follow instructions at [II. Without docker-compose 
](https://github.com/bpatrik/pigallery2/blob/master/docker/README.md#ii-without-docker-compose)  to run docker image for pigallery2, but i get the below error when trying to run the container

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mountpoint for devices not found\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

I am using external mounted media (under /media/_mountpoint_ directory) as my /app/data/images volume. 

**Environment (please complete the following information):**
 - OS: Kubuntu 19.04
 - Docker: 19.03.3

**Used app version**:
- docker image: latest, and
- docker image  :v1.8.0

**Comment by bpatrik** [comment]
Hi,

I just tried this and works (raspbian , rpi3):
```bash
docker run -p 80:80 
-v ~/pigallery2/config:/app/data/config 
-v ./pigallery2/db:/app/data/db 
-v /mnt/hdd/images:/app/data/images 
-v /mnt/hdd/.tmp:/app/data/tmp bpatrik/pigallery2:latest
```

Are you sure, that you are mounting all 4 volumes?

**Comment by nabeelmoeen** [comment]
hi Patrik,

not sure, but it may have had to do with the name of the folder on my NAS. this morning when I rebooted my machine, the folder wouldn't appear under the mount point. i renamed it under Mac OS and now the docker container is working with the same command that failed yesterday.
