### ISSUE TITLE
Picture folder location

### ISSUE THREAD

**Issue by jerryhager** [bpatrik/pigallery2#119]
I use the docker versio of pigallery
I want to change the picture folder to a external location, to accomplish this i created a bind volume which directs to a external loaction as a path (/data/pictures).

In the container the path exists and i can get to it in the container console.

I can not edit the folder location in the UI, is keeps turning back to the default location. editiing in de config.json file does not do te trick either.

What am I doing wrong?

Jhod

**Comment by bpatrik** [comment]
Hi,

With docker tmp, images and these settings are fixed:
https://github.com/bpatrik/pigallery2/blob/b68d5d174d8f485e766865892816710a4794b836/docker/debian-stretch/Dockerfile.build#L21-L24
They should not be changed within the container, rather you should point your volumes to the right folder on your host.

Edit docker-compose.yml here (change `./pigallery2/images` to your images folder):
https://github.com/bpatrik/pigallery2/blob/b68d5d174d8f485e766865892816710a4794b836/docker/docker-compose/default/docker-compose.yml#L22-L25

Or set up the path correctly if you are running directly:
```bash
  -v <path to your config file folder>/config.json:/app/data/config/config.json \
   -v <path to your db file folder>:/app/data/db \
   -v <path to your images folder>:/app/data/images \
   -v <path to your temp folder>:/app/data/tmp \
```

If you really want to override these settings within docker, you can try setting them as [environmental variables ](https://docs.docker.com/compose/environment-variables/):
```yml
 environment:
 - Server-Media-folder=<your path>
```

**Comment by jerryhager** [comment]
thanks for the quick reply, I tried the ENV variant but in capitals ;-(
Using them in normal letters did the trick!

Now experimenting with Pigallery, so far is looks very nice en exactly what I searched for!
Jhod

**Comment by bpatrik** [comment]
I'm happy to hear!
