### ISSUE TITLE
Video playback fails without transcoding on v1.8.0

### ISSUE THREAD

**Issue by krupaldesai** [bpatrik/pigallery2#120]
First of all, thanks a lot @bpatrik for the awesome gallery software. Hats off to you for your enormous contribution.

**Background**
I just updated my old pigallery2 running on locally built docker (I built back in July from master branch) on rpi 3b+ to the latest nightly-alpine. I noticed the new feature for video transcoding. Great job @bpatrik ! Also, thanks for publishing armv7 docker images :).

However I'm not using video transcoding option as I am already pre-processing video to lowest quality as per my needs before putting it to gallery folder.

**Describe the bug**
When I navigate to the video file, it fails playback with the error:
```
1/7/2020, 9:36:32 AM[WARN] Handled error:
ErrorDTO {
  code: 10,
  message: 'Unknown server side error',
  details: [Error: ENOENT: no such file or directory, stat '/app/data/tmp/tc/porch_door_cam/2020-01-07/vid_08/2020-01-07_08-20-00_loop.mp4_2560klibx264480.mp4'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/app/data/tmp/tc/porch_door_cam/2020-01-07/vid_08/2020-01-07_08-20-00_loop.mp4_2560klibx264480.mp4',
    expose: false,
    statusCode: 404,
    status: 404
  },
  detailsStr: "Error: ENOENT: no such file or directory, stat '/app/data/tmp/tc/porch_door_cam/2020-01-07/vid_08/2020-01-07_08-20-00_loop.mp4_2560klibx264480.mp4'"
}
1/7/2020, 9:36:32 AM[ERROR] Unexpected error:
[Error: ENOENT: no such file or directory, stat '/app/data/tmp/tc/porch_door_cam/2020-01-07/vid_08/2020-01-07_08-20-00_loop.mp4_2560klibx264480.mp4'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/app/data/tmp/tc/porch_door_cam/2020-01-07/vid_08/2020-01-07_08-20-00_loop.mp4_2560klibx264480.mp4',
  expose: false,
  statusCode: 404,
  status: 404
}
```

**Screenshots**
UI shows error:
![pigallery2_video_playback](https://user-images.githubusercontent.com/6030965/71886232-da2a1080-3161-11ea-99e0-b489709a6409.png)

**Environment:**
 - OS: Raspbian Buster Lite on raspberry pi 3b+
 - Browser: Chrome

**Used app version**:
- official docker image bpatrik/pigallery2:nightly-alpine
- docker-ce 18.09.7
- release v1.8.0

Is using video transcoding mandatory? If so, is there any way I can turn off the use of transcoding? Thanks!

**Comment by bpatrik** [comment]
Hi,
I'm happy that you like it. 
Thanks for the report. This should work actually. The latest commit should fix it.

Patrik

**Comment by krupaldesai** [comment]
Thanks @bpatrik it is indeed fixed on the latest docker image. Videos play fine. Thanks a lot for your awesome support!

Best regards,
Krupal

**Comment by bpatrik** [comment]
perfect. I'm closing this.
