### ISSUE TITLE
Unstable container

### ISSUE THREAD

**Issue by exetico** [bpatrik/pigallery2#122]
I've used Pi Gallery 2 for a week or to, but my Docker-host crashed two times, and become unavailable. CPU load was stuck at 100%, and i couldn't get in contact with the machine by SSH.

I rebooted it, and everything was good.

After two days, the same thing happened again. 

This was my docker-compose file:
```
pigallery2:
  image: bpatrik/pigallery2:nightly-stretch
  container_name: pigallery2
  environment:
    - NODE_ENV=production
  volumes:
    - ./pigallery2/config:/app/data/config
    - /home/USERNAME/pigallery2/db:/app/data/db
    - /media/pictures:/app/data/images
    - ./pigallery2/tmp:/app/data/tmp
  ports:
    - "CUSTOMPORT:80"
  restart: unless-stopped
```

After that, i removed the container - and everything has been stable hereafter.

Am I the only one, with that issue?

I would like to dump more details and so, however, with all the crashed, i can't get it back up, before i have a few days here within my Home-network, cause everything becomes unavailable, at the time, of the CPU is going to 100%.

I did setup some logging for the docker containers too, but at the time of the Pi Gallery 2 is starting to cook my CPU, the logging is stuck - and no useful information is logged.

My docker software is not the newest (`Docker version 18.03.0-ce, build 0520e24`), but EVERYTHING ELSE works just fine, with no issues, what so ever :-)

**Comment by bpatrik** [comment]
Hi, 

Thanks for the report.
Can you confirm that you were not accidentally running any build in background job? (Like clicking on the transcode videos, create thumbnails, etc.. button)
You can also try going to advanced settings mode and check if there anything running at the `jobs` panel. (technically it is possible that you don't have a job like `indexing` listed at the panel, but it is still running in the background, but only you set it up)

If everything it alright than it should use too much resources. I'll try to keep an eye on my instance. 

In the meantime, you can try running it with:
```yml
command:
 --Server-Log-level=6
```
This will enable more detailed logging.

**Comment by exetico** [comment]
Hi bpatrik.

First, i'm sorry for the late reply!

It's actually a good question - cause i did start the transcode of every video-file. However, it happend two times, as mentioned - and the 2nd time, i had disabled the "video"-feature.

But one thing; Kindly note that i'm unable to access everything on the VM, where the docker-container is hosted, so i can't log in, and check for jobs and so, "while" it's toasting my server :-D 

I could enable the logs, and test it once more, but, do you think, it will give us the proper amount of details?

(_And oh, btw, my server has been rock stable again, after i stopped the container with PiGallery2, to it must be a problem with that_)

**Comment by bpatrik** [comment]
Hi,

I'm running the app (with nightly-alpine image) on my raspberry pi 3 B for days by now and I do not see any odd behavior.

I suspect that there might be running some job in the background.
To make sure noghting runs, empty the jobs in the `config.json`: 
```json
....
    Jobs: {
      maxSavedProgress: 10,
      scheduled: []
   }
...
```

And restart the app. (And do not click after that on any green running button (like: 'convert video' 'index db now', etc..) :) )

Note: If you started the video converting. Disabling the video support, wont stop the video converting, just hide it from the  UI (I might fix it once). Plus if you canceled video converting, It wont stop until that current video in progress is converted. (So canceling means, no further video conversion, but not immediate stopping)

Also how high is the traffic on the app? I'm mostly using it with 1-2 parallel users.
Thumbnail and photo (down scale for faster laod) generation happens on the fly. If your users are different folders, that was not opened before, that adds also extra load.
A way to avoid that to index the whole folder and generate all thumbnail, photo at once with the jobs. 
This is my pipeline: 
![Jegyzet 2020-01-11 153151](https://user-images.githubusercontent.com/7512182/72205813-84b67200-3487-11ea-972b-b89fecba280f.jpg)
Once the indexing is done, it also creates all thumbnail, photo etc.
You can also schedule it to run every night at 2am or so.

**Comment by Suika** [comment]
Limiting runtime resources is also an option https://docs.docker.com/config/containers/resource_constraints/

**Comment by exetico** [comment]
Yes. But it's just a ugly hack - but maybe it's usefull to find out what's
going on within the container, at the time, there the issue is present :-)

I'll start my container again today, and see hos it goes.

søn. 12. jan. 2020 22.41 skrev Suika <notifications@github.com>:

**Comment by exetico** [comment]
And, the whole VM was unavailable again, not more than 24 hours after i enabled the PiGallery2-container again.

So, now i've defined a resourcelimit, and i'll check how that goes:
```
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
```
And oh, btw - there's MANY scheduled things in my config-file:
```
"scheduled": [
                {
                    "name": "Indexing",
                    "jobName": "Indexing",
                    "config": {},
                    "trigger": {
                        "type": 1
                    }
                },
                {
                    "name": "Thumbnail Generation",
                    "jobName": "Thumbnail Generation",
                    "config": {
                        "sizes": [
                            160
                        ]
                    },
                    "trigger": {
                        "type": 4,
                        "afterScheduleName": "Indexing"
                    }
                },
                {
                    "name": "Photo Converting",
                    "jobName": "Photo Converting",
                    "config": {},
                    "trigger": {
                        "type": 4,
                        "afterScheduleName": "Thumbnail Generation"
                    }
                },
                { 
                    "name": "Video Converting",
                    "jobName": "Video Converting",
                    "config": {},
                    "trigger": {
                        "type": 4,
                        "afterScheduleName": "Photo Converting"
                    }
                },
                { 
                    "name": "Temp Folder Cleaning",
                    "jobName": "Temp Folder Cleaning",
                    "config": {},
                    "trigger": {
                        "type": 4,
                        "afterScheduleName": "Video Converting"
                    }
                }
            ]
```

**Comment by bpatrik** [comment]
That config file is normal (those are the default settings. Those settings do not start any job/task, just set up a pipline that is easy to configure. And also you can delete them by settings the `scheduled` property to an empty array `[]`)

Setting a resource limit does not solve the issue, but maybe you will have access to your server at least. Seeing some `docker logs` would be nice. 

Btw can you access it through the web when it is running at 100% CPU?

There are actually 3 differences between your docker-compose and my one:
1) I'm using the alpine build (should not matter)
2) I `restart: always` (docker might restart the instance if it is not responding)
3) for the db, I'm using named volumes instead of a mounted filesystem path (should not matter)

I changed the restart procedure to `restart: unless-stopped` to see if that matters.

btw I was using the app on RPi2, now on RPI3 since 2016 (without docker) and I never had this 100% CPU issue.  So it is very interesting in your case :)

**Comment by exetico** [comment]
It just happend again - and the VM sadly become unavailable.

It's so wierd..

![image](https://user-images.githubusercontent.com/3549445/72364671-314a5b00-36f7-11ea-8fae-57037cb38280.png)
I don't really have the time to debug, it i need to try everything to get it working. I started using PiGallery2, case i really like it simple - and it's using the file-path, and not requesting me to import anything. (Our pictures is sorted in folders)

Also, i would not like to just go with `restart:always`, cause `restart: unless-stopped` should be good enough :-) 

I've removed it again. The same VM are hosting Home Assistant, and my girlfriend shouldn't even control our lights this morning :-) 

My Docker-instance is not that new anymore (18.03), but it's not a problem for other containers, so i don't really know what to do. 

But's it's clear that something within that container, are getting the host to just to almost 100% - and hereafter, become unavailable.

Damn :D

**Comment by bpatrik** [comment]
I'm sorry to hear that. :/

I'll let you know if I came across this issue and find a solution to it. 

You can look around at these places for an alternative:
https://github.com/awesome-selfhosted/awesome-selfhosted
https://www.reddit.com/r/selfhosted/search/?q=photo&restrict_sr=1
I see Piwigo, Lychee the most on these forums.

**Comment by bpatrik** [comment]
Also is you image only about the pigallery2 container?
Because the CPU load should be ~0% if you using (=browsing) the app.

**Comment by exetico** [comment]
I'll just follow up.

I've no problem, since i removed PiGallery2. Not a single crash of my VM, or anything, like that. The load is normal, and so.

So something must be wrong. But i can't say if it's related to how my images was accessed, or so. My images is located on another instance, and data was mounted by NFS, which i'm also using for other files, with much more regular (and power demanded) load. 

Overall i'm still not sure about what's triggering this, but i can't have yet anther day, where the VM arn't working :-)

**Comment by bpatrik** [comment]
Hi, 

thanks for following up. Unfortunately I could not reproduce this and no one else reported anything like this, so I do not really have a clue about this issue.
