### ISSUE TITLE
Too much thumbnails in thumbnail directory

### ISSUE THREAD

**Issue by ifsnop** [bpatrik/pigallery2#123]
**Is your feature request related to a problem? Please describe.**
When gallery is big, the amount of thumbnails created in the thumbnails folder is also really big.

**Describe the solution you'd like**
Other software (github, squid proxy) distribute all the files generated in subdirectories, using the first characters of the filename as subdirectories. Usually two subdirectories are enough to keep the number of files per directory small enough. As you are creating the filename with a md5 hash (PhotoProcessing.ts), it is only a minor change in your code.

If filename is: ffe4829552985261b99b12bdd8ba87d5_200.jpg, it can be stored like:

/tmp/thumbnails/f/f/ffe4829552985261b99b12bdd8ba87d5_200.jpg

https://stackoverflow.com/questions/12157836/how-to-spread-hash-multiple-files-on-disk-without-storing-more-than-1000-per-dir

**Describe alternatives you've considered** (optional)
Really none :) Thanks for this great  code!

**Comment by bpatrik** [comment]
Hi,

After v1.8 this is actually solved. The app follows the directory structure of your images folder now.
And md5 hash is also dropped. Now I'm using the orignal filenames with some prefix.
(Reason for that so now the app has a 'TempDirCleanUp' feature. It can delete all invalid thumbnails, converted photos, transcoded videos in the temp folder. Can be activated in advanced settings mode, under the `jobs` tab)

Patrik

**Comment by ifsnop** [comment]
I have installed from master and didn't see this behaviour, maybe this is
planned but not yet done? I will have to dig deeper :D

However, one of the best things of pigallery2 is that it doesn't need to
modify the original image directories/files (I mount them read-only in my
pigallery2 container).

Please, if possible keep thumbs in a separated tree structure.

Regards

> After v1.8 this is actually solved. The app follows the directory
> structure of your images folder now.
> And md5 hash is also dropped. Now I'm using the orignal filenames with
> some prefix.
> (Reason for that so now the app has a 'TempDirCleanUp' feature. It can
> delete all invalid thumbnails, converted photos, transcoded videos in the
> temp folder. Can be activated in advanced settings mode, under the jobs
> tab)
>

**Comment by bpatrik** [comment]
Hi,

The app won't clean the thumbnail folder automatically as it is a resource consuming process.
You can just manually empty (`rm -r`) your temp folder.
Or manually run the temp folder cleaning job at the [advanced admin](https://pigallery2.herokuapp.com/admin) view (the jobs feature in the app like crontab jobs, but by default they are switched off):
![Jegyzet 2020-01-08 142847](https://user-images.githubusercontent.com/7512182/71981768-55073000-3223-11ea-989b-147c45a5f7b2.jpg)

The new thumbnails should be created under `<temp path>/tc` folder.

Best,
Patrik

**Comment by ifsnop** [comment]
Thanks!
