### ISSUE TITLE
Use alternate config.json file

### ISSUE THREAD

**Issue by ifsnop** [bpatrik/pigallery2#124]
**Is your feature request related to a problem? Please describe.**
If using different config.json files, you could configure several/different galleries easily.

**Describe the solution you'd like**
npm start -- -conf alternate.conf

**Describe alternatives you've considered** (optional)
Couldn't find anything related in the documentation, maybe it has already been implemented.

Thxs!

**Comment by bpatrik** [comment]
Hi,

There is something like this (although not 'officially' supported, but works) .
In the docker I'm using this:
https://github.com/bpatrik/pigallery2/blob/293c37c643e573e0019945b6b9251e90738aa2b2/docker/debian-stretch/Dockerfile.build#L21

Best,
Patrik
