### ISSUE TITLE
Tag search fails with multiple tags

### ISSUE THREAD

**Issue by stavoltafunzia** [bpatrik/pigallery2#128]
Searching by tag doesn't show all results when searching for multiple tags. 

I have a photo with tags (IPTC Keywords) A, B, C, D, E, and I want to search for photos containing tags B, C, and D. If in the search bar I type B, C, D then the photo shows up, but if I change the order, let say C, D, B then the photo is not included in the search results.

I'm using the latest docker container on Debain Buster x64. Tried to search with Firefox and Chrome.

PS: thanks for this great gallery!

**Comment by bpatrik** [comment]
Hi,

This is not supported right now. 
#58 will add this feature to the app.

Patrik

**Comment by bpatrik** [comment]
This should be working now in the nightly build.
