### ISSUE TITLE
Show the number of photo in each page

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#13]
Hi,

I don't know where to put some improvement ideas I had for this so I'm opening them as issues. If you think they might not be the best ideas or the path you want for PiGallery, just ignore and close them ;)

It would be nice to have at the top, next to the map widget, a way to know how many photos there are in the folder.

Regards,
Marco Angélico

**Comment by bpatrik** [comment]
Hi Marco,

thanks for the note.
I'll consider putting a photo counter to the app. (Might be a different place so, depending how it blends in the current design)

Patrik

**Comment by bpatrik** [comment]
Hi,

I've added a photo counter to the navigation bar with the latest commit: [fd74f76](https://github.com/bpatrik/pigallery2/commit/fd74f761dcdbde44a2e4d4b08b421e6b21f63b7a)
It will be part of the next commit
