### ISSUE TITLE
ffmpeg preset and crf as an dropdown in settings

### ISSUE THREAD

**Issue by Suika** [bpatrik/pigallery2#131]
**Describe the solution you'd like**
Add a preset and crf dropdown to the video transcoding setting.

I'm not talking about the `node-fluent-ffmpeg` presets, but ffmpeg's presets https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapresetandtune

Since I didn't see an option for that in `node-fluent-ffmpeg`, a `.addOption(['-crf 20', '--preset ultrafast']);` should do.

This should help speed up some transcodes at the cost of quality if the user so desires and transcoded quality can be more or less be decided by them.

**Comment by bpatrik** [comment]
Okay. I can add this. 

Patrik

**Comment by bpatrik** [comment]
should be added in the latest commit

**Comment by Suika** [comment]
Thx
