### ISSUE TITLE
Feature: cache next and previous images

### ISSUE THREAD

**Issue by stavoltafunzia** [bpatrik/pigallery2#134]
When browsing the photos in full screen mode, both using auto-play or manually clicking 'next', I find it a bit inconvenient that first the thumbnail is shown and right after it's refreshed with the high-resolution image. Even if it may take a small fraction of second to switch from thumbnail to image, the blink when refreshing is noticeable, even in direct Wi-Fi connection to the server.  

I think this could be avoided if, when an image is visualized, the next and previous N images would be pre-loaded and cached locally.

PS: not related to this, but I think if you add a "donate" link you may get some extra!

**Comment by bpatrik** [comment]
Hi,

Thanks for the suggestion. That part of the app is relatively complex, but I might add this at some point. Not sure when yet. 

Patrik
P.s.: I was considering, but I don't expect much money and I wanted to avoid to deal with the taxes :)

**Comment by bpatrik** [comment]
Added a feature to preload next photo. 

I don't think I will implement caching the previous one, si I will just close this bug for now.
