### ISSUE TITLE
Incorrect exif information displayed

### ISSUE THREAD

**Issue by tsmig** [bpatrik/pigallery2#136]
Some photos have incorrect "Date taken" information displayed:  
December 8, 2002
Sunday, 13:00:00 

Attached correct and incorrect  sample photo.
![IMG_20150604_114718](https://user-images.githubusercontent.com/24794933/73793827-6eaa8180-47a7-11ea-993e-fe0f4ca6b1ec.jpg)
![IMG_20160416_170747](https://user-images.githubusercontent.com/24794933/73793828-6f431800-47a7-11ea-8dd0-a4c25a4df95b.jpg)

Pigallery2, Version: v1.8.0. Running in Docker on Debian.

**Comment by bpatrik** [comment]
Hi,

thank you!

I'll look into it.

Patrik

**Comment by bpatrik** [comment]
The latest commit should solve this

**Comment by tsmig** [comment]
Thanks, waiting for docker build then. Please use this picture for test cases.

**Comment by bpatrik** [comment]
The nightly build should already contain this

**Comment by tsmig** [comment]
In nightly-stretch I have:
Error: ENOENT: no such file or directory, mkdir '/app/demo/tmp'
    at Object.mkdirSync (fs.js:823:3)
    at ProjectPathClass.reset (/app/src/backend/ProjectPath.js:28:16)
    at new ProjectPathClass (/app/src/backend/ProjectPath.js:8:14)
    at Object.<anonymous> (/app/src/backend/ProjectPath.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/app/demo/tmp'
}

**Comment by bpatrik** [comment]
Hi,

Can you check the following:
 1. can you delete `config.json` outside the container? (most likely you have some legacy settings at your temp and images folder)
 2.can you make sure you dont give any env variable or cli switch to docker like this: `Server-Media-tempFolder=/app/demo/tmp`
 3. can you make sure that you mounted the correct volume?

**Comment by tsmig** [comment]
The "docker-compose.yml" file is exactly the same as for stable build, except "nightly-stretch" is chosen as image.
1. config.json deleted
2. ran with `docker-compose up -d `
3. mounted the same volume as with stable version.

In fact for test i removed whole "pigallery2" before running test build folder and new one was created by docker

**Comment by bpatrik** [comment]
Hi,

I tried to look into it, but could not find the issue.
It seems that something is overriding your settings somehow. 
A workaround to this would be explicitly setting it through ENV variables in your docer-compose file.
like:
```
 environment:
     - Server-Database-dbFolder=/app/data/db
     - Server-Media-folder=/app/data/images
     - Server-Media-tempFolder=/app/data/tmp 
```

I hope it helps.

**Comment by tsmig** [comment]
Thanks, I'll take a look at this.

**Comment by bpatrik** [comment]
I can confirm that this is indeed an issue. I spent a reasonable time on it, but still could not find  a solution.
This issue is related to #130. 
The problem is with the shell entrypoint: https://github.com/bpatrik/pigallery2/blob/da83d63fa4dd10435417cd4304edcc0ca0cf8c6e/docker/debian-stretch/Dockerfile.build#L40
For some reason, running the container does not parse ENV variables.
With exec type entrypoint it does work: https://github.com/bpatrik/pigallery2/blob/35435af7c067f03b08bf1b7f5832f9d0355a66cc/docker/debian-stretch/Dockerfile.build#L36 but that does not support using ENV variables in the command (like setting the config file path)

I guess I will just revert that and disable setting the config path from env variables
