### ISSUE TITLE
ExcludeDir only works when setting both Exclude Folder List and Exclude File List

### ISSUE THREAD

**Issue by barry-luijten** [bpatrik/pigallery2#137]
**Describe the bug**
When only one of the options is set, ExcludeDir always returns false:

Code snippet from **src/backend/model/threading/DiskMangerWorker.ts:**

```
public static async excludeDir(name: string, relativeDirectoryName: string, absoluteDirectoryName: string) {
    if (Config.Server.Indexing.excludeFolderList.length === 0 **||**
      Config.Server.Indexing.excludeFileList.length === 0) {
      return false;
    }
```
**Quick solution:** change "||" to "&&"
**Workaround:**  Set both options.

**Environment (please complete the following information):**
**Used app version**:
- compiled from source (master branch)

**Comment by bpatrik** [comment]
Hi ,
thanks!
That's a bug indeed. Would you like to make PR so that you show up at the contributors or should I just fix it?

**Comment by barry-luijten** [comment]
I haven't forked the project yet, so you go ahead and fix it ;)
I will definitely create a fork later, since I really like this project and would like to contribute (I have some ideas already)  :)
Thanks!

**Comment by bpatrik** [comment]
okay. I fixed it then :) thanks for the report.
