### ISSUE TITLE
Auto-start pigallery2 on raspberrypi start-up

### ISSUE THREAD

**Issue by xhabih** [bpatrik/pigallery2#142]
This is not a feature request, is a instalation help request, sorry about that but I can't find support anywhere. I'm linux newbye, I instaled pigallery2 on my pi with the "Getting Started" guide, I can start it manually but I'm unable to make it auto-start when I reboot my pi, a guide to auto-start pigallery2 on raspberrypi start-up would be nice for newbyes.

**Comment by xhabih** [comment]
I found the solution myself creating a service as described here: https://github.com/bpatrik/pigallery2/issues/42

**Comment by bpatrik** [comment]
Hi,

I recommend using docker. It is easier to run with that. But yes #42 is a good approach for this.

Patrik

**Comment by xhabih** [comment]
I suggest to add it to the getting started guide.

Thank for your work.

**Comment by bpatrik** [comment]
I'm closing this as the supported / recommended usage is with docker.
