### ISSUE TITLE
Cannot save advanced indexing options

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bpatrik/pigallery2#143]
**Describe the bug**

1. Open settings as an admin
2. Toggle to advanced
3. Go to the indexing options and change a setting. Example in picture is `Folder reindexing sensitivity`
4. Try to save and cannot.

The save button is still grayed out, and unable to be pressed. 
Other settings work and are saveable. 

**Screenshots**

![image](https://user-images.githubusercontent.com/38865330/77565036-a376b300-6e91-11ea-8a3a-d10670817f1c.png)

**Environment (please complete the following information):**
 - OS: Server: Debian 10, Client: Win 10
 - Browser: Both Chrome 80 and Firefox 74

**Used app version**:
Docker latest (1.8)

**Comment by bpatrik** [comment]
Hi, thanks for the report. 
I started at a new  company that has strong restriction on hobby projects. It will take some time until I sort it out, so I cannot give you a date when it will be ready. Until then you can manually change the config file.

Patrik

**Comment by bpatrik** [comment]
This issue is related to #161. See more explanation there.
TL;RD: New version should solve it.

**Comment by TheCakeIsNaOH** [comment]
Thanks, I updated to nightly and I am having no more issues.
