### ISSUE TITLE
Zoom in issue in Safari (desktop and mobile)

### ISSUE THREAD

**Issue by ghost** [bpatrik/pigallery2#144]
**Describe the bug**
Steps to reproduce:
1. Open Pigallery2 in safari
2. Click on picture to zoom in
3. See the issue

**Screenshots**
https://www.youtube.com/watch?v=y5782hvQWbc&feature=share

**Environment (please complete the following information):**
 - OS: MacOS Mojave, iOS
 - Browser: Safari

**Used app version**:
- docker latest

**Comment by bpatrik** [comment]
Hi, thanks for the report.
I started at a new company that has strong restriction on hobby projects. It will take some time until I sort it out, so I cannot give you a date when it will be ready. Until then you can manually change the config file.

Patrik

**Comment by dealancer** [comment]
@bpatrik no worries, I am just reporting things I am finding. Great work btw, I am very happy with Pigallery2 running on my RPI. Hopefully I can invest some time to learn Angular and fix some of the issues.

**Comment by bpatrik** [comment]
I made some updates to the code, that potentially also improves this.

I tested it on a iPad. It does not produce the issues that you have in the video, but zoom still not work.

**Comment by bpatrik** [comment]
It turns out since angular 9, hammerjs does not work by default. Fixed that.
