### ISSUE TITLE
Weird sharing behavior 

### ISSUE THREAD

**Issue by ghost** [bpatrik/pigallery2#145]
**Describe the bug**
There are multiple issues related to the sharing functionality. All of them related to sharing links with no password. I have set global setting enabled for password protection. Not sure if this setting should enforce password protection or not (and it does not).

Issue 1. There is no way to cancel sharing. When I click share button, the sharing link is generated and can be used instantly. It would be nice to have a switch/button to enable or disable sharing.
Issue 2. There is no way to cancel or track previous shares. This is more of a feature request, but is very important cause it is related to privacy.
Issue 3. After guest visited a shared link in Safari, log out button does not work.
Issue 4. Links without a password still asks for a password. Empty password does not work. However if I reload a page I can view the page. Not sure what expected functionality is.

**Environment (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Sfari and Chrome

**Used app version**:
- docker latest

**Comment by bpatrik** [comment]
Hi, thanks for the report.
Some of the is realted to #55. I'll try to fix it at some point. 

----------
I started at a new company that has strong restriction on hobby projects. It will take some time until I sort it out, so I cannot give you a date when it will be ready. 

Patrik

**Comment by bpatrik** [comment]
Hi,

I've added sharing listing and deleting functionality with the last commit.
