### ISSUE TITLE
Any ideas on how to change admin password?

### ISSUE THREAD

**Issue by dealancer** [bpatrik/pigallery2#146]
Since there is an issue with #64, it would be nice to know at least an option on how to change a default password for admin. Any ideas?

**Comment by dealancer** [comment]
Ok, I removed the admin user manually by installing sqlite3 in the container directly and running queries manually.

**Comment by bpatrik** [comment]
For those who find this issue later:
You cannot. There is currently no way to change password of a user. 
You need to delete that user and recreate.
In case of the default admin user you should:
1. create a new user with admin rights
2. login with that user
3. delete the default admin

**Comment by dealancer** [comment]
@bpatrik I guess that didn't work for me, e.g. I was not able to remove admin user. It simply didn't work even if I was logged in as another admin user.
