### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ghost** [bpatrik/pigallery2#148]
**Describe the bug**
I am getting this error message when using safari from time to time, this prevents app from working correctly:

```
Blocked https://example.com/runtime-es2015.50fs915b135b0e6c7b2a.js from asking for credentials because it is a cross-origin request.
```

I didn't see such behavior in Chrome. Is this caused because CORS support is not enabled? I am using nginx as a proxy.

**Environment (please complete the following information):**
 - OS: RPI, MacOS
 - Browser: Safari

**Used app version**:
- docker latest

**Comment by dealancer** [comment]
I guess it has something to do with BasicAuth. Issue happens when I enable BasicAuth only. This may be a solution https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials.

@bpatrik  any ideas?

**Comment by dealancer** [comment]
I guess I found a similar issue: https://stackoverflow.com/questions/56557082/safari-blocked-https-from-asking-for-credentials-because-it-is-a-cross-o

**Comment by dealancer** [comment]
@bpatrik Please review my PR, hopefully it should fix an issue.

**Comment by bpatrik** [comment]
Hi,

This cross origin issue sounds weird as the server of the backend and fronted are the same. There shouldn't be any cross original calls. (I'm not using the usual, separate backend and frontend running with `ng serve`) Also I'm not using Bacis Auth, but cookies and some csrf token.

Can you maybe provide some more info about it?

Like the domain of the url in the browser is the same with the domain that browser is calling?
Also does your PR solve this issue? If yes I don't mind adding it at the end.

sorry for the late reply, I started at a new company with strict restrictions on hobby projects. It took a while until it got sorted, but seems to be okay now.

**Comment by dealancer** [comment]
@bpatrik I guess it has something to do with Safari issue and Basic Auth. Looks like angular has a solution to that. 

I am using nginx +https + basic auth before the pigallery2. Everything works right in Chrome and Firefox, but not Safari. See the issue I have mentioned earlier. I am not sure why it happens though, but it looks like other Angular users have such issues too.

**Comment by bpatrik** [comment]
alright. I'm fine with. The PR does not really break anything

**Comment by dealancer** [comment]
@bpatrik that fixed an issue in the nightly release. Thanks!
