### ISSUE TITLE
Clicking on faces link logs out guest, who is viewing shared link

### ISSUE THREAD

**Issue by ghost** [bpatrik/pigallery2#149]
**Describe the bug**
Clicking on faces link logs out guest, who is viewing shared link.

Also for some reason face recognition is not working for me, I am not seeing a single face. Is this functionality complete?

**Environment (please complete the following information):**
 - OS: RPI, MacOS
 - Browser: Chrone

**Used app version**:
- docker-latest

**Comment by bpatrik** [comment]
Hi,

Thanks for the report. I'll look into it.

Unfortunately there is no face recognition support implemented yet. Its a future plan tho, see #57 
The app can use the XMP Face region metadata:
```
Faces (persons) support
   - reads Adobe's XMP Face region metadata. (It is defined by the Metadata Working Group (MWG).)
   - shows face bounding box over images
```

**Comment by bpatrik** [comment]
The last commit should solve this.
