### ISSUE TITLE
Feature: Add custom links to the navigation bar

### ISSUE THREAD

**Issue by darthdubu** [bpatrik/pigallery2#150]
It would be really sweet to be able to add our own links to the navigation bar, Like if you have a discord or a blog to be able to put it there. I feel like this may already be easily possible but as a non-programmer I'm not sure. I use the docker version of Pigallery2 if anyone is familiar with a way to do this I'd love to know.

**Comment by bpatrik** [comment]
Hi,

Currently I don't really see if there is an easy straightforward way of doing so.
The only way of doing so is to fork the project and add the link at the source. Here:
https://github.com/bpatrik/pigallery2/blob/b6f93ac5c4e2f9939ba2745f65f21da0dd3bfcc4/src/frontend/app/ui/frame/frame.component.html#L18

Then compile and run the project from [source](https://github.com/bpatrik/pigallery2#121-b-install-from-source).

If once I add plugin/add on option to the app, this should be easier.

**Comment by ducky710** [comment]
Aw that's unfortunate, but thanks for at least giving me that option. I think this would definitely be a well appreciated addition when you have time! I love what you've accomplished with the project thus far. Cheers!

**Comment by bpatrik** [comment]
This is now possible as experimental feature. See: [150](https://github.com/bpatrik/pigallery2/issues/174#issuecomment-1345406902)
