### ISSUE TITLE
Recursive random photo is not recursive

### ISSUE THREAD

**Issue by BbillyBob** [bpatrik/pigallery2#154]
**Describe the bug**
Files tree in the PiGallery (with /app/data/images/ as root index folder) :
/app/data/images/galleries/
/app/data/images/galleries/0.jpg
/app/data/images/galleries/dir1/
/app/data/images/galleries/dir1/1.jpg
/app/data/images/galleries/dir2/
/app/data/images/galleries/dir2/2.jpg

_Expected_
1. With http://mygallery.local/api/gallery/random/ : get alternatively 0.jpg, 1.jpg or 2.jpg when refreshed
2. With http://mygallery.local/api/gallery/random/?directory=galleries : get 0.jpg even when refreshed 10 times
3. With http://mygallery.local/api/gallery/random/?directory=galleries&recursive=true : get alternatively 0.jpg, 1.jpg or 2.jpg when refreshed

_Reality_
1. OK
2. OK
3. Got only 0.jpg
3.bis If I delete 0.jpg, I get the following error :
{"error":{"code":12,"message":"No photo found","detailsStr":""},"result":null}
I get the same error with 2. after 0.jpg deletion (but it is expected in this case).
So it seems the recursive parameter does not work or I missed something.

Additionally (you may want me to create another bug issue for this), the "&recursive=true" in the URL field is not updated when I switch "recursive" to on/off in the Random Link menu in the GUI. It is updated when I change another field (Date or Resolution) though.

**Environment**
 - Latest docker version without nginx proxy
 - Browser Firefox and Chrome

**Comment by bpatrik** [comment]
Thanks for the report. I'll look into it.

**Comment by bpatrik** [comment]
The last commit should solve this.
