### ISSUE TITLE
Sorting should also be applied to folders

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#16]
Hi,

When I change the sorting method on the top right corner of the page (below the "logout" button) I was expecting for the entire page (folders and photos) to get the sorting method I select (ascending or descending name or ascending or descending date).
However, it is only being applied to the photos.

If you need any more information or some printscreens, just let me know.

Regards,
Marco Angélico

**Comment by bpatrik** [comment]
Hi,

Thank you for the report. 
Unfortunately I don't have date information for the folders, but i will fix it to be sorted accordingly based on its name.
(Although it might take a while I'm relatively busy lately and its only a hobby project)

Patrik

**Comment by bpatrik** [comment]
Hi,

I've applied the sorting for the folders too with the commit [9f5e612](https://github.com/bpatrik/pigallery2/commit/a9f5e612e2d3e31473bfd8a19b979e98ca06ecbc).
Unfortunately it only works for names, not the dates. 
This feature will be part of the next release.
