### ISSUE TITLE
Thumbnails creation in batch

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#17]
Hi,

Is there anyway to put PIGallery2 to create the thumbnails in batch during low PI use hours?
Something like scheduling the thumbnails creations so that it won't flood the memory/swap/CPU usage when we access a folder with too many photos for the first time?

Cheers,
Marco Angélico

**Comment by bpatrik** [comment]
Hi,

Which Pi and thumbnail generation library are you using?
I have pi 3 with `sharp` and I don't have any issues, it works relatively fast. 
If there is an issue with the ram, you might try starting the node process with the `--expose-gc` switch, then the server will try to clean up after itself (after the thumbnail generation is ready).

Unfortunately there isn't any batch method currently for thumbnail creation.

Patrik

**Comment by bpatrik** [comment]
I think this issue is related to #14.
I've added the option to limit the number of threads for generating the thumbnails. 
Let me know if that is not enough to solve the problem.
