### ISSUE TITLE
Failed to execute 'setItem' on 'Storage': Setting the value of 'content:.' exceeded the quota.

### ISSUE THREAD

**Issue by Getterac7** [bpatrik/pigallery2#170]
**Describe the bug**
The gallery is failing to load and I'm seeing these errors in the browser console:

```
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'content:.' exceeded the quota.

DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'content:2015-06-27 Rock and Roll Hall of Fame and Museum' exceeded the quota.
```

This might just be that I have too many photos for pigallery2. 487 folders, 15537 photos, and 164 videos.

**Environment:**
 - OS: Server runs alpine-3.11-default_20200425_amd64
 - Browser: (everything I tested) Chrome v84.0.4147.105 in Windows and Linux, Firefox v79.0 in Windows

**Used app version**:
Release 1.8.0

**Comment by bpatrik** [comment]
That does not look good. 

This should be fixed. Until then (as a mitigation), you can [manually delete the local storage](https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/) in your chrome browser. It is only used for caching, so it wont cause any issue. (A page reload is recommended afterwards)
You can also disable caching (Settings (enable advanced mode) -> Other -> Cache) so this issue wont come up again

**Comment by bpatrik** [comment]
The latest commit should fix this.
