### ISSUE TITLE
Display metadata tags on Info sidebar

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#171]
It would be helpful to list metadata tags in the Info sidebar on the fullscreen viewer.

The metadata tags currently display when hovering over items in the thumbnail view, but when in the single item view mode there is no where to see the tags. The Info sidebar would be a good place to list them - and they could be hyperlinked to the tag searches.

This is especially useful for the mobile viewer where there is no 'hover' for touchscreens and thumbnail sized tags display are often too small to see all the tags.

**Comment by Forza-tng** [comment]
This would be very helpful indeed.

**Comment by bpatrik** [comment]
Hi, I've implemented this. It should be included in the next release.
