### ISSUE TITLE
Rotated images go back to non-rotated when zooming

### ISSUE THREAD

**Issue by Forza-tng** [bpatrik/pigallery2#172]
Hi, I noticed that for pictures that have rotation tag, thumbnails and previews are rendered correct, but when zooming in on the picture it loads the original file and that is shown without rotation.

**Comment by Forza-tng** [comment]
![Screenshot_20200731-173335_Opera](https://user-images.githubusercontent.com/68693597/89051125-10281f80-d354-11ea-9faa-0ce41ae76e3f.jpg)
![Screenshot_20200731-173335_Opera](https://user-images.githubusercontent.com/68693597/89051136-14543d00-d354-11ea-9dc1-7cf6882080ad.jpg)

This happens on the phone and on the desktop.

**Comment by bpatrik** [comment]
It seems that browsers finally fixed image rotation: https://caniuse.com/#feat=css-image-orientation 
I was manually fixed in #11 
That is a good news as it will speed up the application.
Unfortunately fixing this breaks the "duck image" in #19 and I could not find a solution for that.

**Comment by bpatrik** [comment]
Note: you might need to empty your tmp folder so the app regenerate the thumbnails. (otherwise all your photos will look rotated)
