### ISSUE TITLE
Pictures displayed as colored vertical lines

### ISSUE THREAD

**Issue by kianby** [bpatrik/pigallery2#185]
**Describe the bug**
Some pictures are displayed as colored vertical lines. Same for thumbnail and picture.  They come from same device, are big pictures (3000x4000 px). Some are displayed correctly and others not. 

**Screenshots**

![Screenshot_2020-09-26 PiGallery 2(1)](https://user-images.githubusercontent.com/1949284/94338949-d6873400-ffe5-11ea-98a8-f6ed0e622d8d.png)

**Environment (please complete the following information):**
 - OS: Linux 
 - Browser : Firefox 

**Used app version**:
Docker image :bpatrik/pigallery2:latest | 530.3 MB | 2019-12-30 20:54:11
-Docker 18.09.1

**Comment by bpatrik** [comment]
Hi,
Thanks for the report can you maybe send me a sample photo?

**Comment by kianby** [comment]
hum... sorry but it seems linked  to my browser not pigallery2. I realized display is fine on another Firefox vesion. I rebooted my PC and it's correct on Firefox too. Maybe that's an issue with Firefox 80.0.1 rendering and problem will happen again. Or system update was not applied completely. Anyways that's not an application issue. Thanks for your support. I enjoy using PyGallery2!
