### ISSUE TITLE
npm start: Cannot find module

### ISSUE THREAD

**Issue by lbischof** [bpatrik/pigallery2#197]
**Describe the bug**
I am trying to start Pigallery2 locally, so I can contribute. 

After running `npm install` I get an error:
```
$ npm start

> pigallery2@1.8.2 start /home/user/git/pigallery2
> node ./src/backend/index

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/user/git/pigallery2/src/backend/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pigallery2@1.8.2 start: `node ./src/backend/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pigallery2@1.8.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-10-26T19_04_31_185Z-debug.log
```

How can I start the gallery locally?

**Environment (please complete the following information):**
 - OS: Linux

**Used app version**:
- master

**Comment by bpatrik** [comment]
Hi,

It looks to me that you are trying to run the app from source and you did
not build it before? (ie. ./src/backend/index.js is missing)

lbischof <notifications@github.com> ezt írta (időpont: 2020. okt. 26., H,
20:09):

**Comment by lbischof** [comment]
Ah yes, I missed that line.

**Comment by lbischof** [comment]
`npm start` doesn't seem to reload files. `npm run build` takes a long time. Is there any way to "watch" the files and auto reload when something changes?

**Comment by bpatrik** [comment]
Hi,

If you want to develop the project:
1) I recommend using a IDE that auto compiles  the .ts files (like
Webstorm) or use `tsc -w` (you need typescript installed globally for
this). This would rebuild the backend on change
2) run `npm run run-dev` (
https://github.com/bpatrik/pigallery2/blob/ee1ce3402480514f2f6e4c4eee16fb99d92f721f/package.json#L18)
to rebuild the frontend with watch.

Hope this helps.

Patrik

lbischof <notifications@github.com> ezt írta (időpont: 2020. okt. 27., K,
18:59):

**Comment by lbischof** [comment]
Thanks, that is exactly what I needed.
