### ISSUE TITLE
'npm run build' fails

### ISSUE THREAD

**Issue by rafaelkarrer** [bpatrik/pigallery2#2]
Hi, cool project!

I am trying to install PiGallery2 on my raspberry pi 3 with Raspbian 8 (jessie). Following your install guide gives me the following error after running 'npm run build':

`backend/middlewares/thumbnail/THRenderers.ts(1,39): error TS6137: Cannot import type declaration files. Consider importing 'sharp' instead of '@types/sharp'.
backend/model/memory/UserManager.ts(10,14): error TS2420: Class 'UserManager' incorrectly implements interface 'IUserManager'.
  Types of property 'deleteUser' are incompatible.
    Type '(id: number, cb: (error: any) => void) => void' is not assignable to type '(id: number, cb: (error: any, result: string) => void) => void'.
      Types of parameters 'cb' and 'cb' are incompatible.
backend/model/mysql/UserManager.ts(6,14): error TS2420: Class 'UserManager' incorrectly implements interface 'IUserManager'.
  Types of property 'deleteUser' are incompatible.
    Type '(id: number, cb: (error: any) => void) => void' is not assignable to type '(id: number, cb: (error: any, result: string) => void) => void'.
      Types of parameters 'cb' and 'cb' are incompatible.
test/backend/unit/middlewares/uesr/AuthenticationMWs.ts(173,66): error TS2345: Argument of type 'UserManager' is not assignable to parameter of type 'IUserManager'.
  Types of property 'deleteUser' are incompatible.
    Type '(id: number, cb: (error: any) => void) => void' is not assignable to type '(id: number, cb: (error: any, result: string) => void) => void'.
      Types of parameters 'cb' and 'cb' are incompatible.
test/backend/unit/middlewares/uesr/AuthenticationMWs.ts(198,66): error TS2345: Argument of type 'UserManager' is not assignable to parameter of type 'IUserManager'.
`
Do you have any idea what I could be doing wrong?

Here is the npm log:
[2017-07-11T12_34_55_364Z-debug.txt](https://github.com/bpatrik/pigallery2/files/1138934/2017-07-11T12_34_55_364Z-debug.txt)

Many thanks,
Rafael

p.s.:
Before that step, I had to install the 'unofficial' phantomjs package for rpi from this location:
https://github.com/fg2it/phantomjs-on-raspberry

**Comment by bpatrik** [comment]
Hi Rafael,

I'm happy to hear that interested in the project!

The project is currently under heavy development. 
This error is already fixed with the latest commits, but not part of any 'release' yet.
I'll set up a proper publishing tool chain soon for the project and with those releases, users won't have to install all dev dependencies (like phantomjs), just the minimal required libraries.

I'm also planning to have the first release candidate in the next few weeks.

In the mean time, if you would like to try the PiGallery2, just download the source from the repo, then
`npm install`
`npm run build`

btw.: You got this error because, you try to compile the project with the latest typescript. Using typescript@2.3.4 can also solve this problem.

Best,
Patrik

**Comment by rafaelkarrer** [comment]
Hi Patrik, thanks for the quick reply.
I have downloaded the updated version. `npm run build --verbose` now shows this error:

`npm info it worked if it ends with ok`
`npm verb cli [ '/usr/local/bin/node',`
`npm verb cli   '/usr/local/bin/npm',`
`npm verb cli   'run',`
`npm verb cli   'build',`
`npm verb cli   '--verbose' ]`
`npm info using npm@5.0.3`
`npm info using node@v8.1.3`
`npm verb config Skipping project config: /root/.npmrc. (matches userconfig)`
`npm verb stack Error: missing script: build`
`npm verb stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)`
`npm verb stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5`
`npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5`
`npm verb stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:329:20)`
`npm verb stack     at FSReqWrap.cb [as oncomplete] (fs.js:311:19)`
`npm verb cwd /root`
`npm verb Linux 4.9.28-v7+`
`npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--verbose"`
`npm verb node v8.1.3`
`npm verb npm  v5.0.3`
`npm ERR! missing script: build`
`npm verb exit [ 1, true ]`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2017-07-12T09_53_55_271Z-debug.log`

Sorry for the trouble ;)

Cheers,
Rafael

**Comment by bpatrik** [comment]
Hi Rafael,

Sorry for the misleading setup instructions. 
The latest beta (https://github.com/bpatrik/pigallery2/releases/tag/1.0.0-beta.3)
Doesn't need any more `build` (its prebuilt), just:
`npm install`
`npm run`

please keep in mind, that running the application as a daemon/service is not solved yet. 
You can try something like this:
https://stackoverflow.com/questions/4681067/how-do-i-run-a-node-js-application-as-its-own-process/28542093#28542093

**Comment by rafaelkarrer** [comment]
Thanks, actually it was `npm start` for me.
Watching out for updates :)
Cheers
