### ISSUE TITLE
can't connect : error 404

### ISSUE THREAD

**Issue by augras** [bpatrik/pigallery2#203]
Hi,
I made my install from release : ok.
When i made npm start, i first got the error
Error: ENOENT: no such file or directory '/home/user/public_html/domain/pigallery2/demo/tmp'
In fact the demo directory and tmp directory were lake and i create them by hand.
After a new npm start i got
[server] 0.0.0.0:80 requires elevated privileges
and i use
npm start -- --Server-port=8080
to get
[server] Listening on port 8080
So, i thought it was ok, but when i try to connect to https://domain/pigallery2:8080 or https://domain/pigallery2
i got error 404
Where i have made a mistake ?
Thanks for your answer,
Philippe

**Comment by bpatrik** [comment]
Hi

Try http://
There is no ssl set up you haven't set up any do https:// won't work



-- Sorry for being brief, sent from my phone.

**Comment by augras** [comment]
Thank you for your very speed answer.
I can't use http : everything is redirected on https.
Maybe i can set https in config.json ? I take a look in config.json but haven't seen something about https.
It's not an emergency and we are on sunday...

**Comment by bpatrik** [comment]
You can set https but not with the app. You would need a reverse proxy for
that like nginx.

-- Sorry for being brief, sent from my phone.

**Comment by augras** [comment]
I'm with apache and i try a lot of things but i didn't won !

**Comment by bpatrik** [comment]
Sorry I'm not familiar with apache.
You can check if you can access the app directly (before the appache). That should work on http://. (Given that your server lets that port out).
In general if the app starts up without an error then it could bind to the port, so there is a high chance the issue is not with the app.

**Comment by augras** [comment]
Hi,
what do you mean by "you can check if you can access the app directly" ?

**Comment by bpatrik** [comment]
I assume you have:
`Apache listening on <yourdomain>:portA` that deals with https and forward the request to the `pigallery listening on <youdomian>:portB`.
You can try <youdomian>:portB.
You can netstat https://www.tecmint.com/20-netstat-commands-for-linux-network-management/ to list what serveries are running on what port.

**Comment by augras** [comment]
You are right : there was a port problem.
I's ok now with it... but a new problem, i get now : 
`at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/augras/public_html/augras.xyz/appPigallery2/src/backend/model/threading/ThreadPool.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)`

**Comment by bpatrik** [comment]
Sorry, I cannot really make any sense of the error message. I assume the beginning of it is missing.
