### ISSUE TITLE
Feature request: Admin view of existing shares

### ISSUE THREAD

**Issue by jorgytim** [bpatrik/pigallery2#204]
Please consider adding the ability for a person with the admin role assigned to be able to see all "shares" created by users.
In addition if an admin could also delete or modify shares found, that would be helpful.

**Comment by bpatrik** [comment]
Hi,

This should be already done see #145.
I was just lazy to create a release from the nightly build, but the nightly be should safe to use currently.

**Comment by jorgytim** [comment]
Excellent, thank you for getting back to me!
-Tim
