### ISSUE TITLE
Full screen mode, first load stuck at 20th photo.

### ISSUE THREAD

**Issue by adamcodemaker** [bpatrik/pigallery2#207]
**Describe the bug**
1. create folder with a lot of photos (more than 20).
2. open folder in pigallery2
3. click on first photo to see full screen
4. press right arrow on keyboard to see next photo
5. stuck at 20th photo

To see more you have to quit full screen and load the rest of photos by scrolling.

**Environment (please complete the following information):**
 - server runs on docker 19.03.13 on obuntu 20.04
 - Chrome 87.0.4280.88 on windows 10

**Used app version**:
- docker-1.8.0

**Comment by gioagu** [comment]
I confirm this, also on version 1.8.2 compiled on Raspian GNU/Linux 10 (buster) on a Raspberry Pi 4.

**Comment by bpatrik** [comment]
Thanks. I'll look into it.

**Comment by bpatrik** [comment]
This is an annoying bug. Really hard to reproduce.

If you see this again, can you let me know:

1. What browser are you using (this is a UI issue, backend does not matter)
2. What is the url? 
  * pigallery follows the status with the url `?p=` tag, like: https://pigallery2.herokuapp.com/gallery/?p=IMG_1401.jpg
  * Let me know if that url gets updated the correct way or not.
3. When you exit from the preview mode, what is the status of the scrollbar? 
  * `pigallery` loads new photos if the scrollbar is too low down (i.e.: it loads photos as you scroll).
  * While watching photos in the preview mode, the gallery in the background should scroll to the watched photo (so when you exit, it can do the shrinking photo animation)

**Comment by bpatrik** [comment]
In the meantime, I also randomly run into this and added a fix to it.
