### ISSUE TITLE
H.265 support

### ISSUE THREAD

**Issue by sakhnik** [bpatrik/pigallery2#211]
**Is your feature request related to a problem? Please describe.**
The videos encoded with H.265 play black, despite the thumbnails are generated correctly.

**Describe the solution you'd like**
HEVC videos should be played as well.

**Describe alternatives you've considered** (optional)

My new camera apparently encodes videos using H.265. So older videos play well in pigallery2, but the newer ones show just the black screen. While the audio plays fine. I tried using different browsers, mobile vs desktop to no avail. So it's likely to be the backend deficiency. Is it a known limitation? Or is there anything that could be done?

**Comment by bpatrik** [comment]
Hi 
the issue is with the browsers, they do not support it: https://caniuse.com/hevc

The app can convert the videos back to h264. You can find that in the settings, advanced mode and under `video` or `jobs`
You can manually start the process or periodically run it.

**Comment by sakhnik** [comment]
Oh, right. Perhaps, I should just avoid using HEVC at all! Thanks!

**Comment by tuxthepenguin84** [comment]
Chrome now supports h.265. I've tried playing a h.265 encoded video in PiGallery2 version 1.9.3 but get an "Error during loading of the video". Without using the transcoding option is there another way to get h.265 encoded videos to playback?

**Comment by bleomycin** [comment]
+1 curious about this with native support being available in chrome now?
