### ISSUE TITLE
Question: How is file deletion handelled?

### ISSUE THREAD

**Issue by cbhushan** [bpatrik/pigallery2#213]
Quick question: I have noticed that when a file/folder is deleted. It does disappear in the interface, which is nice. I was wondering if corresponding entries in database is also removed or not? My use case: I was thinking to add my phone camera folder to pigallery2. But I generally end up deleting a lot of photos/video at a later point to remove unwanted/very similar photos. And I was wondering if such thing would have adverse effect on the database performance. 

Thanks for pigallery2. It seems to be right fit for my needs.

**Comment by bpatrik** [comment]
Hi,

It should delete from the DB too. 
The app caches on the client side in session/local storage: https://developers.google.com/web/tools/chrome-devtools/storage/sessionstorage
If you delete that, it will re-fetch from the server side DB.

But it will NOT delete the corresponding thumbnails. For that you can run the `Temp folder cleaning` in the settings under the `jobs` panel in advanced mode. You can run it manually or set up periodic run.

**Comment by cbhushan** [comment]
That's great info. You can consider adding it to FAQ or something similar.
