### ISSUE TITLE
PiGallery Logo

### ISSUE THREAD

**Issue by nishantbb** [bpatrik/pigallery2#218]
As part of my homepage, I whipped up a more descriptive logo for my PiGallery page, as I don't want to get it confused with PiHole and other Pi related imagery. I believe I used a freely available camera icon. I can whip up something for you (following the existing black/white theme?) if you'd like to change the logo at some point. Thank you for PiGallery 2!

![pigal](https://user-images.githubusercontent.com/8856557/103696954-0e423800-4f54-11eb-8a25-42100fe8a703.png)

**Comment by bpatrik** [comment]
Hi 
Thanks you for the offer. 
I would not mind replacing the logo to something better, but I would prefer a simple and clean design. Most likely I would keep a black and white logo in the app, maybe a colorful during load time.

**Comment by bpatrik** [comment]
I'm closing this in favor of the new logo and way that anyone can set any svg icon now.
