### ISSUE TITLE
Support IPTC 120 - Caption / Abstract

### ISSUE THREAD

**Issue by natrius** [bpatrik/pigallery2#22]
Search for that tag and if its present show it a nice way or show it via key or button. That way i could add information about a picture there and its present, no matter on which device. 
That way there is also no need for a database-field or something like that.

**Comment by natrius** [comment]
Sorry, i forgot to add the links (even if you have already implemented it) http://phpgraphy.sourceforge.net/manual/latest/apas04.html and https://sno.phy.queensu.ca/~phil/exiftool/TagNames/IPTC.html 

Is there one picture in the demo where i can see that implementation?

**Comment by bpatrik** [comment]
No problem, I knew this IPTC tag.
Here is an example: https://pigallery2.herokuapp.com/gallery/?p=IMG_5910.jpg
The caption is visible at the top left corner.

I'm not sure about this version yet. I don't want to pollute the design with additional text and I find the file names more useful on the image tiles, so I only put it to the preview window.

**Comment by natrius** [comment]
I like it that way actually. One thought, some keystrokes are recognized right now (ie. right-arrow, left-arrow), maybe add one "i" for "Information" and "c" for "Caption". 
I tend to use date-time.jpg for my images and seldom change the filename itself. But i might consider it. The nice thing about caption is, it could be a longer description actually. Thats why it is nice sometimes. 

And, make it as an opt-in via settings? That would be another idea. So its default clean and if someone would like to see the captions, its possible. 

Thanks for your work! :)

**Comment by bpatrik** [comment]
I've added the shortcut key for `f` fullscreen , `i` info panel, `c` show controls (caption is part of the control panel)
There is now also a config called (Client->)Other->CaptionFirstNaming (default false). If you change it to true, the captions will be shown in the grid view instead of the filename. 

your welcome :)

**Comment by FoxxMD** [comment]
This is awesome thank you <3
