### ISSUE TITLE
How to change admin password?

### ISSUE THREAD

**Issue by thve25** [bpatrik/pigallery2#220]
First of all, I'm really happy with this project, its great!

Only one issue, I see no way to change the default admin password. 
I use docker-compose.

Any suggestions?

Thanks,
Thomas

**Comment by bpatrik** [comment]
Hi,

You need to log in with the original `admin` user . Create a new user with Admin rights. Login with that user and delete the original `admin` user.

Patrik

**Comment by thve25** [comment]
Thanks, that makes sense. Sorry for the stupid question

**Comment by bpatrik** [comment]
Created a Config setting where everyone can list the user that they want to enforce in the app. (You also set it through env variables) It should be secure as if you set the password in the config.json, the app will write back the salted, encrypted version and delete the clear text.

**Comment by bpatrik** [comment]
Updated the MANPAGE.md in 58e1857 that shows the usage of the config.

**Comment by yllekz** [comment]
Could you feasibly update the instructions to state that a new user needs to be created + the old "admin" user must be deleted? I also got super confused by this, initially just looking for a "change password" prompt.

**Comment by stenrock** [comment]
I created a new user with Admin rights and delete the Admin user but still get the warning "(1) Using default admin user!
"You are using the default admin/admin user/password, please change or remove it."

I am puzzled.

**Comment by san-jupitero** [comment]
> I created a new user with Admin rights and delete the Admin user but still get the warning "(1) Using default admin user! "You are using the default admin/admin user/password, please change or remove it."
> 
> I am puzzled.

same issue, have no clue how it can be fixed

**Comment by Gooygeek** [comment]
I was having the same issue. Created a new user with admin rights, deleted the old admin user, still kept getting the warning popup.

The solution was a tale as old as computing... Turn it off and on again.

Restarting the container solved the issue.
