### ISSUE TITLE
Sort by file size 

### ISSUE THREAD

**Issue by oohnana** [bpatrik/pigallery2#222]
Hello! My feature request is simple (but out of the realm of my coding ability). I'd like the ability to sort by "file size". File size does incredibly well when grouping like images together. Thanks!

**Comment by oohnana** [comment]
Found a temporary fix to feed my need for sort. Not perfect but helps.
 exiftool -ext 'png' '-filename<${FileSize#}_%f_.${FileType}' .

**Comment by bpatrik** [comment]
Hi,
yes, indeed its a simple change. I'll add it later once I'm done with the advanced search #58.
Unless someone feels to up to the task and implements it before me :)

**Comment by drwb** [comment]
Did this ever get implemented? @oohnana how would your temp fix work?

**Comment by bpatrik** [comment]
Here you are: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/70493b29-59f9-404b-88fe-d40e79eac35f)
