### ISSUE TITLE
Numeric String Sort

### ISSUE THREAD

**Issue by erri120** [bpatrik/pigallery2#223]
Unsure if this should be a Feature request or Bug report:

Sorting is currently done by comparing strings using `string.toLowerCase()`:

```typescript
      case SortingMethods.ascName:
      case SortingMethods.ascDate:
        this.directories.sort((a: DirectoryDTO, b: DirectoryDTO) => {
          if (a.name.toLowerCase() < b.name.toLowerCase()) {
            return -1;
          }
          if (a.name.toLowerCase() > b.name.toLowerCase()) {
            return 1;
          }
          return 0;
        });
        break;
```
(from https://github.com/bpatrik/pigallery2/blob/master/src/frontend/app/ui/gallery/gallery.component.ts#L175).

The problem is when numbers are involved:

```txt
Screenshot 1.jpeg
Screenshot 2.jpeg
Screenshot 3.jpeg
...
Screenshot 10.jpeg
```

would be sorted to
```txt
Screenshot 1.jpeg
Screenshot 10.jpeg
Screenshot 2.jpeg
Screenshot 3.jpeg
...
```

This is obiously not desired and the standard libs don't offer much help in this regard. There are multiple packages and solutions out there so it's not hard to fix but requires some discussion about what solution to use (if any at all).

**Comment by bpatrik** [comment]
Hi,

Probably proper numerical ordering would be better. 
I just did a quick check on win and windows explorer does the same. 

Would be be interested solving this with a PR?

**Comment by erri120** [comment]
I can take a look
