### ISSUE TITLE
OpenStreetMap instead of Google Maps

### ISSUE THREAD

**Issue by natrius** [bpatrik/pigallery2#23]
Change completely or just make it optional. For selfhosting the usage of OSM should be preferred in my opinion :)

**Comment by bpatrik** [comment]
Do you have any lib suggestion? I don't have experience with OSM. 
I was checking leaflet, that has angular integration too: https://github.com/Asymmetrik/ngx-leaflet
and mapbox: https://github.com/Wykks/ngx-mapbox-gl

**Comment by natrius** [comment]
I'm sorry, no clue about that. Implementing a map itself would be really easy (sry for german site) https://blog.tappenbeck.net/2014/01/25/openstreetmap-in-meine-webseite-einbinden/ - maybe there is more information https://wiki.openstreetmap.org/wiki/DE:Karte_in_Webseite_einbinden 

After further research i found this list 
https://wiki.openstreetmap.org/wiki/Deploying_your_own_Slippy_Map 
but i don't know what popular or easy to use. You could ask in the OSM-Forum (or mailinglist), usally they know a lot and are happy to help

**Comment by bpatrik** [comment]
don't worry, I'll figure it out.

**Comment by bpatrik** [comment]
I've changed the maps. Now it supports by default OpenStreetMaps and Mapbox, but you can add any map provider that has map tile url.

**Comment by natrius** [comment]
Awesome, its beutiful :)
