### ISSUE TITLE
Question: Possible to update docker:lastet?

### ISSUE THREAD

**Issue by Synt3x** [bpatrik/pigallery2#233]
Hello @bpatrik,

I notice that the "latest" build on docker hub is 2 month old, is it possible for you to update it or do you want to finish something before updating it? (Should I start using the nightly build instead?)

Thanks in advance!

Best regards,
Synt3x

**Comment by bpatrik** [comment]
Hi,
There was not many significant update after the last release. I like to keep the latest there for a while without any change so people has time to report bugs before I promote it to a release.

The next release will be 1.9 that will include advanced search #58

**Comment by Synt3x** [comment]
Ni worries! Thanks for info! 😃
