### ISSUE TITLE
Autocompletion while typing in searchbar seems to be broken

### ISSUE THREAD

**Issue by tibrisch** [bpatrik/pigallery2#237]
Suggestions/autocompletion while typing in search bar does not work even if it is enabled in settings.

Running docker image bpatrik/pigallery2:nightly-alpine
Digest:sha256:24c6864f03ddc72d930c5b61174d443cfa897dbf28cefbf3af27751185f8f5fd

**Comment by bpatrik** [comment]
Hi,

I know about the issue. Its beacause of #58, please use v1.8.2 while it gets fixed.

**Comment by bpatrik** [comment]
With the latest commits, it should work.

**Comment by tibrisch** [comment]
Yes, works very well now. Well done!

I am not sure if I should raise a bug concerning a difference in behavior now.
If i click with mouse, or hit enter on keyboard on one of the autocomplete suggestion - I would prefer that the search is done directly, instead i have to click on the search icon or hit enter again. Is this expected behavior?

Also, another issue, if i start typing something and then press backspace and remove - there is some corrupted texts that is printed on same. 
![image](https://user-images.githubusercontent.com/592510/112976499-3b6a4500-9155-11eb-99ee-cb19bbaf9446.png)

**Comment by bpatrik** [comment]
i checked search bars from major companies and indeed hitting enter or selecting auto complete item, runs the search.  So updated the behavior. Also fixed the placeholder overlap issue.

**Comment by tibrisch** [comment]
Thank you for the changes! I added a pull request https://github.com/bpatrik/pigallery2/pull/248 for search on click. I hope you are ok with it.
