### ISSUE TITLE
User access management

### ISSUE THREAD

**Issue by bandita00** [bpatrik/pigallery2#24]
Hi!

Do you plan to implement some access management functionality for the shared folders? For example guest user is only allowed to see one folder, but not another, which is only viewable for admin?
Besides this, this is a really great software, runs fast even on a raspberry pi, which makes it a perfect choice for sharing family photos. So a big thumbs up for you!  :smiley:

**Comment by bpatrik** [comment]
Hi!
Thank you very much! The whole idea was to make it run on devices, like a raspberry. :)

Originally I was planning to make thinks like that (I mean user / folder level access control) the api has the place for it, but currently I'm not planning to do it. May some point at the future. 

With the sharing function you can create link for a specific folder (optionally to its subfolder) and you can give those link to your friends.

**Comment by bandita00** [comment]
This is a good workaround, my intention was to serve separate folders to the users with only one instance of the website running.

**Comment by bpatrik** [comment]
Yeah its made for this use. The only think that users with 'sharing link' are `limited Guests` users. They can not use the searching or the sharing function of the site.
