### ISSUE TITLE
Keep face labels and areas when zooming

### ISSUE THREAD

**Issue by tibrisch** [bpatrik/pigallery2#240]
I have some photos with lots of people. Its impossible to figure out who is who without zooming. How complicated would it be to implement so that labels and face areas scale and move in proportion to zoom and pan?

Thanks for a great project!

**Comment by bpatrik** [comment]
Hi,

The `ligthbox` (photo viewer) is implemented here: https://github.com/bpatrik/pigallery2/tree/master/src/frontend/app/ui/gallery/lightbox

It should not be too hard to implement.

Faces are created here. Their position and size should be trasnformed based on the `zoom` and `drag` value:https://github.com/bpatrik/pigallery2/blob/24942b2ee1a2de01048c1aa053d7b68a28b73d37/src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.html#L53-L70

For the photo I'm calculating the transformation here: https://github.com/bpatrik/pigallery2/blob/24942b2ee1a2de01048c1aa053d7b68a28b73d37/src/frontend/app/ui/gallery/lightbox/media/media.lightbox.gallery.component.ts#L41-L45

This logic should be migrated to the faces.

**Comment by tibrisch** [comment]
I will start to look at the code and try to learn/understand how to do this. It will take me a year or so, but I think it will be a nice enhancement. Thank you for the information on where to start looking.

**Comment by tibrisch** [comment]
I have something that works. https://github.com/bpatrik/pigallery2/pull/249
But I don't think you will be happy when you see it.
