### ISSUE TITLE
Gesture support for zoom

### ISSUE THREAD

**Issue by FoxxMD** [bpatrik/pigallery2#25]
On mobile it would be fantastic if there was gesture support to double tap to zoom. Or pinch to zoom.

**Comment by bpatrik** [comment]
thanks for the tip. I'll look into it at some point. It might take a while, since there is no simple way to do this.

**Comment by larspontoppidan** [comment]
A shortcut to this would be to allow "View Image" from the context menu (long press picture on mobile). On my Android pinch zoom works after choosing "View Image". Also, on desktop "View image" allows easy zoom to 100%

**Comment by bpatrik** [comment]
Hi

I've implemented a 'zoom'-ing feature. Should work both on desktop an mobile.
On desktop you can zoom with mouse wheel or `-` and `+` keys.
On mobile with two finger pinch.

Best,
Patrik

**Comment by FoxxMD** [comment]
Fantastic!! Thank you! ❤️
