### ISSUE TITLE
Improve face text visibility

### ISSUE THREAD

**Issue by tibrisch** [bpatrik/pigallery2#250]
The visibility of the face text could be improved. I suggest replacing the black text-shadow whith a black background to the text and remove the black text-shadow previously added. Also make the text font bold.
Are you OK if i submit a PR for review with my suggestion?
![bild](https://user-images.githubusercontent.com/592510/113616179-11cd8400-9655-11eb-9b5c-f275d013c304.png)

**Comment by bpatrik** [comment]
Hi,

Yes I was thinking about doing it, see: https://github.com/bpatrik/pigallery2/pull/232#issuecomment-792237911

The dark background for the white text should be also added to the caption and the arrows. Not sure yet if they should be rounded or rectangle. The app design follows this non-rounded rectangle design but I think that would look odd in the photo preview.

**Comment by tibrisch** [comment]
Ah, yes I saw your comment. Here is a suggestion I mentioned https://github.com/bpatrik/pigallery2/pull/251
Maybe it's too simple? But I find it easier to read.

**Comment by tibrisch** [comment]
I have added background to caption and navigation arrow. Perhaps this solution is too simple?  https://github.com/bpatrik/pigallery2/pull/251

**Comment by bpatrik** [comment]
It looks good to me, I can merge it.
Thank you for the contribution!

**Comment by tibrisch** [comment]
Thanks!

**Comment by tibrisch** [comment]
Thanks!
