### ISSUE TITLE
Feature suggestion: Persistent sort order on folders

### ISSUE THREAD

**Issue by larspontoppidan** [bpatrik/pigallery2#26]
It would be great if the chosen sort order was remembered for folders. Newly opened folders should start with the default sort order and if changed it should be remembered for that folder.

This would improve my use case as I'd like index folders to show the newest gallery on top, while gallery folders show the oldest picture on top so they can be viewed chronologically. As it is now, I have to change sort order all the time.

Really great photo hosting tool!!

**Comment by bpatrik** [comment]
Hi,

I can implement something like that, but it will only save to sorting locally to the given browser. 
Would that help?

Patrik

**Comment by larspontoppidan** [comment]
Keeping the setting locally in the browser is totally fine. Thanks for doing this!

**Comment by bpatrik** [comment]
I've added persistent sorting. It stores the data in local storage, so only works with the given browser.

**Comment by larspontoppidan** [comment]
Yep, it works. I just tested with bpatrik/pigallery2:nightly-stretch docker, thanks!
