### ISSUE TITLE
Non-expiring shared links

### ISSUE THREAD

**Issue by Wdavery** [bpatrik/pigallery2#260]
As a simple alternative to having a permission based user system (like #188, which would be great) could we implement non-expiring shared links? Currently the share doesn't get created if you set a 0 in the `Valid:` selection.

This would enable some password protection to shared folders that are restrictive at least to a single parent folder.
```
                                  Gallery
          /               |                     |                \
         /                |                     |                  \
   Fam.A.Pics         Fam.B.Pics            Personal            Wedding A+B
   (Fam. A)            (Fam. B)            (not shared)          (Fam A & B)
```

In this example the `(shared links)` would be permanent and both Fam. A and Fam. B would be given two links each with passwords without having to worry about expiration date.

Not a perfect system but it would allow a bit more flexibility beyond needing to host separate instances for, in this case, 3 libraries.

**Comment by gklebus** [comment]
As a quick workaround, you could create links with a ridiculously long expiration date (e.g., 1200 months = 100 years). Practically permanent.

**Comment by Wdavery** [comment]
Definitely functionally equivalent, and what I'll be doing for now. 
Just seems like wasted logic for determine whether a link is expired when you never intend it to be.

**Comment by bpatrik** [comment]
I added this. (Explanation in the commit comment). Basically you can choose now: Validity: Forever that sets the validity date to 01/01/9999. And I'm not showing "time" left if that is longer than 10 years
