### ISSUE TITLE
URL /api/person does not honor Url Base setting

### ISSUE THREAD

**Issue by urlyb** [bpatrik/pigallery2#264]
In case of sub url configuration (i.e. http;//mydomain.com/pigallery) the call to the /api/person URL does not honor Url Base setting. Everything else seems to be working ok (api/admin, api/settings etc.).

**Environment (please complete the following information):**
 - OS: Linux / docker
 - Browser firefox
 - Apache reverse proxy
 
**Used app version**:
- docker-latest
- release v1.8.5

**Comment by bpatrik** [comment]
Hi,

Thanks for reporting. I added a fix to this, can you double check if its already working? (on the nightly build)

**Comment by urlyb** [comment]
Hi Patrik,

Great! The issue seems to be fixed in the nightly build (v1.8.6). By the way, there is also a problem with the same setting (Url Base) in case of sharing. Share URL doesn't include Url Base.

**Comment by bpatrik** [comment]
Try adding it to the page publicUrl:
![kép](https://user-images.githubusercontent.com/7512182/115296503-554ae680-a15b-11eb-98b6-6cc5d908b65f.png)

**Comment by urlyb** [comment]
I tried to change the publicURL setting, but I can't save the change - Save button stays grayed out. So, I tried changing the Page title and public URL at the same time. In this case I was able to click the save button, but PageURL property just defaulted back to the original value.

**Comment by bpatrik** [comment]
Oh, there was a bug in it. Fixed it.

**Comment by urlyb** [comment]
Can confirm, it works now. Thanks.
