### ISSUE TITLE
Clicking on a face forces guest logout

### ISSUE THREAD

**Issue by Wdavery** [bpatrik/pigallery2#269]
To reproduce:
1. Create a shared link
2. Login to said link
3. View a photo with a face tag
4. Click on the tag
5. Takes you to the shared link login page

I'm thinking this may be a "feature not a bug" (or side affect) as faces are not supported for guest users (#268)

If the guestuser cannot see all photos of a person, can we remove the link from the face tag? Forcing logout is definitely not ideal

**Comment by bpatrik** [comment]
Thanks. Indeed that should be disabled.

**Comment by Wdavery** [comment]
Just tried out that latest nightly build, with that commit. I'm still having the same issue despite search being disabled. Or is that just one part of the fix?

**Comment by bpatrik** [comment]
Do you see the errors with a sheared link or just normally, when you disable search?

**Comment by Wdavery** [comment]
Specifically when accessing via shared link (with search enabled in the settings). 
- Login with shared link
- Open photo
- Click on face
- Forced back to login page

I just tried with disabled search with admin user and it says faces not supported without search enabled, as expected. Regular user works as expected as well. 

With search disabled from the settings faces do not appear at all for any user or share. Is that intended behaviour? I'd expect the faces tab to be disabled but not the tags on photos themselves. 

---
Just to clarify my previous reply, when I said search disabled I did not mean disabled on the settings page. Just that it appeared disabled from a shared link perspective. Sorry for any mixup there.

**Comment by bpatrik** [comment]
I tried to reproduce it but could not. 
Created a shared link and none of the search links were working, while the search feature was enabled for the gallery (works as intended)

Can you make sure that you are using the latest nightly build?
you can see the version in the settings:
![kép](https://user-images.githubusercontent.com/7512182/117062005-29b32900-ad23-11eb-9131-413a6210636f.png)
Make sure the git commit is was build from, passed: f0f47f9, 

If you indeed use the latest, can you send a screenshot what you exactly mean?

**Comment by Wdavery** [comment]
I was behind on nightly, oops. Confirmed fully working now!
