### ISSUE TITLE
Keep the top information while scrolling

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#27]
This is more of an enhancement rather than an issue.
When browsing a folder, if I want to go back, I have to go to the top of the page in order to be able to navigate in the folder structure.
It would be nice to have it always available on the top of the page (top menu, navigation on the left and map on the right). Only the fotos would be scrolled.

(BTW, excellent new feature with the latest release. Thanks for it!!)

**Comment by bpatrik** [comment]
A good solution would be to let the top bar reappear when you start scrolling up a bit, so not a total fix.

**Comment by bpatrik** [comment]
Latest commits should support this.
