### ISSUE TITLE
Images and Folders not loading if '#' in path or filename

### ISSUE THREAD

**Issue by Vodes** [bpatrik/pigallery2#276]
**Describe the bug**
Pictures with a `#` in the filename dont load when clicking on them and dont generate thumbnails either.
I doubt its specific to webp images.
Subfolders also break if they contain a `#`

**Screenshots**
[Screenshot](https://vodes.pw/i/Alex/7MQe1ldEh5kRfcy.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Browser: Firefox

**Used app version**:
Docker, Version 1.8.5

**Comment by bpatrik** [comment]
Thanks for reporting. I will look into it. I think it is similar to #272

**Comment by bpatrik** [comment]
Latest commit should fix it
