### ISSUE TITLE
Huge directory thumbnails

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#279]
On desktop browsers (Firefox & Chrome) the directory browser uses huge thumbnails such that only 2 thumbnails display per row.

It seems to be caused by the browser window being sized in a "Portrait" shape: https://github.com/bpatrik/pigallery2/blob/6249d942c0d1098f0f128a817cfefd70c5c7365f/src/frontend/app/ui/gallery/directories/directories.component.ts#L22-L24

Can the portrait mode be removed, or only be triggered for _physically_ small displays?

**Comment by bpatrik** [comment]
Yes. That check is there for the phones basically. We probably need a better "small device" check.

**Comment by mcdamo** [comment]
What about using device detection? https://www.npmjs.com/package/ngx-device-detector
