### ISSUE TITLE
Error running translation script

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#28]
I've tried to run:
npm run add-translation -- --pt

However I got the following error:
npm ERR! missing script: add-translation

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-21T11_19_04_339Z-debug.log

Attached is the mentioned log file.
[2018-12-21T11_19_04_339Z-debug.log]
(https://github.com/bpatrik/pigallery2/files/2702598/2018-12-21T11_19_04_339Z-debug.log)

**Comment by angelmanst** [comment]
In the meantime I noticed I was not using the source project. I've cloned it into my environment and in the meantime I've run into missing modules issues. I was missing the following modules:
- gulp-typescript
- typescript
- gulp-zip
- run-sequence
- gulp-json-modify

So, I installed one by one with:

` npm install <module name>`

I ended up with the following error:

> osmc@angelcenter:~/TEMP/pigallery2/source$ npm run add-translation -- --pt
> 
> pigallery2@1.5.6 add-translation /home/osmc/TEMP/pigallery2/source
> gulp add-translation "--pt"
> 
> [17:44:24] Using gulpfile ~/TEMP/pigallery2/source/gulpfile.js
> [17:44:24] Starting 'add-translation'...
> [17:44:24] Starting 'extract-locale'...
> creating source translation file:  locale.source.xlf
> 
> /bin/sh: 1: ng: not found
> 
> [17:44:24] 'extract-locale' errored after 91 ms
> [17:44:24] Error: Command failed: ng xi18n --out-file=./../locale.source.xlf  --i18n-format=xlf --i18n-> locale=en
> /bin/sh: 1: ng: not found
> 
>     at ChildProcess.exithandler (child_process.js:204:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:886:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:497:12)
> [17:44:24] Finished 'add-translation' after 119 ms
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pigallery2@1.5.6 add-translation: `gulp add-translation "--pt"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pigallery2@1.5.6 add-translation script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/osmc/.npm/_logs/2018-12-21T17_44_24_392Z-debug.log

Attached the mentioned log:
[2018-12-21T17_44_24_392Z-debug.log](https://github.com/bpatrik/pigallery2/files/2703677/2018-12-21T17_44_24_392Z-debug.log)

**Comment by angelmanst** [comment]
Again, I've installed ng with:
`sudo apt-get install ng-common`

And got a different error:
>osmc@angelcenter:~/TEMP/pigallery2/source$ npm run add-translation -- --pt
>
>> pigallery2@1.5.6 add-translation /home/osmc/TEMP/pigallery2/source
>> gulp add-translation "--pt"
>
>[17:55:01] Using gulpfile ~/TEMP/pigallery2/source/gulpfile.js
>[17:55:01] Starting 'add-translation'...
>[17:55:01] Starting 'extract-locale'...
>creating source translation file:  locale.source.xlf
>
>/usr/bin/ng: line 40: exec: xi18n: not found
>
>[17:55:02] 'extract-locale' errored after 147 ms
>[17:55:02] Error: Command failed: ng xi18n --out-file=./../locale.source.xlf  --i18n-format=xlf --i18n-locale=en
>/usr/bin/ng: line 40: exec: xi18n: not found
>
>    at ChildProcess.exithandler (child_process.js:204:12)
>    at emitTwo (events.js:106:13)
>    at ChildProcess.emit (events.js:191:7)
>    at maybeClose (internal/child_process.js:886:16)
>    at Socket.<anonymous> (internal/child_process.js:342:11)
>    at emitOne (events.js:96:13)
>    at Socket.emit (events.js:188:7)
>    at Pipe._handle.close [as _onclose] (net.js:497:12)
>[17:55:02] Finished 'add-translation' after 178 ms
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! pigallery2@1.5.6 add-translation: `gulp add-translation "--pt"`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the pigallery2@1.5.6 add-translation script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /home/osmc/.npm/_logs/2018-12-21T17_55_02_198Z-debug.log

Attached the mentioned log:
[2018-12-21T17_55_02_198Z-debug.log](https://github.com/bpatrik/pigallery2/files/2703723/2018-12-21T17_55_02_198Z-debug.log)

**Comment by bpatrik** [comment]
Hi,

I have checked this error. 
You need to do following for the translation:
1. Download the source
2. install the source: `npm install`
3. add new language
  a) `npm run add-translation -- --fr`
  b) find the new language file in the translation folder and fix the language errors
4. rebuild the frontend app
 a) `npm install`
 b) OR you can build your own release with `npm run build-release`
5. you can make a pull request with the new file, so others can use it too :)

I think you were missing the 2. `npm install` part. I've updated the Readme.md to clarify this step.
Sorry for the inconvenience.

Best,
Patrik
