### ISSUE TITLE
Can't open 2 shared folders - they are getting mixed up

### ISSUE THREAD

**Issue by SlavikCA** [bpatrik/pigallery2#281]
**Steps to reproduce:**
- as a piGallery user, share folder1, share folder2
- log out. (Or use incognito session)
- open link1. folder 1 displayed, as expected.
- open link2. folder 1 displayed, while folder 2 is expected

Here is example of 2 of my photo shares:
- http://pix.slavikf.com/share/36ba3af4
- http://pix.slavikf.com/share/3dd0ab0d
Each link is working fine, but you can't open both links in one browser

**Environment (please complete the following information):**
 - Browser: Chrome 90 in Win10
 
**Used app version**:
- Docker latest of April, 26, 2021

**Comment by bpatrik** [comment]
Hi,

Yeah that is not possible. 
Switching from one link to an other not being possible is a bug.
But supporting both link to be open in one browser is a limitation. (cannot be fixed)

**Comment by calvinbui** [comment]
i have to log out as a Guest before I can open the 2nd link

**Comment by SlavikCA** [comment]
I noticed, that if I use share link, formatted differently, then everything works, as expected:

http://pix.slavikf.com/gallery/2018%2F2018%2005%20Penasco?sk=36ba3af4
http://pix.slavikf.com/gallery/2020%2F2020%2007%20Golden%20ears?sk=3dd0ab0d

The issues is only, if links are like this: http://pix.slavikf.com/share/???

So, Is it a bug with redirect logic? Looks like redirect uses ID, which stored in the browser session, not passed in URL?

**Comment by bpatrik** [comment]
ah, that is interesting. I will try to take a look.

**Comment by bpatrik** [comment]
Unfortunately this cant be support at the moment doe to session handling. You can open up two links but the session will be tight for the last one and if you go back to the previous tab, things will start breaking.

**Comment by SlavikCA** [comment]
It still would be better, if opening new link will switch the session to new share.

I think this is common use case:
- user share album1 and album2

Currently viewers are unable to open album2, because session is sticky to 1st album.

But if opening new link will switch albums - then viewer can go between album1 and album2.

Currently, switching between shared albums only possible by using "full" links, such as $HOST$/gallery/$PATH$?sk=$SHARE_ID$
And doesn't work by using $HOST$/share/$SHARE_ID$

**Comment by bpatrik** [comment]
I made some fixes in [53c8de3](https://github.com/bpatrik/pigallery2/commit/53c8de36956c8dc29a0cc756ab62a1613857e81b). The link that you opened last should work (i hope).

**Comment by SlavikCA** [comment]
It works now!
I tested with links in my first message here.

Thank you.
