### ISSUE TITLE
Random link is very limited

### ISSUE THREAD

**Issue by vomov** [bpatrik/pigallery2#284]
I've got a folder containing subfolders which I"d like to use with the 'random link' functionality. Think of a root folder named `baby`, containing subfolders with months.

The random link is then set up with a 'directory' filter, which:

- Cannot contain spaces (which makes sense, but okay)
- Only looks at the exact folder, and does not recurse through directories (it'll look in `baby`, but not in `baby/month_8`
- It does not seem to like wildcards (`month_*` gets no hits).

What I'd like is a way to create a random link that either accepts wildcards, or have the random link look beyond the starting folder. If this functionality is already present, but I've been too stupid/lazy to find it; sorry!

**Comment by bpatrik** [comment]
Random link has the same engine behind it as search.

You should be able to do 2 type of search:
1. exact match: `directory:"the directory"`
2. any match: `directory:(the directory)`

Both supports spaces. Should also support paths not just exact directory names.

This is code for that:
https://github.com/bpatrik/pigallery2/blob/0b24d60b44917a69aa052398c80b661f12dc8524/src/backend/model/database/sql/SearchManager.ts#L409-L430

**Comment by vomov** [comment]
That answers my question! Sorry, and thank you!

**Comment by bpatrik** [comment]
There was some issue with searching for `directory:(dir/subdir)`. Fixed that with the latest commit
