### ISSUE TITLE
Support Windows Live Photo Gallery face tags

### ISSUE THREAD

**Issue by mcwieger** [bpatrik/pigallery2#288]
I just installed pigallery2 and it appears face tags are not working. All my face tags are created with Windows Live Photo Gallery (stored in XMP tags), but no tags are shown when opening a picture. Regular keywords are working, but I believe those are EXIF.

Is there a setting I'm missing or is XMP not supported?

**Comment by bpatrik** [comment]
So far, the app support what Adobe Lightroom and exiftool uses for setting faces.

We can add Windows Live Photo Gallery support too. 
It should come here:
https://github.com/bpatrik/pigallery2/blob/cb10227e3c2c1f1895ba4d691115de824e30d6b5/src/backend/model/threading/MetadataLoader.ts#L258-L282

And a (small) test photo should go to the xmp test folder, similarly to this: https://github.com/bpatrik/pigallery2/blob/cb10227e3c2c1f1895ba4d691115de824e30d6b5/test/backend/unit/model/threading/MetaDataLoader.spec.ts#L29-L33

If you have time, you can also look into it, or you can send a sample photo here and I or someone will pick it up at some point.

**Comment by mcwieger** [comment]
Thanks for taking this into consideration. Unfortunately, I'm not a programmer, so can't help you with that. But here's a picture you can test.
![Arnie   Syl](https://user-images.githubusercontent.com/8181621/117542367-a3476180-b018-11eb-8fc7-9379b0534fb5.jpg)

**Comment by bpatrik** [comment]
Lets wait until #294 resolved.

**Comment by mcwieger** [comment]
Ah, I hadn't seen that one. Using exiftool is always a good idea 👍

**Comment by mcwieger** [comment]
Nobody appears to be using these tags anymore. I now copy the face tags to a different region and they appear in PG2. So can be closed from my end.
