### ISSUE TITLE
Can't change temp folder

### ISSUE THREAD

**Issue by mcwieger** [bpatrik/pigallery2#289]
I'm running pigallery2 in Docker on Synology. I'd like to keep this as clean as possible, so any data I want to store in mounted volumes (and I always mount a config and data folder as a minimum). My preferred locations for db and temp folder are:
- database file in /data/db
- temp folder in /data/tmp

I can change the path to the db folder, so that's no issue. However, when I change the temp folder from /app/data/tmp to /data/tmp, it switches back to /app/data/tmp and gives the messages 'Success Basic settings saved' and 'Restart the server to apply the new settings'. However, when I restart the container, the settings are not changed. I also tried setting default-Server-Media-tempFolder to /data/tmp, but this does not resolve it.

Looks like a bug.

**Comment by bpatrik** [comment]
In one hand, one should not change the location of temp and images folder within the container, but should mount them to a different place, like:
https://github.com/bpatrik/pigallery2/blob/cb10227e3c2c1f1895ba4d691115de824e30d6b5/docker/docker-compose/default/docker-compose.yml#L21-L25

If I understand correctly, this is also what you need.

On the other hand, yes, this should work. Can you make sure that the configuration folder is properly mounted? If that is not mounted and only lives within the container at every restart it will loose this setting. If the config is properly mounted and you can access it outside the container, you can just open it and change the temp value there.

Furthermore, you can try to force the setting this setting with CLI or ENV variables. 
You should set `Server-Media-tempFolder` not the default version. 

Let me know how it goes and based on that I can spend some time to debug it.

**Comment by mcwieger** [comment]
I mounted the folder to /app/data/tmp now, so no need to change it anymore.
