### ISSUE TITLE
It should be possible to start a single folder reindex

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#29]
Hi,

This is more of an enhancement.

I've been playing around within the folder, reorganizing and moving fotos between folder.
The issue is that it takes some time for pigallery to notice that some of the fotos are no longer within the folder and reindexing the folder.
It should be possible to start a reindex on a single folder rather than doing a full reindex of all folders.

**Comment by bpatrik** [comment]
Hi,

there was a bug with the automatic reindexing. Now it should be more responsible.
Let me know if solved your problem.
(the commit is not part of any release yet, you can check it if you rebuild the app from source or use docker nightly image)

Patrik
