### ISSUE TITLE
Config folder for Docker image

### ISSUE THREAD

**Issue by mcwieger** [bpatrik/pigallery2#290]
Is it possible to create a setting to set the configuration folder for the application running in a Docker container? Best practice in Docker is to set this to /config by default and mount a folder on the host machine to this, for easier upgrading etc.

**Comment by SlavikCA** [comment]
There is page in the project, which describes Docker setup:  
https://github.com/bpatrik/pigallery2/tree/master/docker

And it has example on how to set the configuration folder:

      docker run \
      -v <path to your config file folder>:/app/data/config \
     ...

**Comment by bpatrik** [comment]
Furthermore, you can also change the location of the config file. Please see the manpage: https://github.com/bpatrik/pigallery2/blob/master/MANPAGE.md

namely:
```
--config-path                    sets the config file location
```

**Comment by mcwieger** [comment]
Of course, my bad. Thx for your quick response.
