### ISSUE TITLE
OMV5 docker problem

### ISSUE THREAD

**Issue by jerry-hager** [bpatrik/pigallery2#297]
I am using raspberry pi 4, OMV5 with docker.
Installed the pigallery2 container.
Can not reach the website, page not found
No further errors
all other docker containers work well

**Comment by bpatrik** [comment]
Context from mail.

container output:
```
5/3/2021, 8:57:20 PM[INFO] [server] running diagnostics...

(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
5/3/2021, 8:57:21 PM[INFO] [JobManager] Running job schedules
5/3/2021, 8:57:21 PM[INFO] [server] Listening on port 80
(node:20) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
```

**Comment by bpatrik** [comment]
There is not enough info here to know the issue. My wild guess is that you do not bind the port to the host.

**Comment by jerry-hager** [comment]
I bind port 81 (and tried another) to port 80

**Comment by jerry-hager** [comment]
> There is not enough info here to know the issue. My wild guess is that you do not bind the port to the host.

What can i present to help finding the ' error'?

**Comment by bpatrik** [comment]
Can you provide more details about the setup?

* What operation system are you using?
* Which docker version are you running?
* How are you running the app (docker compose?, direct docker container?)
* Did you set up the mounted volumes properly? (see docker docs in this repo for detalis)
* What is the full docker log? You can also set the logging level in the config to `silly` to see all the logs or through cli or ENV variable, see MANPAGE.md. (Or If I recall correctly setting `NODE_ENV=debug` results in the same behavior, but not sure)
* Can you see on your host that the port is properly mounted?
* What error do you see in the browser, when you try to navigate there?
