### ISSUE TITLE
Keywords and exif data don't seems to be working

### ISSUE THREAD

**Issue by neoxius** [bpatrik/pigallery2#3]
First of all, thanks for this amazing project I really enjoy it in my PI B+. 

Unfortunately I'm currently having issues with metadata related stuff, it seems that keywords are not being recognized. I tried to modify them in the DB having success but it lasts until a new photo is added. When this happens, it seems like the DiskMangerWorker is deleting the values. Any advice?

Im running pigallery2@1.0.0-rc.1

Thanks in advance!

**Comment by neoxius** [comment]
was my fault, files had bad exif data, works like a charm!

**Comment by bpatrik** [comment]
I'm glad that you could make it work :)

If you update a folder, the app rescans/indexes it (all photos in that folder).

**Comment by bpatrik** [comment]
P.s.: If you are running it on a low-end device, you can use these tricks to limit memory usage:
`node backend/index.js  --max-executable-size=96 --max-old-space-size=128 --max-semi-space-size=1 --expose-gc `
this limits the available memory (my slow down the app itself) It is not super tested, so might be unstable:
`--max-executable-size=96 --max-old-space-size=128 --max-semi-space-size=1`
This let the app to trigger the gc manually and clean up after a folder scan:
`--expose-gc`
