### ISSUE TITLE
Wrong entry used while editing "Basic" config

### ISSUE THREAD

**Issue by SlavikCA** [bpatrik/pigallery2#311]
**Steps:**
- open "Settings"
- change the "Page title"
- SAVE

**Bug:**
- the "Images folder" entry has been changed, even though I made no changes to it. The value for "Images folder" got copied from the "Temp folder"

The bug reproduced in SIMPLIFIED and in ADVANCED mode

**Environment:**
- Chrome on Win 10

**Used app version**:
-  image: bpatrik/pigallery2:nightly-alpine, as of May 25, 2021

**Comment by bpatrik** [comment]
Basic settings were always a black sheep amoung all settings.

Pls set thing directly in the config.json until I fix it for good.
