### ISSUE TITLE
Language switch not working

### ISSUE THREAD

**Issue by andrewtheshiny** [bpatrik/pigallery2#32]
I'm running the docker version and the app is great. However, I tried switching the language and I get this error: 

{"error":{"code":9,"message":"Unknown server side error"},"result":null}

Have I configured something wrong?

**Comment by bpatrik** [comment]
Can you give me some more details about it?
Which image are you using? I tried to reproduce it with `bpatrik/pigallery2:nightly-stretch`, but I did not see the error.
Can you try starting it with `-e NODE_ENV=develop` and checking / sending the docker log? (you can see the docker log with `docker logs <container id>` if you run it as daemon).

**Comment by andrewtheshiny** [comment]
I tried it again today on a clean VM with the same result.

Here is my docker-compose.yml

--- cut here ---
version: '3'

services:
    pigallery2:
        container_name: pigallery2
        ports:
            - 80:80
        environment:
            - NODE_ENV=develop
        volumes:
            - /home/andrew/pigallery2/config/config.json:/pigallery2-release/config.json
            - /vantec/data/media/photos:/pigallery2-release/demo/images
            - /home/andrew/pigallery2/temp:/pigallery2-release/demo/TEMP
       image: bpatrik/pigallery2:nightly-stretch
--- cut here –

Here are the logs:

--- cut here ---

> pigallery2@1.5.6 start /pigallery2-release
> node ./backend/index.js

1/2/2019, 5:35:29 PM[[34mDEBUG[39m] [server] Running in DEBUG mode, set env variable NODE_ENV=production to disable
1/2/2019, 5:35:29 PM[[32mINFO[39m] [server] running diagnostics...
1/2/2019, 5:35:29 PM[[32mINFO[39m] Updating database scheme
1/2/2019, 5:35:29 PM[[32mINFO[39m] [server] using config:
1/2/2019, 5:35:29 PM[[32mINFO[39m] [server] {
      "Client": {
            "applicationTitle": "PiGallery 2",
            "Thumbnail": {
                  "concurrentThumbnailGenerations": 1,
                  "thumbnailSizes": [
                        200,
                        400,
                        600
                  ],
                  "iconSize": 45
            },
            "Search": {
                  "enabled": true,
                  "instantSearchEnabled": true,
                  "autocompleteEnabled": true,
                  "InstantSearchTimeout": 3000,
                  "autocompleteCacheTimeout": 3600000,
                  "searchCacheTimeout": 3600000,
                  "instantSearchCacheTimeout": 3600000
            },
            "Sharing": {
                  "enabled": true,
                  "passwordProtected": true
            },
            "Map": {
                  "enabled": true,
                  "mapProvider": 0,
                  "mapboxAccessToken": "",
                  "tileUrl": ""
            },
            "RandomPhoto": {
                  "enabled": true
            },
            "Video": {
                  "enabled": true
            },
            "MetaFile": {
                  "enabled": true
            },
            "Other": {
                  "captionFirstNaming": false,
                  "enableCache": true,
                  "enableOnScrollRendering": true,
                  "enableOnScrollThumbnailPrioritising": true,
                  "defaultPhotoSortingMethod": 3,
                  "NavBar": {
                        "showItemCount": true
                  }
            },
            "authenticationRequired": true,
            "unAuthenticatedUserRole": 4,
            "publicUrl": "",
            "urlBase": "",
            "languages": []
      },
      "Server": {
            "port": 80,
            "host": "0.0.0.0",
            "imagesFolder": "demo/images",
            "thumbnail": {
                  "folder": "demo/TEMP",
                  "processingLibrary": 3,
                  "qualityPriority": true
            },
            "sessionTimeout": 604800000,
            "photoMetadataSize": 524288,
            "database": {
                  "type": 3,
                  "mysql": {
                        "host": "",
                        "username": "",
                        "password": "",
                        "database": ""
                  },
                  "sqlite": {
                        "storage": "sqlite.db"
                  }
            },
            "sharing": {
                  "updateTimeout": 300000
            },
            "threading": {
                  "enable": true,
                  "thumbnailThreads": 0
            },
            "indexing": {
                  "folderPreviewSize": 2,
                  "cachedFolderTimeout": 3600000,
                  "reIndexingSensitivity": 2
            }
      }
}
1/2/2019, 5:35:29 PM[[35mSILLY[39m] Creating thread pool with 1 workers
1/2/2019, 5:35:29 PM[[34mDEBUG[39m] Worker 46 is online, worker count: 1
1/2/2019, 5:35:29 PM[[34mDEBUG[39m] SQL DB inited
1/2/2019, 5:35:29 PM[[34mDEBUG[39m] Worker is waiting for tasks
1/2/2019, 5:35:29 PM[[32mINFO[39m] [server] Listening on port 80
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET / 304 14ms
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET /runtime.ec2944dd8b20ec099bf3.js 200 6ms
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET /main.6e8acfcedd2d1f5fcc6e.js 304 5ms
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET /polyfills.55b2e3ec6ffca12a3c3f.js 200 10ms
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET /styles.a42cde6c1ac355926947.css 200 21ms
1/2/2019, 5:37:37 PM[[34mDEBUG[39m] GET /assets/icon.png 200 1ms
1/2/2019, 5:37:38 PM[[36mVERBOSE[39m] GET / 200 3ms
1/2/2019, 5:37:43 PM[[34mDEBUG[39m] GET /hu 302 4ms
1/2/2019, 5:37:43 PM[[33mWARN[39m] Handled error:
      {"code":9,"message":"Unknown server side error","details":{"code":7,"message":"ENOENT: no such file or directory, open '/pigallery2-release/dist/en/index.html'"}}
1/2/2019, 5:37:43 PM[[34mDEBUG[39m] GET /?ln=hu 200 2ms
1/2/2019, 5:39:20 PM[[36mVERBOSE[39m] GET / 200 2ms
1/2/2019, 5:39:20 PM[[36mVERBOSE[39m] GET / 200 1ms
1/2/2019, 5:39:20 PM[[34mDEBUG[39m] GET /assets/icon.png 404 1ms
1/2/2019, 5:39:26 PM[[34mDEBUG[39m] POST /api/user/login 200 56ms
1/2/2019, 5:39:26 PM[[36mVERBOSE[39m] GET /api/notifications 200 1ms
1/2/2019, 5:39:26 PM[[35mSILLY[39m] [DiskManager] scanning directory: ./
1/2/2019, 5:39:26 PM[[36mVERBOSE[39m] GET /api/gallery/content/?knownLastModified=1546386620142&knownLastScanned=1546450300326 200 76ms
1/2/2019, 5:39:27 PM[[34mDEBUG[39m] GET /assets/icon.png 404 1ms
1/2/2019, 5:39:27 PM[[34mDEBUG[39m] GET /favicon.ico 404 1ms
--- cut here ---

I get the same error if I run it via the docker command line.

…Andrew

**Comment by andrewtheshiny** [comment]
Awesome. Works like a charm. Thanks.

…Andrew
