### ISSUE TITLE
Include mysql as dependencies not optional dependencies

### ISSUE THREAD

**Issue by martadinata666** [bpatrik/pigallery2#322]
As the app support both mysql and sqlite, but only sqlite3 included as dependencies. mysql included as optional dependencies.

Also how to reproduce:
build pigallery2 by using ```--omit=optional```
Full command: ```npm install --production --omit=optional```

expected behavior:
Mysql connection work on the fly on switching.

**Comment by bpatrik** [comment]
The docker build should include mysql and if someone build from sources,
should be able to force it or remove it.

Let me know if it doesn't work from docker.

-- Sorry for being brief, sent from my phone.

Dedy Martadinata S ***@***.***> ezt írta (időpont: 2021. jún.
9., Sze 8:35):

**Comment by martadinata666** [comment]
oh i see, thanks for the clue, got it working.
I tried build my own custom docker image, and prefer using from distro ffmpeg instead from npm. And use ```--omit=optional``` but it also remove the ```mysql``` because it included in ```optionalDependencies```.

**Comment by bpatrik** [comment]
Yeah that is the case for the docker too (not using npm ffmpeg) so I did
some magic gulp build to avoid ffmpeg but keep mysql. You can check the
docker file for the executed command.



-- Sorry for being brief, sent from my phone.

Dedy Martadinata S ***@***.***> ezt írta (időpont: 2021. jún.
9., Sze 10:52):

**Comment by martadinata666** [comment]
After browse around the workflow, i get what i need 
```npm run create-release -- --skip-opt-packages=ffmpeg,ffprobe --force-opt-packages``` 
That command i need, to create a release without ffmpeg, as the readme just create-release that will include everything.

Thanks 👍🏼
