### ISSUE TITLE
Docker pull returning Error manifest unknown 

### ISSUE THREAD

**Issue by meldarionqeusse** [bpatrik/pigallery2#326]
**Describe the bug**

when I am trying to install pigallery2 using the docker-compose.yml file I am getting manifest unknown. Tried docker pull bpatrik/pigallery2 as well same result.

**Comment by bpatrik** [comment]
There is an issue with `latest`˛tag,  please use `latest-debian-buster `. I made a not the the docker readme to clarify it.

**Comment by meldarionqeusse** [comment]
thank you
