### ISSUE TITLE
Choose Album Cover

### ISSUE THREAD

**Issue by GiamBoscaro** [bpatrik/pigallery2#329]
**Is your feature request related to a problem? Please describe.**
I cannot choose the album cover

**Describe the solution you'd like**
I'd like to be able to choose an album cover from the images inside the album (facebook like)

**Describe alternatives you've considered** (optional)
None

**Comment by wechsler42** [comment]
I would like to second this feature request.

**Comment by bpatrik** [comment]
This is a duplicate of #80 please follow the conversation there.
