### ISSUE TITLE
docker-compose.yaml files refer to non-existent image

### ISSUE THREAD

**Issue by gabrielwhite** [bpatrik/pigallery2#330]
the sample docker-compose.yaml refers to non-existent image

bpatrik/pigallery2:latest

It should be something like:

bpatrik/pigallery2:latest-alpine
bpatrik/pigallery2:latest-stretch

**Comment by bpatrik** [comment]
yes `latest` is temporary unavailable do to an issue in:
https://github.com/bpatrik/pigallery2/blob/3e33d8ab895cf532ba3d79a400478274740da981/.github/workflows/build.yml#L152-L163

 see README and https://github.com/bpatrik/pigallery2/issues/326#issuecomment-864546136

**Comment by gabrielwhite** [comment]
Thanks.

**Comment by bpatrik** [comment]
Lets keep it open, so people can find it. (Or I can flag thing to be a duplicate of it :) )

**Comment by bpatrik** [comment]
it is fixed with the latest release
