### ISSUE TITLE
Does it reindex if new photos are added to existing folders?

### ISSUE THREAD

**Issue by danmed** [bpatrik/pigallery2#333]
**Is your feature request related to a problem? Please describe.**
I can see it mentions if you add a new folder it will reindex.. but does it detect new photos / videos in existing indexed folders?

**Describe the solution you'd like**
Would be nice if it reindexed when it finds a new file...or atleast on a schedule.

Apologies if this is documented somewhere that i havn't found!

**Comment by martadinata666** [comment]
yes, it will. i used it to monitor my photo upload
