### ISSUE TITLE
Translation attempt failure (Win 10) 

### ISSUE THREAD

**Issue by vdergachev** [bpatrik/pigallery2#34]
Hi there,

Tried to translate gallery to Russian, but no luck. I have downloaded sources from `https://github.com/bpatrik/pigallery2/archive/master.zip`
after that 
`npm install`
and 
`npm run add-translation -- --ru`

My output is here https://gist.github.com/vdergachev/022e52dd34c99c1ca4d93af73c291709

frontend\translate folder contains 3 files:
- messages.en.xlf
- messages.hu.xlf
- messages.ru.xlf

My environment - windows 10 x64, NPM 5.6.0

Thanks in advance

**Comment by bpatrik** [comment]
Hi,

unfortunately there are some issues with the google translate part of [xlf-google-translate](https://github.com/bpatrik/xlf-google-translate) (I'm using this lib for translation). 
I managed to fix it for now. 
If you see the error again: `messages.ru.xlf` is actually still valid, just the english texts are not translated automatically with google to your language (they stay english).

**Comment by vdergachev** [comment]
Great, now it works. Will create PR with translation later. 
Thanks
