### ISSUE TITLE
Direct links to images

### ISSUE THREAD

**Issue by MasterGroosha** [bpatrik/pigallery2#343]
**Is your feature request related to a problem? Please describe.**
I'd like to use pigallery2 as personal photo hosting with the ability to use images URLs in self-hosted blog

**Describe the solution you'd like**
To be able to get direct links to images for hotlinking. However, this creates some problems like "should it be possible to get direct links to private folders" or "How to deal with temporarily shared images"

**Describe alternatives you've considered** (optional)
Running an nginx container looking at the same images directory as pigallery2. This creates another layer of problems like bruteforcing paths.

**Comment by bpatrik** [comment]
I think this is a duplicate of #257 please see comments there.

**Comment by MasterGroosha** [comment]
Looks like really a duplicate, sorry! Closing the issue.
