### ISSUE TITLE
Add this docker on Unraid AppCommunity

### ISSUE THREAD

**Issue by thymon13** [bpatrik/pigallery2#347]
Hello there !

Please add this great app in UNRAID  : [https://unraid.net/community/apps](https://unraid.net/community/apps)

**Comment by rhatguy** [comment]
I think this is basically complete.  I'm running pigallery2 in unraid successfully from the below repo.

https://github.com/ItJustFox/unraidtemplate/tree/main/PiGallery2

**Comment by bpatrik** [comment]
I see it uses `nightly-debian-buster`. Its not good,, but not terrible. I will leave as it is.
