### ISSUE TITLE
1.9.0 tag not found on docker hub

### ISSUE THREAD

**Issue by bseclier** [bpatrik/pigallery2#348]
Hello,
I was using the 1.8.5 tag for getting the pigallery2 image from docker hub (not alpine or stretch).
I can see that there is no 1.9.0 tag anymore. Will you add it further or should I change my tag for alpine or stretch ?

If I have to change from 1.8.5, can I use any of the new 1.9.0 stretch or alpine without breaking my current installation ?
Thanks for your help.
Cheers,

**Comment by bpatrik** [comment]
There is some issue with the docker tag aliasses, see readme: https://github.com/bpatrik/pigallery2/tree/master/docker

1.8.5 was an alias to one of the debian releases (i think stretch)

I recommend choosing tag that is closest to your host machine setup. If you do not know, i can recommend `latest-debian-buster`.

Upgrading to the new version, you might loose some config setup (like if the config was moved to a different place in the config.json hierarchy or got deleted. Also most likely you will need to reindex the DB.)

You can check the release notes about what you would get from the upgrade: https://github.com/bpatrik/pigallery2/releases/tag/1.9.0

**Comment by bseclier** [comment]
Thank you for your answer. I tried with the 1.9.0 buster tag, the "migration" worked but some of my folder are unavailable since this upgrade (I go back to the parent folder when I click on it).
I rolled back in 1.8.5.

**Comment by bpatrik** [comment]
That sounds odd.
I can Imagen some database issues. Deleting the DB and reindexing should
solve it.

-- Sorry for being brief, sent from my phone.

Benjamin SECLIER ***@***.***> ezt írta (időpont: 2021. aug.
1., V 14:58):
