### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by cbhushan** [bpatrik/pigallery2#350]
[AVIF](https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF)) is a modern and effiecint image format and [is supported on most recent browsers](https://caniuse.com/avif). I verified that my chromium version was able to load and show sample avif images. It would be nice to support it in pigallary2 as well (I tried and pigallary2 does not show it).

**Background:** AVIF is based on [AV1 coding](https://en.wikipedia.org/wiki/AV1), which is an open, royalty-free video coding format and is successor of VP9 (codec used in most webm files). It is being developed by the Alliance for Open Media (AOMedia). The governing members of the [Alliance for Open Media](https://en.wikipedia.org/wiki/Alliance_for_Open_Media) are Amazon, Apple, ARM, Cisco, Facebook, Google, Huawei, IBM, Intel, Microsoft, Mozilla, Netflix, Nvidia, Samsung Electronics and Tencent. In other words, it will be very likely be the next generation of jpeg in terms of adoption. Although, [WebP 2](https://chromium.googlesource.com/codecs/libwebp2/) might be another one.

**Comment by cbhushan** [comment]
Some samples on links below:

* http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF
* https://colinbendell.github.io/webperf/animated-gif-decode/avif.html
* https://github.com/link-u/avif-sample-images

**Comment by bpatrik** [comment]
Its a bit of stretch that modern browsers support it (like Safari or any Microsoft browser does not support it).

You can try to enable for yourself, just add the extension here: https://github.com/bpatrik/pigallery2/blob/2b89bc49ab1019c383514b49cca8e8ba55a7d790/src/common/SupportedFormats.ts#L1-L8

**Comment by bpatrik** [comment]
Closing this due to lack of edge and safari support.

**Comment by SlavikCA** [comment]
@bpatrik 

I tried to add `avif` to that list, but `avif` files still not listed in UI

+1 for AVIF support: even though Safari doesn't support it - it can be supported via polyfill:
https://github.com/Kagami/avif.js

**Comment by bpatrik** [comment]
In the long term these "more exotic" extension can be supported with encoding, like raw photos (they are also not yet supported).

 >I tried to add avif to that list, but avif files still not listed in UI
 Did you re build both frontend and backend? also did you reindex the folder?

**Comment by 02015678** [comment]
Hi, may be it's time to consider add AVIF support again?

AVIF is supported by browsers below
Safari 16 
Chrome 85
Firefox 86

**Comment by rohit-n** [comment]
If anyone is interested, I made a branch that has AVIF support, including EXIF tags.

https://github.com/rohit-n/pigallery2/tree/avif

**Comment by SlavikCA** [comment]
> If anyone is interested, I made a branch that has AVIF support, including EXIF tags.
> 
> https://github.com/rohit-n/pigallery2/tree/avif

@rohit-n Are you planning to create PR to upstream your changes?

**Comment by rohit-n** [comment]
I don't mind, but I'm not proficient in TypeScript and can't guarantee I can make adjustments if they're needed. I'll make one any way so that it gets attention.

**Comment by bpatrik** [comment]
My plans for now is to make the current release as it is. (No new feature)

In the new release I'm considering adding add-on support. Changes like this
would be easy to add to the app that way.

-- Sorry for being brief, sent from my phone.
