### ISSUE TITLE
Provide apple-touch-icon

### ISSUE THREAD

**Issue by numen31337** [bpatrik/pigallery2#351]
**Is your feature request related to a problem? Please describe.**
I use pigallery2 on my iPhone as an app saved on the desktop and it works fine. I'm really happy with everything, but the icon of this app is very off-putting. Instead of an icon, a small version of the gallery itself is displayed. It looks unpleasant and some users might have privacy issues.

![123](https://user-images.githubusercontent.com/5677845/128683963-82e67b81-a4be-4e26-8ade-5c007df37769.jpg)

**Describe the solution you'd like**
I suggest providing an [`apple-touch-icon`](https://web.dev/apple-touch-icon), as I understand this should solve the problem.

**Comment by bpatrik** [comment]
Hi,

Thanks for the suggestion. Feel free to send me a PR about this.

**Comment by desertwitch** [comment]
This can be closed as of #407
