### ISSUE TITLE
Can’t access sub/sub folder with reverse proxy

### ISSUE THREAD

**Issue by floriangeyer** [bpatrik/pigallery2#361]
Hello, I set up a reverse proxy (apache) to my gallery. I can’t navigate to a sub/sub folder like `https://photos.mydomain.com/gallery/subfolder1%2Fsubfolder2` instead it directs me back to `https://photos.mydomain.com/gallery/`. No problem while accessing the gallery through the specified port though. I know, it’s more likely a misconfiguration of the reverse proxy. Any advice on this?

Thanks,
Florian

**Comment by meldarionqeusse** [comment]
Did you solve this issue? I have the same problem would appreciate if you share your solution of you managed to find one. Thanks

**Comment by meldarionqeusse** [comment]
I have figured the solution for Apache reverse proxy @bpatrik I had to add `AllowEncodedSlashes On`

<VirtualHost *:443>
 ServerName youdomain.com
 ProxyPreseveHost On
 ProxyRequests Off
 AllowEncodedSlashes On

 ProxyPass / http://localhost:2342/
 ProxyPassReverse / http://localhost:2342/

 SSLCertificateFile /etc/letsencrypt.... # patg to your certificate file
 SSLCertificateKeyFile /etc/letsencrypt.... # path to you key file

</VirtualHost>

**Comment by floriangeyer** [comment]
Great! I didn't figure it out yet. I closed this issue because I created a thread on discussions. Going to try this.
