### ISSUE TITLE
Random image sorting

### ISSUE THREAD

**Issue by kartotoffel** [bpatrik/pigallery2#37]
PiGallery2 is exactly what I was searching for and I really love it! The only thing I'm missing is the ability to sort the images randomly. At the moment you can only sort by date and name, resulting in seeing the same pictures over and over again when logging in (and scrolling down). It would be awesome to be able to spice it up a little by having them randomly sorted :)

**Comment by bpatrik** [comment]
OK, I'll add the random listing option in the near future,

**Comment by bpatrik** [comment]
Hi,

I've added this feature with one of my [latest commit](https://github.com/bpatrik/pigallery2/commit/a61337353709375ba33858721b9c67b77296389e).

Best,
Patrik
