### ISSUE TITLE
Navigating to nested folders result in 404

### ISSUE THREAD

**Issue by zurvan2** [bpatrik/pigallery2#371]
Top level folders work correctly, but any folder nested inside of those results in a 404, and the user is dropped back to the top-level images folder. 

**Screenshots (optional)**

![Screenshot 2021-09-30 175443](https://user-images.githubusercontent.com/59699982/135535544-b522e79a-d27d-456e-9b61-04a6d56c47b4.png)

**Server logs (optional)**

No relevant logs. (Is there a way to enable access logs?)

**Environment (please complete the following information):**
 - OS: debian bullseye, but using docker-compose 
 - Browser: firefox on windows, chrome on android

**Used app version**:
- bpatrik/pigallery2:latest-debian-buster
- IMAGE ID: 7de7cb391963

**Comment by zurvan2** [comment]
I figured this out. I am using apache for ssl termination and proxy. In the latest version of apache in debian buster, apparently you now need to set 

AllowEncodedSlashes On

to let this work.

**Comment by florihupf** [comment]
Thank you, thank you!

**Comment by alexislefebvre** [comment]
> I figured this out. I am using apache for ssl termination and proxy. In the latest version of apache in debian buster, apparently you now need to set
> 
> AllowEncodedSlashes On
> 
> to let this work.

Thanks! I added a PR in order to add it to the README: 

- #668
