### ISSUE TITLE
Asynchronous Folder Thumbnailing 

### ISSUE THREAD

**Issue by desertwitch** [bpatrik/pigallery2#381]
At the moment non-cached folder thumbnails are not received asynchronously, but rather a single database query is sent for every single folder synchronously, and only then the directory listing (gallery) is eventually built when everything else is already available. Therefore the availability of the directory listing (gallery) itself is delayed until a thumbnail was received for every single folder, which can result in the whole application becoming unavailable while these queries are running on particularly large folders or subfolders. (tested 700 subfolders, takes **minutes**!)

It would be better to initially build the directory listing (gallery) with blank folder thumbnails for it to become available fast, which are then filled in with actual folder thumbnails asynchronously, like it is already done when viewing folders containing only images (not subfolders/subfolders & images). Like for images, there should also be an option that only folder thumbnails are received for the immediate visible folders (lazy image rendering)

**This is what is currently happening BEFORE the directory listing is built (with the loading bar filling on top of the page)**:

`query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC LIMIT 1 -- PARAMETERS: [3380,"Dir1/*"]`

`query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC LIMIT 1 -- PARAMETERS: [3381,"Dir2/*"]`

[...] _**x** number of subfolders in navigated directory_

I, therefore, propose the directory listing (gallery) is built immediately with blank folder thumbnails, which are then exchanged for actual folder thumbnails with the above queries running asynchronously in the background. The unfinished queries should also be cleared from the asynchronous queue when the user navigates away from the folder before all thumbnails were built, instead of continuing to run in the background and eat up database resources (as it is currently happening).

P.S. I have tested this on a project with all folders pre-indexed and pre-thumbnailed on an SSD, so there should be no further bottlenecks apart from these synchronous thumbnailing queries.

P.P.S I have run further testing and can confirm that these queries, receiving the folder thumbnails from the database, are the bottleneck here. If I let the particular function return "null" on every requested folder thumbnail, the directory listing becomes available instantly with blank thumbnails even on folders with 700+ subfolders.

This might also be relevant for #299

**Comment by desertwitch** [comment]
Did some more testing. It seems that what actually delays the directory listing is that for each folder a media object is requested from that folder for the thumbnailing job. This results in a query for each folder to retrieve one media object from that folder to use for thumbnailing. If that query could happen asynchronously, then the directory listing could already be shown to the user and the thumbnailing job start when the media object from the folder becomes available?

**Comment by bpatrik** [comment]
hi,

directory listing is a bit complex.
It depends:
* DB or no DB usage
* last index time
* indexing severity

Lets take a szimple / most common approach:
DB, recently indexed, low/medium reindexing severity:

1. no re-indexing will occur, or it will be done asynchronously, happens here: https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/GalleryManager.ts#L36
2. cheks the requeted dir: https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/GalleryManager.ts#L44
3. adds more data to the requested dir: https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/GalleryManager.ts#L83
4. gets the faces and sub direcotry thumbnails:https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/GalleryManager.ts#L253
5. gets preview for sub directories, one at a time from here https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/GalleryManager.ts#L222, using this: https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/backend/model/database/sql/PreviewManager.ts#L82


The last step got recently introduced as people wanted to customize directory thumbnails. Caching the preview photo instead of querying it all the time would probably significantly speed up the listing.

I got rather busy lately, I do not think I will have the time for that any time soon, sorry :/

**Comment by desertwitch** [comment]
Thanks for the answer, what I don't understand is why the database queries for the preview media need to happen **before** the directory listing is shown. Can they not happen **afterwards** so the directory listing is shown first? If I open a folder with 700 subfolders the directory listing takes minutes because all these database queries for the preview media are run first.

These queries for a single media object from each folder are all running before the directory listing is shown, and **only when all of them are complete the directory listing is shown**. Is it not better to have the directory listing available as fast as possible for navigating, rather than getting a single media object from each folder for later thumbnail creation before the actual directory listing?

_query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC **LIMIT 1** -- PARAMETERS: [3380,"Dir1/*"]_

_query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC **LIMIT 1** -- PARAMETERS: [3380,"Dir2/*"]_

_query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC **LIMIT 1** -- PARAMETERS: [3380,"Dir3/*"]_

_query: SELECT "media"."id" AS "media_id", "media"."name" AS "media_name", "directory"."name" AS "directory_name", "directory"."path" AS "directory_path", "directory"."id" AS "directory_id" FROM "media_entity" "media" INNER JOIN "directory_entity" "directory" ON "directory"."id"="media"."directoryId" WHERE ("media"."directoryId" = ? OR "directory"."path" GLOB ?) ORDER BY LENGTH("directory"."path") DESC, "media"."metadataRating" DESC, "media"."metadataCreationdate" DESC **LIMIT 1** -- PARAMETERS: [3380,"Dir4/*"]_

**Comment by bpatrik** [comment]
Yes, indeed this would be an optimization.

But I would rather just de-normalize the table and "cache" the preview image, then the listing would go with one query instead of N.

**Comment by desertwitch** [comment]
> Yes, indeed this would be an optimization.
> 
> But I would rather just de-normalize the table and "cache" the preview image, then the listing would go with one query instead of N.

That sounds like a good idea, but I honestly have no idea how to do it.
It would be great if the performance of folders with many subfolders could be improved this way. :-)

**Comment by bpatrik** [comment]
Yeah it would require a more complex development.

DataManagers know if there was a database update. Like Album manger does something similar. It invalidates the album previews: https://github.com/bpatrik/pigallery2/blob/db9889ed2cf2202be964199035fb2240c3eb145b/src/backend/model/database/sql/AlbumManager.ts#L76-L92

Something similar would be needed for directories too. Probably a bit smarter as not all Directory need t be updated if a new photo was added, just all parent dir of that photo.

**Comment by myroik** [comment]
+1, its a shame the application stop responding and need total restart because of eternal load time of listing and preview images... cannot use for very large database (like photographer).

**Comment by bpatrik** [comment]
776c8e8 introduces a column to store the directory previews. This should speed up the listing. (not first time ever listing will be still slow. assigning preview is lazy. They are assigned only when they are needed)

**Comment by desertwitch** [comment]
Amazing, thanks a lot!
Can't wait to test it once it's pushed to Docker.

**Comment by bpatrik** [comment]
nightly should have it already

**Comment by desertwitch** [comment]
I have just had the chance to test this and the performance is **significantly** improved. A test database on MySQL with 2.5 million images in 800 folders (4 folders with 200 subfolders each) is running smoothly with minor loading times and no crashes. Initial preview building times are acceptable and once the database is filled with preview IDs there is almost no loading time for the directory listings. 

Thank you so much for addressing this issue and taking the time to code this, I am sure people with especially large databases will be very happy that this works so well now. THANK YOU! 🥇

**Comment by bpatrik** [comment]
wow nice size of a gallery. Happy that it works, did not have time for extensive testing. 
in 69fedd6 I created a `Preview Filling` job that should populate all previews (Album, Person and Directory).  I recommend running it right after indexing.

**Comment by desertwitch** [comment]
This has been implemented and is working well since https://github.com/bpatrik/pigallery2/commit/69fedd6c67384a5fab42697e54e14baf813c616b
