### ISSUE TITLE
Pigallery2 as a service doesn't start the server

### ISSUE THREAD

**Issue by Tos26** [bpatrik/pigallery2#382]
hello,

I installed Pigallery2 from release without Docker following the installation guide given [here](https://github.com/bpatrik/pigallery2#12-direct-install-if-you-are-familiar-with-nodejs-and-building-npm-packages-from-source).
It's done and works properly with NGINX as proxy server.

- Raspberry PI 3B+
- Rasbian Buster.
- Nginx 1.14.2
- Pigallery2 v1.9.0

But I tried to initialize a systemd service in order to start automatically the server. I setup the service as described [here](https://github.com/bpatrik/pigallery2/issues/42#issuecomment-458340945). 

First, I think there is a mistake in the file description: `ExecStart=/usr/bin/node backend/index.js --expose-gc`
src is missing : `ExecStart=/usr/bin/node src/backend/index.js --expose-gc`

Despite that fix, the service seems to start correctly but the server is not running.
**
![image](https://user-images.githubusercontent.com/23366980/140809431-ab0fd117-eda4-45ec-aad4-836a55f13720.png)
**
I checked all the parameters and they match my configuration:
`WorkingDirectory=/var/www/pigallery2`
`ExecStart=/usr/bin/node src/backend/index.js --expose-gc`
`User=www-data`

Someone can help me on that strange behavior ?

Thanks

**Comment by bpatrik** [comment]
Hi,

does this help:  https://github.com/bpatrik/pigallery2/issues/70

sorry for the short reply, super busy lately.

**Comment by Tos26** [comment]
Thank you Patrik for your quick answer.

As we can see in the description [here](https://www.axllent.org/docs/nodejs-service-with-systemd/), when the service is launched, the server is clearly displayed like that:
![image](https://user-images.githubusercontent.com/23366980/140996814-d28837d3-30bf-453a-8cfd-be5e5721fa1c.png)

However, I don't have the same message in my case:
![image](https://user-images.githubusercontent.com/23366980/140996954-0370ec5d-a81f-47b4-854f-22c598d38b67.png)

But I didn't find yet the explanation of this difference.

Any advice will be helpful...

**Comment by Tos26** [comment]
Hello,

It seems that my first analysis was wrong because the service and the server are running after a reboot.
Maybe I tested the right connection before the service was fully started... I don't know.

Thanks for help.
