### ISSUE TITLE
Add option to display/hide square around face tags

### ISSUE THREAD

**Issue by alexthamm** [bpatrik/pigallery2#394]
**Is your feature request related to a problem? Please describe.**
All faces in my pictures are tagged (using digikam). When opening a picture with a tagged face, a square is shown around the face. This is not helpful because I know the people in my pictures. It's rather annoying as I'm interested in the actual pictures and not the location of the faces in the pictures.

**Describe the solution you'd like**
It would be great if we could configure on the settings page whether the square is displayed or not.

**Comment by bpatrik** [comment]
Sounds good to me. 
It should be added here: https://github.com/bpatrik/pigallery2/blob/22954550bfd473d85206d62aca50e47853b20862/src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.html#L58

**Comment by bpatrik** [comment]
We should soon have this

**Comment by bpatrik** [comment]
The latest commit should contain this.
