### ISSUE TITLE
Ability to launch thumbnailgeneration from commandline or similar?

### ISSUE THREAD

**Issue by andreasferm** [bpatrik/pigallery2#4]
Hi Patrik, 

I just installed this on a B+ that has become redundant, and it seems to fit my needs quite well.. There's just one feature that i feel would make it kick-ass, and that would be to be able to traverse all images in image folder, and if there's no thumbnail, generate it.

Let me give some backround info, i decided to make a "backup" solution using the B+ and a 2.5" hdd for use with my dslr when traveling.  At the moment this works well, it copies all the raw files to a new folder, and renames the files based on the shooting-time.  After this i extract the embedded jpeg from the raw files with dcraw (500ms per 24mpixel file, reasonably fast) 

Now these are the files that will be used for pigallery2, but since i will be out traveling there won't be any screen, keyboard or internet, so i wanted to use usb tethering from my android phone, problem is the current capacity on usb... once it connects to the rpi it will start to charge, and when doing 'heavy' I/O such as generating thumbnails, the hdd will get into power issues and disconnect and reconnect as a new device (without being mounted in the 'correct' place).

If i was able to have the thumbnails generated before connecting the phone, i could later use my phone to ensure that all files have been transfered correctly (if i need to wipe a memory card)

Are there something similar that could be done with the current code?

**Comment by bpatrik** [comment]
Hi,

I not sure if the pregeneartoin would solve this issue. Whenever you open a a folder a full directory search might occur (depending on what setting are you using). Plus, if you open up an image, the full image will be loaded. So there will be full directory reading and image reading even after you have the thumbnail ready. 
An addition to that If you set up multiple thumbnail sizes (which is the default), you should generate all the sizes. (You can change that in the setting)

Unfortunately, there isn't any command line way to generate the thumbnails. I have some busy weeks now, so I cannot promise you to implement one.

However, I can offer you 3 "hacks":

1) You can try connecting the phone when its fully charged. If the phone is around 100%, it might use less power, or no power at all for a few minutes. During that time you can make the app to generate the thumbnails.


2) You can try a stronger power supply and better cables. Imho, one with 2.5Amp should work.


3) You can write a little script that calls the API of the page.
 You can do something like this:
`curl https://pigallery2.herokuapp.com/api/gallery/content/`
this gives you back a json that contains the 'main' folder that you can parse. (Of course you should change the `https://pigallery2.herokuapp.com` to you domain. And you might also need to disable authentication during that time in the config)
If you inspect the result json, you will see that there are `directories` and `photos`. Under the `photos` you see all the photos in the current directory.
Here is how you can make the app the generate a thumbnail:
`curl https://pigallery2.herokuapp.com/api/gallery/content/IMG_6220.jpg/thumbnail/200`
where `IMG_6220.jpg` is the (file) name of the photo and `200` is the thumbnail size. (The size should one of the sizes, that are set on the settings page).
If you want to do the same with a subfolder called `mysub`, you can do this:
`curl https://pigallery2.herokuapp.com/api/gallery/content/mysub`
`curl https://pigallery2.herokuapp.com/api/gallery/content/mysub/IMG_6220.jpg/thumbnail/200`

**Comment by andreasferm** [comment]
Hey Patrik, you're correct, the pregeneration didn't solve the issue, once connected with the phone and opening an album , all the disk activity and activity over usb to the phone, plus the charging of the phone made i/o errors and hdd was 'unmounted'.

Regarding the power supply i used a 2.1A one, but i have a 2.5 at home and that is definitely worth a try, but it could be a that the limit is the throughput of the rpi as well. 

The curl approach is definitely doable and i'll look into that. 

I will see if i can get around the issue by connecting the phone to a powered usb hub and then to the pi, unsure if it will work with ptp or not, so i need to check that.

Either way, thanks for the info i should be able to take it from here :)

**Comment by bpatrik** [comment]
Hi,
np. :)
I also had power issues with my RPI B. I could solve it with a powered USB hub. I plugged my HDD to the HUB, as well as the rpi. The the HDD got the power from the hub, not from the RPI. 
The hub had 2.5 A supply. (I think it was a belkin usb hub).
A better cable with lower resistance can also help. Something with [18-20 AWG](https://en.wikipedia.org/wiki/American_wire_gauge)
