### ISSUE TITLE
Mysql settings show error

### ISSUE THREAD

**Issue by frankyifei** [bpatrik/pigallery2#40]
tried to connect to mysql server and returned this error 
`Error: Error while saving database settings: QueryFailedError: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'name' used in key specification without a key length`
Mysql server is working without issue.

**Comment by bpatrik** [comment]
Hi,
Thank you for the report, I'll look into it in the next few days (worst case weeks)

Patrik

**Comment by bpatrik** [comment]
Hi,

The latest [commit ](https://github.com/bpatrik/pigallery2/commit/d92003eeeed3864a82422f62b9fc679580265eaf)solve this issue.
(Its not part of any release yet, you can try it witch docker:nightly or [building from source](https://github.com/bpatrik/pigallery2#111-b-install-from-source))

Best,
Patrik

**Comment by frankyifei** [comment]
Works great now. Using mysql is better than sqlite because I have a collection of more than 10k photos. Thanks.
