### ISSUE TITLE
[QUESTION] How to integrate costum analytics to the app

### ISSUE THREAD

**Issue by esturniolo** [bpatrik/pigallery2#404]
Hi!
Thanks for this simple and great gallery. Does what it says. And very well. 

I'm sharing to the world an album and I would like to know how many people access, from where, etc. 
So an analytics tool it’s the best to do this job. 
But to use any analytics tool I must to add some code to the webpage to track it. 

The million dollar question is, how can I add this code into PiGallery?

I'm using the Docker version and I browsed into the container but I can't anything where to put that piece of code. 

The most common is to put that code inside the `<HEAD>` html tag. 

Thanks!!!

EDIT: I realized that I messed up with the issue title. Feel free to edit it if you can/want. 
I can't edit it. Sorry for that. 
Happy new year!!!!!

**Comment by esturniolo** [comment]
Sorry for reopen the ticket @bpatrik.
First at all thanks to take a look at this.

How can I add the code inside Pigallery to start to use the analytics tool? 
I don't get it.

Thanks!

**Comment by bpatrik** [comment]
I'm not sure how your tool works, but you can add things here that will be added to the head part:

![kép](https://user-images.githubusercontent.com/7512182/150027681-93331dab-cda8-437a-95a6-0582229ccef0.png)

**Comment by esturniolo** [comment]
Ohhhh perfect!!!!
I think that this field should work flawessly.

Thanks again!

**Comment by vutsalsinghal** [comment]
Perfect! 

For anyone who cares, I did a very simple out of the box approach. Instead of adding the following in the "Custom HTML Head" in settings:
```
<script async src="https://umami.exameple.com/script" data-website-id="0618"></script>
```

I added
```
</script><script async src="https://umami.exameple.com/script" data-website-id="0618">
```

Now its working!
