### ISSUE TITLE
Missing Node Module: Chronos breaks latest Dockers

### ISSUE THREAD

**Issue by desertwitch** [bpatrik/pigallery2#406]
internal/modules/cjs/loader.js:905
throw err;
^
Error: Cannot find module '../../../../../node_modules/ngx-bootstrap/chronos'

Is thrown using the latest Docker nightly images (alpine & buster tags).

**Comment by bpatrik** [comment]
that is very odd. that should not be need in the release. That is a dev dependency (needed for building the angular frontend). 
I'll take a look.

**Comment by bpatrik** [comment]
huh, i found the culprit.

**Comment by desertwitch** [comment]
Thanks a lot for the fast response, can confirm it works now (tested debian-buster).
