### ISSUE TITLE
Admin account recreation on restart

### ISSUE THREAD

**Issue by headcrushedindoor** [bpatrik/pigallery2#408]
Hey,

I'm using nightly-alpine. With the last update, PiGallery2 adds admin/admin account which I deleted before.
After re-deleting admin account, warning notification won't go away and it says "To dismiss these notifications, restart the server. ". If I restart it with "docker-compose restart" admin/admin appears again.

**Comment by bpatrik** [comment]
Hi, I'll fix it.

In the meantime, you can set the enforced Users settings to empty array in
the config.json to prevent the recreation of the admin/admin user.



-- Sorry for being brief, sent from my phone.

headcrushedindoor ***@***.***> ezt írta (időpont: 2022. jan.
18., K 9:48):
