### ISSUE TITLE
Negative EXIF ratings cause DB malfunction

### ISSUE THREAD

**Issue by desertwitch** [bpatrik/pigallery2#409]
Negative EXIF ratings such as -1, which are used by few rare clients for marking images for deletion, cause folder indexing queries to fail because _tinyint_ database field does not tolerate negative values, only positive values from 0 to 255. As part of this problem the image with negative EXIF rating and all following images of that folder are not indexed into the DB.

**driverError: Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'metadataRating' at row 1**

- Solution A: Change field type in database from _tinyint_ (1 byte) to _smallint_ (2 byte) to allow negative ratings too and stay true to actual rating of image.
- Solution B: Always override negative ratings to 0 because negative ratings are useless, not staying true to actual rating of image - see my pull request.

**Comment by bpatrik** [comment]
I prefer solution B (min value should be 0) as client only works with value
between 0 and 5

P

-- Sorry for being brief, sent from my phone.

Veronika ***@***.***> ezt írta (időpont: 2022. jan. 18., K
12:53):

**Comment by desertwitch** [comment]
fixed #410
