### ISSUE TITLE
No folder previews on directory search results

### ISSUE THREAD

**Issue by desertwitch** [bpatrik/pigallery2#411]
When searching using "**directory:**", the search returns the found folders, but the previews of these folders are not shown / loaded.

**Comment by bpatrik** [comment]
The issue is mostly likely in the Searchmanager. It is not selecting the
preview media (it requires a left join select on that)

But just a guess, need to check

-- Sorry for being brief, sent from my phone.

Veronika ***@***.***> ezt írta (időpont: 2022. jan. 18., K
13:39):

**Comment by bpatrik** [comment]
So with the validpreview field is selected and can be true, while preview
is not selected so null/undefined.

-- Sorry for being brief, sent from my phone.

Patrik J. Braun ***@***.***> ezt írta (időpont: 2022. jan. 18., K
14:22):

**Comment by desertwitch** [comment]
OK, I think I now understand why it makes sense to select the preview in the SearchManager instead. So that empty but valid previews are not re-checked every single time because of `!dir.preview`, correct? The other functions all load/check the preview from the DB upstream, only in SearchManager it is currently missing.

**Comment by bpatrik** [comment]
Yes that idea would be that with a single SQL query you get the whole directory, including the preview (so less SQL queries are needed).

validPreview is used to show if a preview is valid, while empty (null) preview is still valid. An empty directory cannot have a preview. Lets not run preview update all the time for those directories.

Unfortunately I did not have too much time on this hobby project lately, so last few changes were in a rush.
This: https://github.com/bpatrik/pigallery2/blob/a4a9fe2c988514b7ce129ca6116108eb936b7840/src/backend/model/database/sql/GalleryManager.ts#L223
Mostly decorates subdirectories and makes sure they have a preview. A refactor would be good there and make that decoration on in the middlewares. Also the PreviewManager setandgetPreview should do a check before blindly doing the query, etc., etc.

**Comment by bpatrik** [comment]
In the meantime I pushed a fix to this issue  3982250. I hope did not put too much effort fixing it.

**Comment by desertwitch** [comment]
Thanks a lot for the fix and explanation!
I understand the logic behind it now. 👍
