### ISSUE TITLE
Enable video without transcoding

### ISSUE THREAD

**Issue by jniggemann** [bpatrik/pigallery2#420]
pigallery2 is a very fine software, thank you!
My tmp folder was filling up drive with transcoded videos, but I don't need transcoding because all my vids are pre-processed mp4s.

So: How can I use the video feature but prevent transcoding / only transcode on the fly?

**Comment by martadinata666** [comment]
Set to advanced settings, Remove the job of videos converting, the most bottom part. 
![2022-02-13-114423_1574x844_scrot](https://user-images.githubusercontent.com/2433562/153739098-3d0a8f18-cd88-4958-a8ad-7730da03ff3f.png)

But, i agree to get a toggle button to `enable/disable convert`

**Comment by jniggemann** [comment]
Ahh, thank you!
