### ISSUE TITLE
Integrate a toggle button to enable/disable video convert.

### ISSUE THREAD

**Issue by jniggemann** [bpatrik/pigallery2#421]
**Is your feature request related to a problem? Please describe.**
I was asking how to enable video without transcoding (#420)

**Describe the solution you'd like**
Integrate a toggle button to enable/disable convert.

**Describe alternatives you've considered** (optional)
Document somewhere that to have video without converting, the corresponding job is to be deleted.

**Comment by bpatrik** [comment]
The gallery does not trascode videos without you explicitly clicking on the transcode videos button, so there is no need for a button to disable it. 

If you would like to use jobs, mentioned in #420, but you would like to scik the video transcoding step, just remove that step from the jobs. 

FYI: There is no need the explicitly index, convert or transcode videos (i.e.: use the jobs), the gallery does that on the fly when you navigate to a folder. Its only recommended if you would like to do all at once for the whole gallery

**Comment by jniggemann** [comment]
Thank you explaining!
