### ISSUE TITLE
Floating button to go Up or Back

### ISSUE THREAD

**Issue by kafka0** [bpatrik/pigallery2#427]
**Is your feature request related to a problem? Please describe.**
When I am scrolling trough a folder with a lot of photos (opening some of them) and arrive at the end I need to scroll all the way up in order to go back to the parent folder. The back button on the browser does not work for that, it will open the last opened photo.

**Describe the solution you'd like**
The suggestion would be to have a floating button on the right lower corner that we could press to go straight to the top of the page or maybe back to the parent folder.

**Comment by bpatrik** [comment]
How about hitting the `home` button on the keyboard?

**Comment by kafka0** [comment]
Hello.

Thank you for your reply.
That works on a browser on Windows.
But I am having this "issue" on android. Maybe there is a easy way to do this that I don't know about.

**Comment by bpatrik** [comment]
Yeah on android, a button like this could help. I might add something like this in the future.

**Comment by kafka0** [comment]
Thanks ;-)
