### ISSUE TITLE
Permission / Restricted acces

### ISSUE THREAD

**Issue by ItJustFox** [bpatrik/pigallery2#430]
**Is your feature request related to a problem? Please describe.**
Yes and no, I just ask if it is possible to set restriction for folder or images.

**Describe the solution you'd like**
In the panel admin a way to create grade (like admin user) with special permission. And in admin or another panel, a way to restrict image / video to a certain role. (using like see.restrictedimage.permission)

**Describe alternatives you've considered** (optional)
Just above ! ;p

**Comment by bpatrik** [comment]
No, its not possible at the moment.

I think this is a duplicate of #188

**Comment by ItJustFox** [comment]
Ah, yes duplicate.

Sorry

**Comment by pepa65** [comment]
So all users have access to the same single collection of `images/`??
So the users just differ in the role/authorization they have?

**Comment by bpatrik** [comment]
yes. thats is correct.
