### ISSUE TITLE
UnraidOS - Cannot use official DockerImage 

### ISSUE THREAD

**Issue by ItJustFox** [bpatrik/pigallery2#431]
**Describe the bug**

unable to use the official docker image `bpatrik/pigallery2` under UnraidOS

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/42358087/155170470-0331ac9a-e5f8-41f2-a22d-ad43ed86e06a.png)
![image](https://user-images.githubusercontent.com/42358087/155170414-7c3966d6-aceb-4b66-88a3-d7c2d2a8689f.png)

**Server logs (optional)**

```
Récupération de l'image: bpatrik/pigallery2:latest

TOTAL DONNÉES RÉCUPURÉES: 0 B



Arrêt du conteneur en cours: PiImage
Conteneur arrêté avec succès 'PiImage'



Suppression du conteneur en cours: PiImage
Conteneur supprimé avec succès 'PiImage'



Command:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='PiImage' --net='br0' --ip='192.168.0.94' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e HOST_HOSTNAME="KaliServeur" -e HOST_CONTAINERNAME="PiImage" -e 'TCP_PORT_85'='80' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:80]/' -l net.unraid.docker.icon='https://bpatrik.github.io/pigallery2/assets/icon_inv.png' -v '/mnt/user/appdata/PiGalery2/config':'/app/data/config':'rw' -v '/mnt/user/Image/Imaze/Privée/':'/app/data/images':'ro' -v '/mnt/user/appdata/PiGalery2/tpm':'/app/data/tpm':'rw' -v '/mnt/user/appdata/PiGalery2/db':'/app/data/db':'rw' 'bpatrik/pigallery2'
Unable to find image 'bpatrik/pigallery2:latest' locally
docker: Error response from daemon: manifest for bpatrik/pigallery2:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

Échec de la commande.
```

**Environment (please complete the following information):**
OS : UnraidOS

**Used app version**:
- Automatic Docker with UnraidOS

**Comment by bpatrik** [comment]
Sorry, but I do not know `UnraidOS` (I also do not speak french). 
Maybe you need to add this as an image: ` bpatrik/pigallery2:latest-debian-buster` or at least add `latest-debian-buster` somewhere in the config.

Keeping it open, maybe others can help.

**Comment by ItJustFox** [comment]
Oh, sorry for the french, I like auto-translate it >.<
But I have try set `bpatrik/pigallery2:latest-debian-buster` and now it's work perfectly. 

I too, ask if I can add so your work into the UnraidCommunityApp (where is every docker you can download and use) with sending and saying that you created this docker and not me. That up to you !

**Comment by ItJustFox** [comment]
(Ps²: is you need someone to help translate in french, i can help if nedeed !)

**Comment by bebestmaple** [comment]
I wonder who create this repo to unraid,but it has a mistake 
![image](https://user-images.githubusercontent.com/7425640/156731456-842c5411-2c6c-45ba-8ccf-f16a22214909.png)

the default tmp folder would be 'tmp',not 'tpm'.

**Comment by ItJustFox** [comment]
> 

It's aleadry fixed and have been a while ago, I dont know why you come here for :/
