### ISSUE TITLE
tmp directory being cleanup when migrating to another host

### ISSUE THREAD

**Issue by GWONG3** [bpatrik/pigallery2#441]
Hi all,
Recently installed pigallery2 on my macbook air with over 200K pictures indexed (using OSX docker and docker compose).  I see there are several Gbs of thumbnails created on the tmp folder that I defined in my docker-compose.xml file after spending days of converting photos.  Everything is working fine.  Both my tmp and original pictures are on a NAS shared folder.

In fact I want to host this 200K pictures album on a RPI4B (but used my faster MBA for indexing/converting).  I use the same docker-compise.xml settings (of course I changed the paths based on my RPI's environment).  When I started it up, I can see no pic ; but if I go to perform the photo converting, it says starting to clean up my tmp folder and I do see my tmp folder subdirectories are really being cleanup....

Is this normal?  I dont want to spend another few days to regenerate the thumbnails and I thought the RPI4B can reuse the same thumbnails rather than being "clean up" and regenerate again?

Your advice is greatly apprieciated!

Regards,
GWONG3

**Comment by bpatrik** [comment]
Hi,

It should be possible to use the same tmp folder. I also converted my videos on my laptop.

The issue can be two fold:
 * you run clean-up without indexing your gallery fully (what is not in the db, the app will delete it
 * the gallery file structure have changed. `tmp` uses the same folder structure as your gallery. If the relative path from your gallery route to a photo have changed, it wont fond that image.

**Comment by GWONG3** [comment]
Thank you bpatrik!  I found out I did not index my gallery fully before I moved to the new host and that's why.
