### ISSUE TITLE
[Suggestion ] Create a list of tags to create logical albums

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#45]
I have all of my photos in YYYY/MM folders, but i also use digikam to tag all of the photos into vitual albums.

Is there a way to list all of these tags so that i can navigate through them?  have the folder heirachy, then under that have a heirachy of logical albums / tags?

I would love this, and would make my 50k photos actually navigatable!

thanks :)

**Comment by palitu** [comment]
I think you can go even simpler than complex unions on searches.  Literally just allowing you to list all tags as a minimum, then the next step could be allowing you to list all tags that you want to be able show on the front page as a gallery, without having to search for them.

This will allow your workflow of offline editing via lightroom, then dynamically creating albums in PG.

If i can get my head around this style of programming, i could have a look into extending the front page.

cheers,

**Comment by bpatrik** [comment]
I was actually considering creating a 'dashboard like something' with a keyword cloud.
Is that what you have in mind?

**Comment by palitu** [comment]
that would work in a pinch.  I guess i am after discoverability of different tags.

**Comment by bpatrik** [comment]
Ok, I'll add a feature like that down the road. 
Sorry, bit I can't promise any deadline. 
The current DB scheme doesn't really supports such queries, so I'll need to change that first.

**Comment by palitu** [comment]
ah bugger - was hoping that it would.  Will see how we end up :)

thanks

**Comment by bpatrik** [comment]
I'm organizing my albums the following way. And also the app is the best for this:
```
+ 2016
+ 2017
+ 2018
- 2019
   |--- 2019.01.03 <Event name 1>
   |--- 2019.01.10 <Event name 2>
   |--- 2019.02.03 <Event name 3>
```

If you can convince me that there is a better / equally good way of doing this I might do this feature earlier. 
Or I can be also biased by the community: if more people (min. 4-5) say, this feature is important for them, I'll do it too. :)

**Comment by palitu** [comment]
I am similar, except i have **all** of my photos in my list, the good, the bad, the ugly!

```
+ 2016
+ 2017
+ 2018
- 2019
   |--- 01 Jan
   |--- 02 Feb
   |--- ...
   |--- 12 Dec
```
This becomes a dump for all photos across all of our cameras and phones (wife and I), then we use Digikam to place tag/captions into the images to create logical albums.

So a photo may be in `2017/09 Sep`, but it may have a number of tags:
```
#Kiribati
#Kiribati Work Slideshow
#Eli
#Hospital Butaki
```

This allows me to view all of my photos through the folder structure, but also have the same photo be assigned to a number of albums.

It is a way that we can keep a single set of photos, but have them appear in different albums for different reasons.  In the example above

**Kiribati** our album of photos from our trip to Kiribati
**Kiribati Work Slideshow** the album i used to show colleagues our trip
**Eli** nice photos of our son
**Hospital Butaki** and event in kiribati.

It is a really nice way of having all you photos together, and being flexible enough for multiple people to work on the same set.

Then you have this great web interface that allows you to look through all of your photos, as well as show off your albums.  There is a web album called photato which is really nice, but is unmaintained which i find has an outstanding method for showing off photos, across both folders, dates, tags, people and locations.  You should have a look.  If you like i will spin up an instance for you to have a look through.

cheers,

**Comment by bpatrik** [comment]
Pushed Advanced Search #58. (pls. handle it as beta).
This will allow now to implement virtual folders.

**Comment by bpatrik** [comment]
Added saved search (logical albums) to the app.

It is still in "beta". By default switched off in the config. Enable it directly in the `config.json` at `Client.Album.enable`

**Comment by bpatrik** [comment]
I see there are some comments about keyword / tag cloud. Pls. open a new ticket for that if you would like to still see that feature.

**Comment by cbhushan** [comment]
> Added saved search (logical albums) to the app.
> 
> It is still in "beta". By default switched off in the config. Enable it directly in the `config.json` at `Client.Album.enable`

Just discovered this and it achieves what I was looking for - Timeline on a selected folder :smile: :+1: 

Is there a way to also add sorting/ordering method to saved albums? I was looking for  another feature: **random sampling from gallary** (with or without any additional constrains). The same saved search approach can be used for it. I was looking to get something similar, but not exactly same, as [this feature from photostructure](https://photostructure.com/faq/why-photostructure/#fast-and-fun-browsing-of-samples-). The only missing piece is ability add sorting/ordering method to saved albums.

**Comment by bpatrik** [comment]
Currently you cannot preset an ordering to searches. You can change it once you list the search tho.

I think the random API/link is the closest that you can get to random sampling, but that is only a single photo.

**Comment by bpatrik** [comment]
Closing this as the original FR was implemented.
