### ISSUE TITLE
Add multiple directories (natively) without symlinks etc...

### ISSUE THREAD

**Issue by jimdaway** [bpatrik/pigallery2#451]
I am running PiGallery2 in a docker container. Is it possible to add multiple image directories natively within PG2?

The ability to add multiple image directories natively in PiGallery 2 would be of benefit.

I believe I've seen where it has been suggested that symlinks may be used to "add" additional directories.

**Comment by bpatrik** [comment]
Hi

Symlink does not work within a docker container. What you can do is to
mount multiple folders (volumes) within the docker container.



-- Sorry for being brief, sent from my phone.

jimdaway ***@***.***> ezt írta (időpont: 2022. márc. 8., K
15:59):

**Comment by jimdaway** [comment]
Thank you @bpatrik 
Aside from the original Images folder (/app/data/images/), I tried adding a new Path pointed to "/app/data/images2/" but that didn't work.

When I added a new path using the same container Images path again (/app/data/images/), the container failed to start with execution errors.

What would the internal map-point be for extra folders?

**Comment by martadinata666** [comment]
```
 volumes:
      - "./pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "./pigallery2/images2/app/data/images/images2:ro"
    ports:
```
`/images` is the root for image dir gallery
-- /images
  | xxx.jpg
  | yyy.jpg
  - /images2
    | zzz.jpg
    | aaa.jpg

**Comment by bpatrik** [comment]
If this does not work, I would try:

```
 volumes:
      - "./pigallery2/images1:/app/data/images/aaa:ro" # CHANGE ME, ':ro' mean read-only
      - "./pigallery2/images2:/app/data/images/bbb:ro"
```

Not sure what happens if you map something below a mapped folder.

**Comment by zigmhount** [comment]
> Not sure what happens if you map something below a mapped folder.

@bpatrik [it doesn't work](https://stackoverflow.com/a/38167198) :) I tried earlier this week, and I settled instead with the same as you're suggesting.

**Comment by jimdaway** [comment]
Thank you @bpatrik and @martadinata666 

As I understand, all folders below the mapped folder will be indexed and presented to the browsing user.
To expand on my particular situation, I have this installed on an unRAID server in a docker container.

I am trying to map two (or hopefully more) different image folders in different shares as follows:
Container           unRAID Shares
Images               /mnt/user/Personal/Photos/
Images2             /mnt/user/Professional/Gallery/
Images3             /mnt/user/Pictures/Public/

Note that in the above example, there are multiple image folders below each of the three different shares.
Is there a way to do this with PiGallery2?

Thank you again for you assistance.

**Comment by martadinata666** [comment]
> Thank you @bpatrik and @martadinata666
> 
> As I understand, all folders below the mapped folder will be indexed and presented to the browsing user. To expand on my particular situation, I have this installed on an unRAID server in a docker container.
> 
> I am trying to map two (or hopefully more) different image folders in different shares as follows: Container Mapping...............--->........unRAID Shares /app/data/images/................--->......../mnt/user/Personal/Photos/ /app/data/images2/..............--->......../mnt/user/Professional/Gallery/ /app/data/images3/..............--->......../mnt/user/Pictures/Public/
> 
> Note that in the above example, there are multiple image folders below each of the three different shares. Is there a way to do this with PiGallery2?
> 
> Thank you again for you assistance.

Anything under `/app/data/images`
```
Container Mapping...............--->........unRAID Shares
/app/data/`images`/personal................--->......../mnt/user/Personal/Photos/
/app/data/`images`/Professional..............--->......../mnt/user/Professional/Gallery/
/app/data/`images`/Public..............--->......../mnt/user/Pictures/Public/
```

**Comment by hajo62** [comment]
That's what I have in my `docker-compose.yaml` to have one top folder for each year in the gallery. Maybe it helps
```
    volumes:
     ...
      - /home/hajo/Photos/2021:/app/data/images/2021:ro
      - /home/hajo/Photos/2020:/app/data/images/2020:ro
      - /home/hajo/Photos/2010-2019/2019:/app/data/images/2019:ro
      - /home/hajo/Photos/2010-2019/2018:/app/data/images/2018:ro
     ...
``` 
![grafik](https://user-images.githubusercontent.com/15800980/158153939-2b729d73-5432-486d-b49c-21cc9bc09f15.png)

**Comment by jimdaway** [comment]
Hi @hajo62 . Do you map those different folders under the Photos folder in order to exclude other folders in the Photos folder?
In other words, could you not just map the /home/hajo/Photos/ folder and PiGallery2 would pull from all the folders in Photos?
This is probably very simple and I'm just over-thinking it😞

**Comment by hajo62** [comment]
Could do so... But... 
I have folders for decades - 2010-2019 - and therin 10 subfolders for the years to make easier file system browsing. In the gallery I want to have the folders _flat_.

**Comment by jimdaway** [comment]
Well, @hajo62 , Thank You! It worked for me! Thank you to @bpatrik , @martadinata666 for the guidance as well.

It was a simple matter of dropping preconceived expectations of how it "should" work and adopting @hajo62 's structure example. Wow, for something so simple I certainly did complicate it - for myself!

Thanks again!
