### ISSUE TITLE
Website: Local Filters image is not found

### ISSUE THREAD

**Issue by Tofee** [bpatrik/pigallery2#459]
**Describe the bug**

On the main website, http://bpatrik.github.io/pigallery2/assets/local_filters.jpg is not found in the "Local Filters" section.

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

N/A

**Server logs (optional)**

N/A

**Environment (please complete the following information):**

Firefox 98, Archlinux

**Used app version**:

http://bpatrik.github.io/pigallery2

**Comment by bpatrik** [comment]
Fixed. Thank you!
