### ISSUE TITLE
Any plan to add boolean logic EXCLUDE or NOT function for search?

### ISSUE THREAD

**Issue by 02015678** [bpatrik/pigallery2#465]
It seems that currently there is no operator to exclude certain keyword from search result.

What feature is wanted: Example:
If I want to search anything about Trump but exclude anything that contain Donald.

It should be:
Trump -Donald
Trump and (not Donald)

**Comment by bpatrik** [comment]
Hi,

It should be already possible, just not part of the UI, but the parser should understand it:
![kép](https://user-images.githubusercontent.com/7512182/161060184-afa02062-762f-4d4d-b6e2-bf278678f31d.png)
```
person!:John # negation 
```

**Comment by 02015678** [comment]
Thank you very much.
