### ISSUE TITLE
[Question] What's behavior if image itself is smaller than Preview/Thumbnail size?

### ISSUE THREAD

**Issue by 02015678** [bpatrik/pigallery2#466]
Thank you for the great project. This is not a bug report, but a question.

What is the behavior if the image is smaller than preview size?
1) do nothing (skip preview generation)
2) create hard copy to preview folder
3) create a link in preview folder that points to original folder
4) up-convert the resolution to preview size

What is the behavior if the image is smaller than SOME of thumbnail sizes?
For example, if thumbnail setup is 360;720, and some image size is smaller than 360.
1) do nothing (skip thumbnail generation)
2) create two identical hard copies to thumbnail folder
3) create two links in thumbnail folder that points to original folder
4) up-convert the resolution to two thumbnail sizes

Thank you very much.

**Comment by bpatrik** [comment]
Hi,

If I recall correctly the app will generate the thumbnail either way.

**Comment by 02015678** [comment]
Thanks for the reply.
