### ISSUE TITLE
Image date displayed in incorrect timezone

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#469]
Image date is adjusted to the user's browser timezone.

For example if image was taken at 10:30 and the browser is in UTC+10 then date will display as 20:30. This was previously [raised as question here](https://github.com/bpatrik/pigallery2/discussions/360)

Image datetime metadata does not have timezone information so should be displayed without any time adjustments.

**Comment by Scott1009** [comment]
I also experience this. As suggested above, if I force my system to UTC, then the time in the information panel is correct.  Since the create time is without a timezone - perhaps we should impose one, e.g "11/22/2022 12:34:56Z", and read it back out using getUTCString()?
