### ISSUE TITLE
Directory Listing Fails

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#48]
When listing a folder with a certain movie in it, i get the following error, and it returns to the home page:

It seems there is an error with FFMPEG when looking at a certain video file.

```
pigallery       | 2/4/2019, 11:48:58 AM[WARN] Handled error:
pigallery       | ErrorDTO {
pigallery       |   code: 7,
pigallery       |   message: 'Error during listing the directory',
pigallery       |   details:
pigallery       |    { error:
pigallery       |       'Error: ffprobe exited with code 1\nffprobe version N-45896-g19c3df0cd-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2018 the FFmpeg developers\n  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg\n  libavutil      56. 17.100 / 56. 17.100\n  libavcodec     58. 19.100 / 58. 19.100\n  libavformat    58. 13.100 / 58. 13.100\n  libavdevice    58.  4.100 / 58.  4.100\n  libavfilter     7. 20.100 /  7. 20.100\n  libswscale      5.  2.100 /  5.  2.100\n  libswresample   3.  2.100 /  3.  2.100\n  libpostproc    55.  2.100 / 55.  2.100\n[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5e98380] 
moov atom not found\n/pigallery2-release/demo/images/2017/09 Sep/GOPR0978.MP4: Invalid data found when processing input\n' } }
```

**Comment by bpatrik** [comment]
Hi thanks for the report, I'll look into it.

Is it possible to share some of your errorous media with me? I see that you have several image/video files that the app can't handle.
So I can test it.
A private share would also help a lot (like dropbox), but the best would be if you could send me small files (up to 5-10 KBs) that I can also add to the repo as test cases (probably its not possible with videos, but only with images).

**Comment by palitu** [comment]
i can send them - obviously some will be bigger than others.  You can of course just right the erroneous metadata into images (ie, the space based altitude).

When i get home i will set some up for you.

cheers,

**Comment by bpatrik** [comment]
Is this still an issue?
My guess that the app skips the file now and you should see a warning in the log.
Can you confirm that you can open that folder in the UI and it does not crashes?

**Comment by palitu** [comment]
all my folders are loading, and any erroneous files are just missing a thumbnail.

**Comment by palitu** [comment]
you can close

**Comment by bpatrik** [comment]
Ok, Thank you for helping with the debugging!

Patrik
