### ISSUE TITLE
URL shortener for sharing

### ISSUE THREAD

**Issue by sakhnik** [bpatrik/pigallery2#489]
**Is your feature request related to a problem? Please describe.**
I always need to copy URL into another service to get a shorter link, for instance, bit.ly.

**Describe the solution you'd like**
I'd like to get a short link suitable for sharing with another mobile device.

**Describe alternatives you've considered** (optional)
Otherwise, I'll still have to do that manually again: copy URL, shorten it on another site etc.

**Comment by bpatrik** [comment]
I will consider adding this.
Also i do not think the sharing url is that long. The length of it depends on your domain, which the app cannot control.

**Comment by sakhnik** [comment]
The domain is really simple, just an IP address in my VPN. But the path to the media is sometimes ugly because of how I organize the gallery, not to mention it's mainly in Cyrillic. So when I copy and paste the address into WhatsApp or whatever IM app, it almost never recognises it as a URL.
Anyway, much appreciated!

**Comment by bpatrik** [comment]
If you hit the share button, you should have a link like `https://<your domain>/share/a8s31134` (given that you protect your gallery with a password, otherwise sharing is not supported).

If you just copy the url then indeed it can be a bit long.

**Comment by sakhnik** [comment]
Interesting, I don't see the share button. It's just download, info, full screen, close. I'm running version 1.9.3. Is it something new or am I missing it?

**Comment by bpatrik** [comment]
You need to enable sharing in the config. It's a pretty old feature.

Again it only available if you protect your gallery with a password

-- Sorry for being brief, sent from my phone.

**Comment by sakhnik** [comment]
I see. So having the ability to share individual files would be just what I need.

**Comment by bpatrik** [comment]
Someone just opened a Issue for that #497

**Comment by bpatrik** [comment]
lets continue it on https://github.com/bpatrik/pigallery2/issues/497

**Comment by kagahd** [comment]
> Again it only available if you protect your gallery with a password

It seems that the current version (1.9.5) allows to share albums **without** passwords, even though the option `
Enables password protected sharing links` is **enabled**. Is this on purpose or a newly introduced bug?
See also issue #607

**Comment by bpatrik** [comment]
Hi,
Accidental sharing creation is indeed sounds to be a bug.

I think the app should print if there is any active sharing available for
the folder in view.

Once I get some more time to work on this app, I'll look into it.

Also to the app's defense the sharing key is only known within the app and
those who you share with.
I don't see how is it significantly stronger if you protect the link with a
password and the  Send the password over with the link itself.

-- Sorry for being brief, sent from my phone.

**Comment by kagahd** [comment]
@bpatrik thanks for you quick reply. Please let's continue in #607 because this issue is already closed whereas #607 addresses the bug directly.
