### ISSUE TITLE
DB error at evry indexing

### ISSUE THREAD

**Issue by Railline** [bpatrik/pigallery2#501]
**Describe the bug**

when i launch a index task i get this error in my DB

**Photo/video (optional) that causes the bug**

2022-06-18 16:17:25 15851 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').

2022-06-18 16:17:25 15851 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/57727650/174442643-4a949361-b351-485e-bcb1-248696f225ea.png)

**Server logs (optional)**

In case of a server side error, provide logs:
* Set env variable `NODE_ENV=debug` to log everything.
* To get logs from docker: `docker ps -a` to list containers, `docker logs <container ID>` to get logs.

**Environment (please complete the following information):**
 - OS: [Unraid]
 - Browser [Chrome]

**Used app version**:
- docker-nightly V

**Comment by martadinata666** [comment]
Is it 10.8? https://github.com/MariaDB/mariadb-docker/issues/438

**Comment by grooverdan** [comment]
Note this is excessively noisy [upstream bug MDEV-28866](https://jira.mariadb.org/browse/MDEV-28866), but the upgrade did actually succeed at the end of this.

**Comment by grooverdan** [comment]
The fix for [MDEV-28866](https://jira.mariadb.org/browse/MDEV-28866) has been committed and the next 10.8.4 release will not contain the same invalid error messages in its upgrade.

**Comment by bpatrik** [comment]
If I understand correctly, this is resolved. Closing now. Feel free to reopen if you think otherwise. 

Also thank you [martadinata666](https://github.com/martadinata666) and [grooverdan](https://github.com/grooverdan) for the help.
