### ISSUE TITLE
Face tags in some vertical photos are misplaced

### ISSUE THREAD

**Issue by wonx** [bpatrik/pigallery2#515]
**Describe the bug**

I have noticed that in many cases, pictures have their face regions mispositioned on pigallery2. It looks like the rotation is not applied correctly for the coordinates of the face rectangles. For instance, most (all?) of the vertical pictures I take with my mobile phone. I use Digikam to do my face recognition, and I remember that some time ago it had the same problem (see https://bugs.kde.org/show_bug.cgi?id=372340 and https://bugs.kde.org/show_bug.cgi?id=395243), that was already fixed.

**Photo/video (optional) that causes the bug**

(I can provide several examples, but I prefer not to show pictures of people I know here. I would have no problem sharing them in private, though.)

**Screenshots (optional)**
![Screenshot_20220705_112539](https://user-images.githubusercontent.com/2736639/177364263-55275096-3355-4c0a-9188-ed6cfb499c6d.png)

**Environment (please complete the following information):**
 - OS: OpenMediaVault 5.6 (based on Debian Buster)
 - Browser: Google Chrome

**Used app version**:
- Docker latest, created on 2022-07-02

**Comment by rhatguy** [comment]
I had this same issue recently.  I found that if I went into digikam and rotated the picture one way, then back to the original rotation then re-indexed pigallery2 it fixed the issue.  I assume digikam is rewriting some tag into a format that pigallery2 handles better, but I didn't take the time to figure out what was changing.  If you do the same, maybe save a before and after version of the picture to be able to see the differences in the metadata.

**Comment by rhatguy** [comment]
Caught an actual example of this recently.  I have a picture that was taken on a Samsung S20FE 5G phone.  I tagged the face in the photo with digikam and then imported into pigallery2.  I noticed the face on pigallery2 wasn't lined up with what was showing in digikam.  I went back to digikam and manually rotated the picture 90 degrees one way then back to the original orientation and then saved a copy of the updated picture as the "new" tag shown below.  I grabbed the metadata from both pictures with exiftool and put them in text files to compare.  I found there were quite a few metadata changes.  Found a couple of interesting differences in before the roatation and after detailed below.  Wondering if this is a digikam problem (maybe it should have updated these items before it saved the face originally) or if pigallery2 should be able to handle this either way.

/tmp # egrep Orientation old.txt
Orientation                     : Rotate 90 CW
/tmp # egrep Orientation new.txt
Orientation                     : Horizontal (normal)

/tmp # egrep "Exif Image" old.txt
Exif Image Width                : 4000
Exif Image Height               : 3000
/tmp # egrep "Exif Image" new.txt
Exif Image Width                : 3000
Exif Image Height               : 4000

/tmp # egrep -i region old.txt
Region Applied To Dimensions W  : 4000
Region Applied To Dimensions H  : 3000
Region Applied To Dimensions Unit: pixel
Region Name                     : persons_name
Region Type                     : Face
Region Area X                   : 0.4135
Region Area Y                   : 0.471167
Region Area W                   : 0.096
Region Area H                   : 0.0963333
Region Area Unit                : normalized
Region Person Display Name      : persons_name
Region Rectangle                : 0.3655, 0.423, 0.096, 0.0963333
/tmp # egrep -i region new.txt
Region Applied To Dimensions W  : 4000
Region Applied To Dimensions H  : 3000
Region Applied To Dimensions Unit: pixel
Region Name                     : persons_name
Region Type                     : Face
Region Area X                   : 0.528833
Region Area Y                   : 0.4135
Region Area W                   : 0.0963333
Region Area H                   : 0.096
Region Area Unit                : normalized
Region Person Display Name      : persons_name
Region Rectangle                : 0.480667, 0.3655, 0.0963333, 0.096

**Comment by rhatguy** [comment]
I noticed a similar thing.  I've found if you rotate it one direction in DK
them rotate it back it seems to fix things.  I think we need to capture
examples of a file before and after showing the difference in metadata to
figure out what's going on.

**Comment by bpatrik** [comment]
The latest push should fix it.

Basically the issue that some (mostly older) tool adds orientation exif tag to the photo instead of actually rotating it. The app did not pick it up properly for faces.
