### ISSUE TITLE
Date in the metadata not detected in some pictures

### ISSUE THREAD

**Issue by wonx** [bpatrik/pigallery2#517]
**Describe the bug**

It only happens in a small minority of pictures, but sometimes the EXIF date is not detected, and as a result the picture is not sorted chronologically in the gallery. The rest of the metadata (camera model, lens, tags, people) seems to be detected correctly. I estimate that around 0.35% of the pictures of my gallery are affected. So, not a big deal, but because of this, they are shown first instead of being in their chronological place.

Sometimes it's a particular picture within an album that's missing the date, when all the rest have it. I have tried checking the metadata in Digikam, and they all seem to be correct. I even manually edited the data, save it again, and run the indexing again, but it doesn't seem to be detected.

I have attached all the metadata of a sample picture that I extracted using exiftool. 

**Photo/video (optional) that causes the bug**

(I can provide example pictures in private)

**Screenshots (optional)**

![Screenshot_20220705_120558](https://user-images.githubusercontent.com/2736639/177370713-3d88bdcc-323d-4a26-ac03-ad66e66b863f.png)

Metadata of the picture: [IMG_9502.JPG.txt](https://github.com/bpatrik/pigallery2/files/9047892/IMG_9502.JPG.txt)

**Environment (please complete the following information):**
 - OS: OpenMediaVault (based on Debian Buster)
 - Browser: Google Chrome

**Used app version**:
- Docker:latest (2022-07-02)

**Comment by bpatrik** [comment]
Do you have a photo that you can share with me and I can test on?

**Comment by wonx** [comment]
That's weird, I went to check the exact same picture I mentioned in the last post, but now the date appears. Is it possible that the first scan did not pickup all the metadata the first time, and that was corrected in subsequent scans?

If I see the problem again I'll report back.
