### ISSUE TITLE
[Suggestion] download photos

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#52]
This is a feature request to download multiple photos in a zip file.

When I share a link with family or friends they want to download the collection of photos easily. This could be an option to download all photos in current folder or an interface to select photos in the thumbnail view and then download only the selected photos.

Thankyou for this app, I'm really impressed with the searching tools.

**Comment by bpatrik** [comment]
Hi,

Thanks for the suggestion. 
I can add the full folder download to the app. Selecting a photo is currently not possible and not super straightforward to implement, I might not do that. Also it will be probably a slow feature if you have like 50+ or even 100+.  I can imagen on weak device (like a raspberry) it can be even like 5-10mins.
Unfortunately I cannot promise any deadline. (Most likely will take up several months.)

Patrik

**Comment by ALutz273** [comment]
This function (download all images as zip) is unfortunately also missing for me and would be very cool
How can you be supported? Unfortunately, I am not a good programmer.

**Comment by mcdamo** [comment]
#278 adds ability to download directory's media in a zip.

**Comment by bpatrik** [comment]
made it support search results too in #1017
