### ISSUE TITLE
Guest link can download unshared photos

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#53]
If a guest is given access via a shared link then it appears to be possible to download photos that are not within the shared folder.

**Comment by mcdamo** [comment]
There is also a more series vulnerability when your gallery allows public guest access, let me know if you would like me to disclose further details here or via a private channel.

**Comment by bpatrik** [comment]
Hi,
Thank you for reporting this. I'm somewhat aware of the first one, but I do not have any information on the second and would like to hear more. 
Maybe in private would be better?
email: bra.patrik `AT` gmail.com

**Comment by mcdamo** [comment]
Responded via email.

**Comment by bpatrik** [comment]
Hi
Now this error should be fix. (also the one that you have reported via email)

Thanks for the report again!
best,
Patrik

**Comment by mcdamo** [comment]
It appears both issues are fixed. Thanks!
