### ISSUE TITLE
Photo file dates incorrect during summer time (DST)

### ISSUE THREAD

**Issue by HuwSy** [bpatrik/pigallery2#530]
**Describe the bug**

The imported date/times within the db and info tab are an hour out for photos taken during daylight savings time. This occurs in latest released version, not checked in latest code base.

An example file on my setup, although is occuring in files from Camera, iOS and Android

mediainfo -f DSC_1086.JPG
...
File last modification date              : UTC 2022-08-26 16:30:06
File last modification date (local)      : 2022-08-26 17:30:06
...

ls -l DSC_1086.JPG
-rw-rw-r-- 1 . . 9887811 Aug 26 17:30 DSC_1086.JPG

exiftool output
File Modification Date/Time     : 2022:08:26 17:30:06+01:00
Modify Date                     : 2022:08:26 17:30:06
Date/Time Original              : 2022:08:26 17:30:06
Create Date                     : 2022:08:26 17:30:06
Create Date                     : 2022:08:26 17:30:06.575649+01:00
Date/Time Original              : 2022:08:26 17:30:06.575649+01:00
Modify Date                     : 2022:08:26 17:30:06.575649+01:00

Date within gallery 

August 26 Friday, 18:30:06

Date expected within gallery based on the time it was actually taken 

local time
August 26 Friday, 17:30:06

or utc time
August 26 Friday, 16:30:06

Ideally using the local time as the videos import using local time but if the videos also got moved to UTC then the latter would be suitable as my order by date/time would still be visually correct.

**Photo/video (optional) that causes the bug**
Only noticed impacting photos, videos are getting dates correctly presumably via ffmpeg/ffprobe not mediainfo

**Environment**
Raspberry Pi 4 64bit Raspberry Pi OS

**App version**
1.9.3

**Comment by bpatrik** [comment]
related to #360

**Comment by bpatrik** [comment]
Base on https://github.com/bpatrik/pigallery2/discussions/360#discussioncomment-3513484 this is resolved. Closing this. Feel free to reopen if you think otherwise.
