### ISSUE TITLE
Exposure Value in Info-Panel will Overrun rest of Panel

### ISSUE THREAD

**Issue by Sean-T-Moore** [bpatrik/pigallery2#535]
**Exposure Value in Info-Panel will overrun rest of Panel**

The code currently takes the reciprocal of the exif exposure value to display as a 1/x fraction. But there is no attempt to constrain the number of decimal places shown, so the value can overrun the focal length value that is next in the panel.

For example, if the exposure value is: 0.002824858757062147
Then the MetadataLoader will store this as:  0.0028 and the panel display code will show this as 1/x like so:
1/357.14285714285717s

![exposure-value-format-problem](https://user-images.githubusercontent.com/6337432/188034270-d345e0fc-446e-4e2f-b68d-f04dc09c9c92.png)

exiftool and other exif viewers will display this as 1/354. 

I have created a branch to fix the precision of the exposure value and to display the fraction without the offending extraneous decimal digits causing the display overrun.

I'm ready to submit a PR if you would like to incorporate this fix.

**Comment by bpatrik** [comment]
To my understanding this is fixed. Closing this. Feel free to reopen if you think otherwise.
Also tanks for flagging it :)
