### ISSUE TITLE
Save Album sort order

### ISSUE THREAD

**Issue by wonx** [bpatrik/pigallery2#539]
**Is your feature request related to a problem? Please describe.**
I think it could be useful to be able to save the Album sort order, so pictures could be sorted by date or name depending on our choice. For instance, I have a folder which is synced with my phone, so I'd like that particular folder to show the newest pictures first, while other albums are better showing the older pictures at the top.

**Describe the solution you'd like**
When creating a new album (or editing an existing one), add a field for "Sort order".

**Comment by bpatrik** [comment]
I'm confused. Would you like to save album or folder sorting? (albums are basically saved search querries)

At the moment the app remembers the last order used for a given folder. And you can also set up default sorting order for search querries.

**Comment by wonx** [comment]
Hi. I have checked, but if I change the sort order in a given folder and refresh the browser, that sort order is lost. 

I would like that, if I create an album (saved query) and I change the sort order for that album, this sort order is maintained between sessions.

**Comment by bpatrik** [comment]
The latest commit should fix this.
