### ISSUE TITLE
Duplicate users named admin

### ISSUE THREAD

**Issue by civita** [bpatrik/pigallery2#54]
Hi all,

Since I wanted to change the default password of admin and found nowhere to approach, I created another user named `admin` with different password. However, it seems that two users named `admin` are able to coexist, and either of them cannot be deleted. I haven't tested whether other users with same name will coexist or not. Please help me to figure this out.

![screen shot 2019-02-22 at 9 48 31 pm](https://user-images.githubusercontent.com/14911217/53246453-b39aec80-36eb-11e9-85d6-08596aada499.png)

Thank you!

**Comment by bpatrik** [comment]
Hi,
Thank you for the report. 
I've made a fix. Now you can not create user with the same name. (I'll add the password changing ability in the future too).
To make the fix available you need the get the latest version (like: nightly docker) off the app and reset the db (like: delete the sqlite.db file)

**Comment by bpatrik** [comment]
I consider this to be solved, so I close the issue.
