### ISSUE TITLE
not compatible with nodejs 19......

### ISSUE THREAD

**Issue by dream7180** [bpatrik/pigallery2#547]
After system update (archlinux), unable to run anymore. Could you please update it accordingly.

**Comment by bpatrik** [comment]
There is no direct support on my side to direct run for the app at the
moment.
I recommend using the dockerized version.

-- Sorry for being brief, sent from my phone.

**Comment by bpatrik** [comment]
only node v16 is supported with the app. There is no plan at the moment to support v19. 
See package.json for limitation
