### ISSUE TITLE
Ability to change "Images" breadcrumb element to something else.

### ISSUE THREAD

**Issue by greenerk** [bpatrik/pigallery2#554]
With the ability to display videos as well as photos, having "Images" as the base folder (and breadcrumb root) feels a little dated.  If this could be set to something else within the config/settings that would make for a great option.

Even if it was set to "Home" by default it would look better.

![image](https://user-images.githubusercontent.com/56622533/201981787-9ac2e977-8ec8-499a-a540-11b7c2d11d40.png)

![image](https://user-images.githubusercontent.com/56622533/201981958-684a446d-a791-4148-b9aa-4f67100f07f2.png)

![image](https://user-images.githubusercontent.com/56622533/201982055-7e0399e0-e167-4204-80a3-0f1b93deef5d.png)

![image](https://user-images.githubusercontent.com/56622533/201982645-621fa8c7-a9ef-4f6d-a851-434202dcadf7.png)

**Comment by andiohn** [comment]
I agree

**Comment by bpatrik** [comment]
SG. Its more complex to make it configurable, as it needs to be localized, but I changed to Home

**Comment by greenerk** [comment]
Nice.  Thank you.
