### ISSUE TITLE
Hide overlay with face tag

### ISSUE THREAD

**Issue by b-a0** [bpatrik/pigallery2#563]
To start of: I think this is a wonderful application, and I'm really happy that it doesn't try to do many things OK-ish, but one thing well. However, I have a question, for which I could not find a solution in the manual and previous github issues.

**Is your feature request related to a problem? Please describe.**

Whenever I click on a photo that has tagged faces, square overlays are shown over the faces. I rarely need to see those, as I often know the names of the people in the photo by heart. In my opinion the square overlays + the face name obstruct the photo too much and reduce my viewing experience.

**Describe the solution you'd like**

A setting that toggles the viewing of the square overlays for a user.

**Describe alternatives you've considered** (optional)

I've looked through the [Manual](https://github.com/bpatrik/pigallery2/blob/master/MANPAGE.md) and checked the previous github issues that mentioned the word "face".

**Comment by bpatrik** [comment]
duplicate of #394

**Comment by b-a0** [comment]
Sorry, didn't find that one. I'll close mine in favour of the existing issue.
