### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by b-a0** [bpatrik/pigallery2#565]
**Describe the bug**

The demo at https://pigallery2.herokuapp.com/ seems to be down, when visiting the URL I get the following error:

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command `heroku logs --tail`

A similar issue occurred in #522.

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/25707742/205442067-3c250fbc-7653-4f2f-9c64-1b97520df3dc.png)

**Server logs (optional)**

N/A

**Environment (please complete the following information):**
 - Browser Firefox 107.0.1 (64-bit) on macOS Monterey 12.6.1

**Used app version**:
N/A

**Comment by bpatrik** [comment]
Herkou moved to a payed tied and I did not have the time yet to find an alternative.
