### ISSUE TITLE
new release after 1.9.3?

### ISSUE THREAD

**Issue by rhatguy** [bpatrik/pigallery2#568]
Is a new release planned anytime soon or is it expected for users to run on the nightly's?  Just curious what the recommended deployment approach is today.  Thanks!

**Comment by bpatrik** [comment]
I do not have a fix date yet. I might do a release before the end of this year but no promises. I might only have time for that during spring.

Feel free to use nightly in the meantime. Its mostly stable. I'm using the same

**Comment by bpatrik** [comment]
I'm planning a new release soon. see #576. Lets continue the conversation there.
