### ISSUE TITLE
[HELP WANTED] with translation and bug report for release v1.9.5

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#576]
## Translation

I really happy about all the translations that this project is translated to. :)
Unfortunately I do not speak all the languages, also keeping all the translation always up-to-date would significantly slow down the feature development. (And I already have way less time for this project than a few years ago). With the latest config refactor #569, unfortunately lot of translations got obsolete and many more new text got added to the app.

Therefore, I usually just keep adding features and rely on other contributors on translations.
If you would like to contribute to the project, take a look at the translations in the [src/frontend/translate](https://github.com/bpatrik/pigallery2/tree/master/src/frontend/translate) folder and if a translation (value in the <target> tags) does not make sense, update it and send a PR.

You can also a new language, here is the how to: https://github.com/bpatrik/pigallery2#2-translate-the-page-to-your-own-language

P.S.: I also welcome if you only translate a few lines, not the whole file. Every improvement is welcome.

## Bug report

Please report if you see any *bug on the latest nightly version*.  Preferably in a separate issue with instructions on how to reproduce and logs. Use `NODE_ENV=debug` in your docker-compose file to enforce debug logging.
Only bug reports please. I'm not adding new features to 1.9.5 anymore.

Known issues (will be fixed):
 * scroll bar does not appear sometimes  (mostly after searching)
 * slideshow starts too fast even if speed is slow
 * slideshow stops working if the machine goes to sleep and wakes up
 * If password is enabled for sharing, UI bugs if no password is given

----------------------------------------------------
If I get the time I will release v1.9.5 during next week. If I did not get there, feel free to use nightly until the release. They will be technically the same I just did not get the time to hit the release button.

**Comment by bpatrik** [comment]
Added some more missing texts to the translation file.

**Comment by mrtnbr** [comment]
> Added some more missing texts to the translation file.

Can you merge back in my new translation to Dutch? I forked yesterday. https://github.com/bpatrik/pigallery2/compare/master...mrtnbr:pigallery2:master

**Comment by bpatrik** [comment]
if you create a PR it should work.

**Comment by mrtnbr** [comment]
Great. If all goes well I should be done today. It might need a second pass by me or someone else to after that but it will be very usable.

**Comment by bpatrik** [comment]
Thank you all for the contribution. I hit that release button for 1.9.5
