### ISSUE TITLE
Enable/Disable toggle buttons break when translating to longer words

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#577]
**Describe the bug**

I am working on a Dutch translation, requiring me to replace the words Enable and Disable to Ingeschakeld en Uitgeschakeld (or Inschakelen and Uitschakelen, still contemplating what is best). 

These words however are too long and the button now looks wrong :)

![Screenshot from 2023-01-08 12-45-09](https://user-images.githubusercontent.com/4752390/211194444-4cb12b32-d6c1-468e-bb77-d2040182e86b.png)

**Comment by bpatrik** [comment]
Mode some fix. 

Also I don't worry much about the settings page translation. Usually admins understand english (otherwise they wont be able to read the install instruction on this repo).
