### ISSUE TITLE
Some text cannot be translated

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#579]
Some text cannot be translated, mostly in the Search dialogues. 

![Screenshot from 2023-01-08 14-38-42](https://user-images.githubusercontent.com/4752390/211202801-7603bc36-7ef0-4ba4-bc51-ffa6f919b80b.png)

![Screenshot from 2023-01-08 14-39-23](https://user-images.githubusercontent.com/4752390/211202816-823e5feb-4fda-44e4-a77a-69d38e54acda.png)

**Comment by bpatrik** [comment]
[ce8c40a](https://github.com/bpatrik/pigallery2/commit/ce8c40a08f12a32352cca3719cee7d05a69a3939) fixes this.

**Comment by mrtnbr** [comment]
I cannot find the entry to change Album Name and the greyed 'Search' in the search box when opening the 'popup' to search and to add an album.

**Comment by bpatrik** [comment]
Is it still the case?

I can see them: 
![kép](https://user-images.githubusercontent.com/7512182/211646556-7eb71566-c137-4e53-98e6-12c84abd61e4.png)

https://github.com/bpatrik/pigallery2/blob/fb9f8bd38ea577789e17b7d91ef57d8eb5ba5879/src/frontend/translate/messages.nl.xlf#L2986-L2992

I will add the album name

**Comment by mrtnbr** [comment]
I will check

**Comment by mrtnbr** [comment]
Where does the 'Save as album' text appear? Can't find it :D

The "Search" text will be the only (front-end) text that can not be translated then I think.

**Comment by bpatrik** [comment]
When you hit save in the search: 
![kép](https://user-images.githubusercontent.com/7512182/211673135-c474524f-0558-4221-a43c-ef0f5eb2373f.png)

**Comment by bpatrik** [comment]
Hopefully [e6bd8ac](https://github.com/bpatrik/pigallery2/commit/e6bd8ac555e34386b9fab088bb41dd7cee4c5673) gets the last Search text :)

**Comment by mrtnbr** [comment]
Yes, think you've got them all now :)
