### ISSUE TITLE
[Feature]  Advanced search

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#58]
PiGallery should support search queries like:
  *  `Landscape photos of John with Katie within 10km of New York between 02/04/2018 and 05/08/2019`
  *  `Two persons out of John, Katie, Bob and Alice`
  *  etc..

**Comment by mcdamo** [comment]
Simple keyword searches with implied 'and' would be good:
 * `John`, `New York`

Add other operators such as 'not':
 * `John`, `New York`, `!Katie`

**Comment by bpatrik** [comment]
Implemented Advanced Search as **Beta**. 
Did a lot of tests, and took me longer than expected to roll it out. Pls report if you see any issue with it.

**Comment by bpatrik** [comment]
There is still place to further improve Advanced Search (mostly on the UI side), but it is feature ready.
