### ISSUE TITLE
"Allow parallel run" button in configuration too small and unclear mouseover text

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#582]
There seems to be a difference in the display of the Indexed Only button when using a translation. Also, button is to small for the text (also in English). The mouseover text is a bit nonsensical/meaningless

.
![Screenshot from 2023-01-09 13-25-32](https://user-images.githubusercontent.com/4752390/211311954-c75aa235-efdc-4c3e-b236-97c1f74bbd04.png)

![Screenshot from 2023-01-09 13-47-56](https://user-images.githubusercontent.com/4752390/211311976-1fc044b6-4729-4113-8447-bd465907a22e.png)

**Comment by bpatrik** [comment]
Alright I will just remove that button now. I wanted to do it for a long time as it is not maintained anymore.
