### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#587]
Tracking bug for UI improvements efforts.

I plan (no promises):
 * dark theme
    * this would involve adding themeing support
 * better mobile/tablet support (more responsive design)
 * back navigation should go up a folder not back to opening the lightbox
 * some better look (no idea yet)
 * replacing icon sets
 * maybe maybe: new icon #690

**Comment by kparuchuri** [comment]
Just wanted to add on the mobile friendliness, I have built a flutter based web app to browse my pigallery2 photos at [foto-gallery](https://github.com/kparuchuri/foto-gallery.)  This is a very simple interface, no support for advanced features that pigallery2 provides, and is NOT a replacement for pigallery2, but an easy way to browse it on my phone/tablet/browser.

I've created this as a personal home project and a docker instance is available to test it out.

I LOVE pigallery2 and think this is one of the best apps for my usecase to browse home photo collection.

**Comment by bpatrik** [comment]
Thank you @kparuchuri for your kind words!

Great that you created a mobile app. Unfortunately I had to decide that I cannot invest into a mobile app myself as I simple have no time for keeping this app alive plus creating an extra frontend (mobile all).

Unfortunately pigalley2's api is not well documented and I change it from time to time without backwards compatibility. I would like to keep this approach for a while for development velocity.

**Comment by edrikk** [comment]
Really great work on the mobile UI side, thank you!

if I can make a suggestion/request:  after scrolling down for a period, once one scrolls up again the menu appears (which is perfect).  Can a translucent hovering button be added in the lower right so as to allow for jumping back to the top?

**Comment by APraxx** [comment]
https://github.com/bpatrik/pigallery2/blob/2aea6f4456ffa35f6eb42800744efe2018aa01e8/src/frontend/app/ui/gallery/directories/directory/directory.gallery.component.css#L6

What do you think about removing/reducing these borders?

Imo by removing it looks less dense and a bit more "modern"

**Comment by bpatrik** [comment]
> https://github.com/bpatrik/pigallery2/blob/2aea6f4456ffa35f6eb42800744efe2018aa01e8/src/frontend/app/ui/gallery/directories/directory/directory.gallery.component.css#L6
> 
> What do you think about removing/reducing these borders?
> 
> Imo by removing it looks less dense and a bit more "modern"

It indeed looks better. I also rounded them as I started using round style everywhere in the app.

**Comment by bpatrik** [comment]
> Hi, would it be possible to force an orientation in the app is in pwa mode (when the app is 'installed' on the phone)? It annoys me when I'm lying on my bed trying to view the photos in portrait mode, but it keeps changing to landscape because the phone is sideways to the ground.
> 
> I've tried disabling my phone's orientation sensor and adding Permissions-Policy headers, but it does not work.
> 
> Specifically, this line, where it uses the phone's orientation to change to landscape or portrait mode.
> https://github.com/bpatrik/pigallery2/blob/fc35128e2cf87f47092f92b0ecb4ab02b0b33511/src/backend/routes/PublicRouter.ts#L126

Let's talk about it in #681

**Comment by bpatrik** [comment]
> Really great work on the mobile UI side, thank you!
> 
> if I can make a suggestion/request: after scrolling down for a period, once one scrolls up again the menu appears (which is perfect). Can a translucent hovering button be added in the lower right so as to allow for jumping back to the top?

@edrikk Its a duplicate requests of #427 and #615. Latest commit should support this: https://github.com/bpatrik/pigallery2/commit/b7529b13e10f283ecf0b26d3c6aee7d12a936a3b

**Comment by marcusfey** [comment]
I love pigallery2 and started rolling it out to my family members on RPI and other hardware. Thanks for the fantastic work!

Usually my directories contain several thousand images. The scroll up button does certainly work once one scrolled down a lot.

Would it be possible to have an additional _hovering_ navbar on the top from which one could easily go back one level (or several) in the directory tree?

Really just for going back not necessarily a drop down for accessing the sibling/"cousin" directories in the respective (grand-)parent directories.

**Comment by bpatrik** [comment]
> I love pigallery2 and started rolling it out to my family members on RPI and other hardware. Thanks for the fantastic work!
> 
> Usually my directories contain several thousand images. The scroll up button does certainly work once one scrolled down a lot.
> 
> Would it be possible to have an additional _hovering_ navbar on the top from which one could easily go back one level (or several) in the directory tree?
> 
> Really just for going back not necessarily a drop down for accessing the sibling/"cousin" directories in the respective (grand-)parent directories.

I'm sorry but I don't want to add any more buttons to the screen. Max I'm willing to do is to fix the current bar to be always visible.

You can just alt+up to go one directory up.
