### ISSUE TITLE
WebP format videos do not display a thumbnail

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bpatrik/pigallery2#59]
I have some .webp files and they are not displaying thumbnails. Playing them works normally.

![annotation](https://user-images.githubusercontent.com/38865330/53373414-fe4e7b80-391a-11e9-8db9-8c4f12135c19.jpg)

Using the Sharp library for thumbnail generation.

Browser-
Windows 10 1809
Chrome 72 and Firefox 66(beta)

Server-
Host OS is Debian 9
Docker version 1.5.6-stretch

Edit- GitHub does not support webp files so I cannot attach one, but here is a link to one that I have-
https://media.giphy.com/media/l4EoMWIMDVG156l6U/giphy.gif

**Comment by bpatrik** [comment]
Hi,

I did a quick check. 
It seems to be some problem with `sharp` itself. 
Rendering the thumbnail with sharp says: `Error: webp2vips: unable to read pixels`.
That leads to a libvips issue: https://github.com/libvips/libvips/issues/823.
I've opened an issue at sharp: https://github.com/lovell/sharp/issues/1592
Hopefully we get a quick answer. 

Best,
Patrik

**Comment by bpatrik** [comment]
Update: 
According to [sharp](https://github.com/lovell/sharp/issues/1592#issuecomment-467434727) this issue will be solved in the forthcoming libvips 8.8. We will have to wait until then.

**Comment by TheCakeIsNaOH** [comment]
Ah well, at least a fix is in the pipe.

Thank you for your quick diagnosis, and also thank you for creating this awsome project.

**Comment by bpatrik** [comment]
Your welcome :)
