### ISSUE TITLE
Login to a password protected shared does not work

### ISSUE THREAD

**Issue by kim82** [bpatrik/pigallery2#591]
Logging in to a shared folder with a password does not work. It won't open the album/folder after the login

To reproduce the error:
- Share a folder with a password
- Open the shared-url in a new browser (or in incognito)
- Enter the password, and click the login-button

Nothing happens. But if you refresh the screen (F5) it will let you in.

Bug exists in the docker version 1.9.4 in chrome/safari on ios

**Comment by bpatrik** [comment]
https://github.com/bpatrik/pigallery2/commit/66d663b8bc5a5ee228e06d3054ebc181dbded30e should fit it. I charrypicked it back to v1.9.5
