### ISSUE TITLE
Hardware Transcoding

### ISSUE THREAD

**Issue by headcrushedindoor** [bpatrik/pigallery2#592]
Hey, 

I'm trying to enable hw transcoding (vaapi) for video converting. 
Tried to add -hwaccel vaapi; -hwaccel_output_format vaapi; -vaapi_device /dev/dri/renderD128 to custom options and h264_vaapi to codec but log tells me;   

[FFmpeg] Error: ffmpeg exited with code 1: Option hwaccel (use HW accelerated decoding) cannot be applied to output url -hwaccel_output_format vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to. 

So is it possible to send custom options before "-i" of ffmpeg?

**Comment by bpatrik** [comment]
Hi, I made a config to add custom input options to ffmpeg. (Api doc that I'm using: https://www.npmjs.com/package/fluent-ffmpeg#inputoptionsoption-add-custom-input-options)

Can you report back about your findings? Like: are you using docker and Raspberry pi 4? Could you make hardware acceleration work? If yes, with what configuration. If its an easy addition I will make it a default settings.

**Comment by bpatrik** [comment]
Looking a bit around. Might not work out of the box as size breaks with vaapi according to this: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1120

I'm using size: 
https://github.com/bpatrik/pigallery2/blob/e7983a6defa6d93c13e156ec23005ab437121d3e/src/backend/model/threading/VideoConverterWorker.ts#L67-L69

Also if you set logging to silly, it should print executed ffmpeg command.

**Comment by a-ilin** [comment]
Hello! Thanks a lot for great gallery!

I can confirm that the options specified in the field `Video transcoding / Custom Options` are going after the input file.
It would be very nice to have this fixed, as HW acceleration speeds up conversion in 8-13 times in my case!

Here are options I specified for VAAPI video conversion: `-init_hw_device vaapi=intel:/dev/dri/renderD128; -hwaccel vaapi; -hwaccel_output_format vaapi; -hwaccel_device intel; -filter_hw_device intel;`
Codec: `h264_vaapi`

Pigallery2 runs ffmpeg with the following command line (taken from logs):
`ffmpeg -i input.mp4 -y -b:v 5120k -vcodec h264_vaapi -r 25 -filter:v scale=w=trunc(oh*a/2)*2:h=720 -crf 23 -preset medium -init_hw_device vaapi=intel:/dev/dri/renderD128  -hwaccel vaapi  -hwaccel_output_format vaapi  -hwaccel_device intel -filter_hw_device intel -f mp4 output.mp4
`

As you see, the specified options are placed before the output file. The correct location would be before the input file, as below:
`ffmpeg -init_hw_device vaapi=intel:/dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device intel -filter_hw_device intel -i input.mp4 -y -b:v 5120k -vcodec h264_vaapi -r 25 -filter:v 'scale_vaapi=w=trunc(oh*a/2)*2:h=720' -crf 23 -preset medium -f mp4 output.mp4
`

Also a change in scaling filter is needed: instead of `scale` there is `scale_vaapi`.

Can you consider making ffmpeg options more customizable?

**Comment by a-ilin** [comment]
I've just noticed the input options are already added in the nightly builds.

With that I've managed to workaround other issues and enable HW acceleration with the following approach.

1. Use custom input options: `-init_hw_device vaapi=intel:/dev/dri/renderD128;-hwaccel vaapi;-hwaccel_output_format vaapi;-hwaccel_device intel;-filter_hw_device intel`

Note the absence of spaces in the options near `;` semicolons. Adding spaces causes incorrect empty arguments being passed to ffmpeg.


2. Use codec: `h264_vaapi`.


3. Apply the commits from PR: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/1121

This may be done with `patch-package` tool: https://www.npmjs.com/package/patch-package

The PR has a bug when videoCodec is not the first option, as in pigallery2. To fix the bug apply the following patch to `fluent-ffmpeg` (again, `patch-package` would work):
```patch
diff --git a/lib/options/videosize.js b/lib/options/videosize.js
--- a/lib/options/videosize.js
+++ b/lib/options/videosize.js
@@ -7,8 +7,8 @@


 function getScaleFilter(output) {
-  if (output.video.get('-vcodec').length > 1) {
-    let codec = output.video.get('-vcodec')[1];
+  if (!!output.video.find('-vcodec', 1)) {
+    let codec = output.video.find('-vcodec', 1)[0];

     if (codec.endsWith('_vaapi')) {
       return 'scale_vaapi';
```


After those steps are done HW acceleration works fine in my case.

**Comment by bpatrik** [comment]
I'm not sure what is the status of this issue.

Looking at the cod of the current     "fluent-ffmpeg": "2.1.2", ` function getScaleFilter(output)` function does not exist anymore and also did not exist for a while. There was no new release in the last 6 years: https://www.npmjs.com/package/fluent-ffmpeg. 

I'm closing this bug with the assumption that no further action is needed.

**Comment by ioncubekh** [comment]
@a-ilin Can you look at my issue here https://github.com/bpatrik/pigallery2/issues/977

I modified a portion of your code
```
     if (codec.endsWith('_rkmpp')) {
       return 'scale_rkrga';
```

> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Filter

It cannot identify codec `h264_rkmpp`

**Comment by kennethsible** [comment]
@bpatrik I tried following the steps outlined by @a-ilin above for `h264_vaapi`, but the **Temp Folder Cleaning** job keeps deleting all the transcoded files. I confirmed that both the `vaapi` codec and `scale_vaapi` filter are available in the Docker container. However, `h264_vaapi` isn't listed as an option for the MP4 codec in the Web UI, so I edited the `config.json` file.

```json
"mp4Codec": "h264_vaapi",
"customOutputOptions": [
    "-r 25",
    "-b:v 5120k",
    "-filter:v",
    "scale_vaapi=w=trunc(oh*a/2)*2:h=720"
],
"customInputOptions": [
    "-init_hw_device vaapi=intel:/dev/dri/renderD128",
    "-hwaccel vaapi",
    "-hwaccel_output_format vaapi",
    "-hwaccel_device intel",
    "-filter_hw_device intel"
]
```

@a-ilin didn't mention anything about the output options, but PiGallery2 wasn't generating these for me. I'm not seeing any ffmpeg errors in the logs, but PiGallery2 is deleting the transcoded files. Unfortunately, thermal throttling occurs on my Intel N100 Mini PC when using the default CPU transcoding, but the temperature never exceeds ~65°C when using the iGPU.

**Comment by bpatrik** [comment]
Here is the temp folder cleanup job: https://github.com/bpatrik/pigallery2/blob/master/src/backend/model/jobs/jobs/TempFolderCleaningJob.ts

Here it checks if a video in the temp folder is valid:
https://github.com/bpatrik/pigallery2/blob/45366861756af3fc83311d35892cda31fcae8580/src/backend/model/fileaccess/fileprocessing/VideoProcessing.ts#L25-L52

This is how the end of the filename is generate: 
https://github.com/bpatrik/pigallery2/blob/45366861756af3fc83311d35892cda31fcae8580/src/backend/model/fileaccess/fileprocessing/VideoProcessing.ts#L120-L130

I think it should just work. Can you check if the generate file names match these?

**Comment by kennethsible** [comment]
It looks like `convertedPath.lastIndexOf('_')` is causing the problem because `h264_vaapi` includes an underscore. After switching the log level to `DEBUG`, I noticed that when multiple codec options are provided, only the last one is actually used. So, I switched the value of `mp4Codec` back to `libx264`, which has no underscores, and added `-c:v h264_vaapi` to the output options.

However, the transcoded paths still ended up including `h264_vaapi`, so I instead tried using `-c:v:0 h264_vaapi`, assuming that the parser is specifically matching on `-c:v`, and that change worked! PiGallery2 now transcodes with `h264_vaapi`, while the transcoded paths contain `libx264` to avoid being removed during the cleaning job.

**Comment by rhatguy** [comment]
I got the below ffmpeg line to work inside the console of the container and even validated that it works with my intel GPU.  Is there a way to merge this into the config so all transcodes use it?  I don't quite understand  the above comments.  @kennethsible  would you mind pasting your working config? 


ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 
-i /app/data/images/year/filename.mp4 
-vf "format=nv12,hwupload" 
-b:v 5120k -c:v hevc_vaapi -r 30 -f mp4 
-y /app/data/tmp/tc/test_vaapi.mp4

**Comment by kennethsible** [comment]
Sure, here's the transcoding settings I've been using for the past few months:
```json
"transcoding": {
    "//[bitRate]": "Target bit rate of the output video will be scaled down to this. This should be less than the upload rate of your home server.",
    "bitRate": 8000000,
    "//[resolution]": "The height of the output video will be scaled down to this, while keeping the aspect ratio.",
    "resolution": 1080,
    "//[fps]": "Target frame per second (fps) of the output video will be scaled down to this.",
    "fps": 60,
    "format": "mp4",
    "mp4Codec": "libx264",
    "webmCodec": "libvpx",
    "//[crf]": "The range of the Constant Rate Factor (CRF) scale is 0–51, where 0 is lossless, 23 is the default, and 51 is worst quality possible.",
    "crf": 23,
    "//[preset]": "A preset is a collection of options that will provide a certain encoding speed to compression ratio. A slower preset will provide better compression (compression is quality per filesize).",
    "preset": "medium",
    "//[customOutputOptions]": "It will be sent to ffmpeg as it is, as custom output options.",
    "customOutputOptions": [
        "-c:v:0 h264_vaapi",
        "-b:v 8000k",
        "-filter:v",
        "format=nv12,hwupload,scale_vaapi=w=trunc(oh*a/2)*2:h=1080:format=nv12"
    ],
    "//[customInputOptions]": "It will be sent to ffmpeg as it is, as custom input options.",
    "customInputOptions": [
        "-init_hw_device vaapi=intel:/dev/dri/renderD128",
        "-filter_hw_device intel"
    ]
}
```

**Comment by rhatguy** [comment]
I finally got the accelerated transcoding on my 14th gen intel CPU working using the code block below.  The video's generated by this seem to play great in Safari (MacOSX and iOS).  I validated that the byte range that is requested by the browser in the request for the video matches the file size of the transcoded video being played and not the original so I'm confident the transcoded videos are working.

The issue I'm having now is that the "temp folder cleanup" job clears out all of my transcoded files.  I assume the cleanup job is looking at the filenames that are generated and thinking it doesn't need them.  Anyone know how I can stop the cleanup job from removing the transcoded files with filenames like shown below?

anniversary_video.mp4_5120khevc_vaapi1080.mp4


```
"transcoding": {
                "//[bitRate]": "Target bit rate of the output video will be scaled down to this. This should be less than the upload rate of your home serv
er.",
                "bitRate": 5242880,
                "//[resolution]": "The height of the output video will be scaled down to this, while keeping the aspect ratio.",
                "resolution": 1080,
                "//[fps]": "Target frame per second (fps) of the output video will be scaled down to this.",
                "fps": 30,
                "format": "mp4",
                "mp4Codec": "hevc_vaapi",
                "webmCodec": "libvpx",
                "//[crf]": "The range of the Constant Rate Factor (CRF) scale is 0–51, where 0 is lossless, 23 is the default, and 51 is worst quality poss
ible.",
                "crf": 23,
                "//[preset]": "A preset is a collection of options that will provide a certain encoding speed to compression ratio. A slower preset will pr
ovide better compression (compression is quality per filesize).",
                "preset": "medium",
                "//[customOutputOptions]": "It will be sent to ffmpeg as it is, as custom output options.",
                "customOutputOptions": [
                    "-c:v hevc_vaapi",
                    "-low_power 1",
                    "-tag:v hvc1",
                    "-rc_mode CQP",
                    "-global_quality 26",
                    "-bf 3",
                    "-refs 4",
                    "-g 240",
                    "-movflags +faststart",
                    "-filter:v",
                    "hqdn3d=1:1:3:3,format=nv12,hwupload,deinterlace_vaapi=mode=motion_adaptive,scale_vaapi=w=trunc(min(1080\\,ih)*a/2)*2:h=min(1080\\,ih)"
                ],
                "//[customInputOptions]": "It will be sent to ffmpeg as it is, as custom input options.",
                "customInputOptions": [
                    "-init_hw_device vaapi=intel:/dev/dri/renderD128",
                    "-filter_hw_device intel"
                ]
            }

```

**Comment by kennethsible** [comment]
@rhatguy If you look at my previous comments, PiGallery2 expects an underscore to separate the original filename from the metadata suffix. Your example filename has two underscores because the `hevc_vaapi` codec contains an underscore. I fixed this by tricking PiGallery2 into using `libx264` in the filename while actually using `h264_vaapi` for transcoding, which I did by setting "mp4Codec": "libx264" and adding "-c:v:0 h264_vaapi" to the customOutputOptions (the :0 is very important).

**Comment by rhatguy** [comment]
@kennethsible  Thanks for pointing me in the right direction.  I had read your previous comment, but it didn't register for me that I was having the same issue until you pointed it out.  I've now updated my transcoding configuration as shown below.  My issue was exactly as you described where the filename was breaking things.  After changing mp4Codec to "libx264" my filenames now look as below and are not deleted by the cleanup job.  I switched from a 14 core Intel 6132 to an Intel 14400 and the addition of the intel GPU makes night and day difference.

Previously - anniversary_video.mp4_5120khevc_vaapi1080.mp4
now - anniversary_video.mp4_5120klibx2641080.mp4

```"transcoding": {
                "//[bitRate]": "Target bit rate of the output video will be scaled down to this. This should be less than the upload rate of your home server.",
                "bitRate": 5242880,
                "//[resolution]": "The height of the output video will be scaled down to this, while keeping the aspect ratio.",
                "resolution": 1080,
                "//[fps]": "Target frame per second (fps) of the output video will be scaled down to this.",
                "fps": 30,
                "format": "mp4",
                "mp4Codec": "libx264",
                "webmCodec": "libvpx",
                "//[crf]": "The range of the Constant Rate Factor (CRF) scale is 0–51, where 0 is lossless, 23 is the default, and 51 is worst quality possible.",
                "crf": 23,
                "//[preset]": "A preset is a collection of options that will provide a certain encoding speed to compression ratio. A slower preset will provide better compression (compression is quality per filesize).",
                "preset": "medium",
                "//[customOutputOptions]": "It will be sent to ffmpeg as it is, as custom output options.",
                "customOutputOptions": [
                    "-c:v:0 hevc_vaapi",
                    "-low_power 1",
                    "-tag:v hvc1",
                    "-rc_mode CQP",
                    "-global_quality 26",
                    "-bf 3",
                    "-refs 4",
                    "-g 240",
                    "-movflags +faststart",
                    "-filter:v",
                    "hqdn3d=1:1:3:3,format=nv12,hwupload,deinterlace_vaapi=mode=motion_adaptive,scale_vaapi=w=trunc(min(1080\\,ih)*a/2)*2:h=min(1080\\,ih)"
                ],
                "//[customInputOptions]": "It will be sent to ffmpeg as it is, as custom input options.",
                "customInputOptions": [
                    "-init_hw_device vaapi=intel:/dev/dri/renderD128",
                    "-filter_hw_device intel"
                ]
            }
```
