### ISSUE TITLE
'Enforced users' text shows up in wrong place in Configuration

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#594]
I can see the text 'Enforced users' also as one of the options in Media | Thumbnails. It should be something relating to image compression I think, but I could not find what it once was.

![Screenshot from 2023-01-17 08-36-24](https://user-images.githubusercontent.com/4752390/212839073-df036350-0deb-42e5-a400-6cff12234c8d.png)

**Comment by bpatrik** [comment]
Last commit should fix this.
