### ISSUE TITLE
There is problem in single picture show in mobile browser 

### ISSUE THREAD

**Issue by zjuerkzhang** [bpatrik/pigallery2#6]
Single picture show in desktop browser is OK, but in mobile browser the picture is shown in the bottom right conner. I tried in chrome/safari in iPad and safari in iPhone.

**Comment by bpatrik** [comment]
thank you @zjuerkzhang for the report, I'll try to look into to it ASAP. It might take a while, I'm focusing lately on other projects.

**Comment by studioai** [comment]
+1

**Comment by tomikais** [comment]
iPad, iPhone and mac Safari have problems to display the website correctly

**Comment by bpatrik** [comment]
sorry for the late response. 
Unfortunately I have limited access to IPhone / Safari, but I found the similar error in Edge too. 
I fixed it there, you can try it here:
https://pigallery2.herokuapp.com/
If it works I'll do a release from this.

**Comment by tomikais** [comment]
In the detail view, the image is now displayed correctly:
<img width="185" alt="detail" src="https://user-images.githubusercontent.com/7860085/39636082-7ba50950-4fbf-11e8-858e-cfce7c79e498.png">

On the overview page, when you click on a picture, the picture jumps slightly upwards:
![overview](https://user-images.githubusercontent.com/7860085/39636168-bcc03c5c-4fbf-11e8-90fe-413920d13afc.png)

**Comment by bpatrik** [comment]
ok, thank you for testing.
I'll try to fix it in the next couple of weeks.

**Comment by bpatrik** [comment]
I think a managed to fix it. 
If you confirm it, I'll do a release.

**Comment by tomikais** [comment]
Nice! No jumping pictures. But in your demo gallery there are a lot of doubles. Can you please have a look?

**Comment by tomikais** [comment]
now everything looks fine!

**Comment by bpatrik** [comment]
I've made several design related improvements lately (will be out with the latest release).
If there isn't any more design related errors, I'll close this issue.
