### ISSUE TITLE
[Feature request] Public browsing

### ISSUE THREAD

**Issue by Liandriz** [bpatrik/pigallery2#60]
Hi, i did some research, but didn' find any hint about it.  
Is it possible atm to make the gallery totally public or any chance to get it? Really enjoy your app, would be great to have it publicly browsable, thanks.

**Comment by bpatrik** [comment]
Hi

You can set up the app such a way that it does not require login.
Or you can create a link, sharing a folder (and optionally its sub folder.)
Is that what you are looking for?

**Comment by Liandriz** [comment]
Yes, didn't find how to set it up to doesn't require login to just browse please 👍

**Comment by bpatrik** [comment]
You can just disable password protection in the settings

![settings](https://user-images.githubusercontent.com/7512182/54119252-2a76fb80-43f5-11e9-97d1-7d7ce115f7a9.jpg)

**Comment by Liandriz** [comment]
With password disabled, administration is open to all viewers no? :/

**Comment by bpatrik** [comment]
You can set the default role for the unauthenticated user.
You need to manually edit `config.json` and set  [unAuthenticatedUserRole](https://github.com/bpatrik/pigallery2/blob/43142299aadad8c3631e2a4776120d72f0c4557e/common/config/public/ConfigClass.ts#L155) to a different value.
The default value is Admin (4), you can set it to user (3).
You can find the list of roles and their rights here: https://github.com/bpatrik/pigallery2/blob/master/USERRIGHTS.md

**Comment by Liandriz** [comment]
Thanks, got it working, didn't look at this file.  
After making it available with a simple user (level 3 for unAuthenticatedUserRole), is it possible to logout and login to admin account, or is it stuck to level 3 account?  
Thanks again for your help.

**Comment by bpatrik** [comment]
Unfortunately there is no was currently to log in as admin. 
Generally you do not need the admin role after the initial setup.
I mean you might want to run the `indexing` manually once after installation and also do the required settings, but apart from that you won't really need admin rights anymore.

**Comment by Liandriz** [comment]
Ok thanks, will do that way, and manually restart app to force indexing.

**Comment by bpatrik** [comment]
You do not need to restart the app to force indexing. Just click on the
'index' button in the settings.
But its not necessary. If you open a folder in the app, it will index it.
(you can only search within indexed folders)

Patrik

Liandri <notifications@github.com> ezt írta (időpont: 2019. márc. 11., H,
15:12):

**Comment by Liandriz** [comment]
Yep, just getting some first index, then switching to simple user account mode and restarting.  
Thanks for the help, can close now 👍
