### ISSUE TITLE
[documentation?] Safari/MacOS10.x do not support WebP

### ISSUE THREAD

**Issue by 4gra** [bpatrik/pigallery2#603]
**Describe the bug**

Since Pigallery2 has moved to using WebP, Safari on older versions of MacOS which might be expected to work (v14 and v15) cannot browser pigallery2. All thumbnails on all pages and all lightbox images show as 'broken' / 'missing'.  This appears to be a regression since v1.9.3 worked fine for these clients.

This is a global problem and not really a pigallery2 bug, just an incompatibility with Safari, but because Apple have done a poor job of documenting this limitation (Apple claim simply that Safari 14+ support WebP) it might be worth noting against the 1.9.5 release.  

The workaround is straightforward - use any other modern browser on this platform.  Chrome on 10.15 works fine for example.  Support can be established using Google's test images: https://developers.google.com/speed/webp/gallery

**Environment (please complete the following information):**
 - OS: any Server OS
 - Browser: Safari (any version) using MacOS < 11.x (e.g. Catalina 10.15).

**Used app version**:
- release v1.9.5

**Comment by bpatrik** [comment]
Hi thanks for flagging this.

Im not that familiar with apple. Can you tell how many people can be
impacted by this? Like how old are those devices that cannot be updated
anymore to have a Safari with webp support?

I'll add the warning to the release

Patrik

-- Sorry for being brief, sent from my phone.

**Comment by 4gra** [comment]
> Can you tell how many people can be
> impacted by this? Like how old are those devices that cannot be updated
> anymore to have a Safari with webp support?

Hi, I don't have a good sense of how many people affected and of course MacOS is a small market but it looks like any MacBook Pro from 2015 or earlier could be affected - there is a compatibility list somewhere but potentially some devices as new as 6 years old could be affected.

The additional confusion is that these devices might be running the very latest Safari even though their MacOS is outdated.

**Comment by bpatrik** [comment]
Thanks. I have updated the release notes with a warning.
