### ISSUE TITLE
Inadvertent Public Exposure of Photos by Sharing

### ISSUE THREAD

**Issue by numen31337** [bpatrik/pigallery2#607]
**Is your feature request related to a problem? Please describe.**
I run a family photo library and sometimes I want to share photos with my friends. I have the sharing feature enabled with password protection for security. However, if anyone, including me or a family member, accidentally clicks the share button, it creates a public link to the photos right away. The link may even lead to the entire photo gallery if it was clicked on the main page. The issue is that there is no way to cancel the share once it's been created, and the copy button is disabled until a password is entered, making it seem like no share was created even though the gallery is now publicly accessible with the right link.

<img width="503" alt="Screenshot 2023-02-10 at 23 44 57" src="https://user-images.githubusercontent.com/5677845/218216012-412ad4fb-4dbc-428b-b272-9d7b3aec579c.png">

**Describe the solution you'd like**
I'd suggest adding an option to only create shares with a password or modifying the dialog to clearly indicate that a link has been created and provide the ability to cancel the action in case it was done accidentally.

**Comment by kagahd** [comment]
I want to underline the importance of this request because the link to the shared album is created **as soon as an user** (not even an admin) **clicks on the "share" button**! 
So if you clicked the "shared" button accidentally and immediately closed the dialog window, the link has already been silently created with the default validity period **without being password protected** and **without any notification**!
In my opinion, if an admin has activated the option `Enables password protected sharing links` then PiGallery must create the link **only** when a password is provided.

**Comment by unlucio** [comment]
I started using pigallery2 yesterday and this got me super confused:
1) The invalid settings made me think there as something wrong with the whole configuration, so I went a bit nuts trying to find out what was wrong with it. "Invalid Settings" didn't really convey to me that all was missing was the password.
2) While trying to figure out what was wrong I clicked the `share` button a bunch of times, unknowingly creating a tons of share links and of course I also did it for my entire library like @numen31337.

I'm not sure how many people would expect that a share is created asap they click the `share` button, I certainly did not.
It's probably better to wait for some "positive action" from the user before actually creating the share.

I'd be willing (I usually prefer a functional style to a heavily OBJ oriented one) to take care of it and submit a PR, perhaps adding the ability of sharing a single item as suggested by https://github.com/bpatrik/pigallery2/issues/243.
Perhaps @kagahd can confirm if https://github.com/bpatrik/pigallery2/blob/master/src/backend/middlewares/SharingMWs.ts and https://github.com/bpatrik/pigallery2/blob/master/src/frontend/app/ui/gallery/share.service.ts are the 2 places where to start on this.

**Comment by kagahd** [comment]
@unlucio yes, the sources look like these but @bpatrik should confirm more reliably.

**Comment by bpatrik** [comment]
Hi,

See my comment in #489:
"
Accidental sharing creation is indeed sounds to be a bug.

I think the app should print if there is any active sharing available for
the folder in view.

Once I get some more time to work on this app, I'll look into it.

Also to the app's defense the sharing key is only known within the app and
those who you share with.
I don't see how is it significantly stronger if you protect the link with a
password and the  Send the password over with the link itself.
"

@unlucio about sharing a single photo: lets continue here: #243

**Comment by bpatrik** [comment]
The latest commit should fix it:

![kép](https://github.com/bpatrik/pigallery2/assets/7512182/353744a4-b0b0-43c4-9746-5644fcbbc3cd)

**Comment by numen31337** [comment]
I may not have a complete understanding of the project's nuances, but would it be possible to consider adding a "Confirm" or "OK" button within this dialog? This would allow users to initiate the sharing process more intentionally, rather than it starting immediately.

**Comment by bpatrik** [comment]
With the latest update, it only creats the sharing link when you explicitly
click the button.

It also show the already created shares for the directory.

-- Sorry for being brief, sent from my phone.
