### ISSUE TITLE
Share button is not appearing on Firefox

### ISSUE THREAD

**Issue by patrickbolle** [bpatrik/pigallery2#61]
**Describe the bug**
No share button appears where it should be (in the top right corner beside search). The setting is enabled but nothing appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/11012317/54872565-8aca4d80-4da4-11e9-9aec-27dc572805ae.png)

![image](https://user-images.githubusercontent.com/11012317/54872540-522a7400-4da4-11e9-86dd-470eb042da94.png)

**Enviroment (please complete the following information):**
 - OS: Ubuntu 16.04 on VPS
 - Browser: Firefox

**Used app version**:
- docker-nightly

**Comment by patrickbolle** [comment]
*** Just checked in Chrome, Share button appears and shows up fine. Must be a Firefox only issue.

Using Firefox Nightly.

**Comment by bpatrik** [comment]
Hi,

Unfortunately I could not reproduce so far. (Using Firefox stable and nightly)
I suspect that this might be a configuration error. It might happen that the configuration could not go successfully through when using UI ( but It looks like as it was successful)

Can you check if the config is successfully set?
So like: 
 * the `config.json` says that `Client.Sharing.enabled` is `true` 
     *  and also `Client.authenticationRequired=true`  as you need login for the sharing function 
     *  and also `Server.databse.type` is `2`(mysql) or `3`(sqlite) as you need DB for sharing
 * also after you set the config on the UI and refresh the page, does the settings stay enabled?
 * you can also try setting `Server.log.level=6` to enable full server side logging. (Then you can inspect the logs with `docker logs <containerId>`)

**Comment by patrickbolle** [comment]
Ah! I got it.

The share button gets stuck in my uBlock origin filters it seems. Those filters are meant to block Facebook/Twitter/etc sharing modules but it seems this one gets put into the mix because of the class names and wording.

Thanks for the help nevertheless!

**Comment by bpatrik** [comment]
Hi 

Is this a custom uBlock settings or a relatively common one? 
(I tried to reproduce, but I could not.) If it is a common I can try to fix it.

**Comment by tkedwards** [comment]
Same issue seen using Adblock Plus on Firefox on Ubuntu
