### ISSUE TITLE
Docker non root user group

### ISSUE THREAD

**Issue by HuwSy** [bpatrik/pigallery2#610]
**Is your feature request related to a problem? Please describe.**
docker with —user and a uid:gid does not start, stuck in reboot loop, as it appears this needs root somewhere but ideally docker containers should not run as root

**Describe the solution you'd like**
Default running non root user and group within the container make file, or fix usage with —user in docker cli

**Describe alternatives you've considered** (optional)
As above, —user uid:gid as per other docker containers

**Comment by bpatrik** [comment]
Do you want to bind the docker port to the host's 80 or 443 port?

Those need root rights.

**Comment by HuwSy** [comment]
No, it’s binding to 8090 on the host. Within the container it’s at port 80 though. Could that be the issue as the --user command stops it being root within the container? Is there a way of changing this easily via docker exec to test?

**Comment by bpatrik** [comment]
You can set the ENV variable PORT to 8090 to change the port within the container

**Comment by HuwSy** [comment]
Ah. Missed that one. Thank you.
