### ISSUE TITLE
The directory name contains the "[" character, which causes the directory to not recurse to the preview image under the subdirectory

### ISSUE THREAD

**Issue by zzy-boy** [bpatrik/pigallery2#621]
**Describe the bug**
Hi,I found that when the parent directory contains the '[' character, the parent directory will not use the preview image of the child directory as the cover page

Like this

<img width="523" alt="image" src="https://user-images.githubusercontent.com/59224151/221622021-f3cddfb9-bc74-4aad-ab71-0b780ab6ca6d.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/59224151/221622857-59fa73d2-84b0-4d7b-9fad-e3cf3dd59345.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/59224151/221622951-1d2535e8-094e-4553-88ec-a2c3a8e61ae3.png">

So I made the following modifications to line 191 in the src/backend/model/database/PreviewManager.ts(192 line): file, and it can be displayed normally:

` q.orWhere('directory.path GLOB :path', {
                path: DiskMangerWorker.pathFromParent(dir) + "*",
              });`
->
`     q.orWhere('directory.path GLOB :path', {
                path: DiskMangerWorker.pathFromParent(dir).replace('[', '[[]') + "*",
              });`

But I think this is not rigorous. It is a bit like sql injection. Should we filter these wildcards for these statements

**Environment (please complete the following information):**
 - OS: [Mac OS,docker]
 - Browser [edge, chrome, safari]

**Used app version**:
- compiled from source
- docker

**Comment by bpatrik** [comment]
I got there to have a moment checking this.

Indeed its a wildcard issue as you pointed out: https://stackoverflow.com/questions/44904120/how-to-escape-and-in-glob

**Comment by bpatrik** [comment]
It seems this  https://www.npmjs.com/package/glob-escape wont work here. 

Added some test to it and it seems that `.replaceAll('[', '[[]')` solve the issue. I agree that is not the best, but I could not find any better solution for now. Also directories cannot contain arbitrary characters, like stars, so that helps.
