### ISSUE TITLE
Portfolio mode

### ISSUE THREAD

**Issue by gerroon** [bpatrik/pigallery2#623]
Hi

I would like to use PG2 for portfdolio purposes. It is almost there except that in Portfolio mode some kind of custom sort is needed so that the person can decide which image shows up first etc with the shared link.

thanks

**Comment by bpatrik** [comment]
Hi

It is not possible at the moment. All photo related information should come from the raw photo file. (See readme: no edits and manual changes are possible or planned to be available) I recommend changing the file name and sorting by that or adding rating and sorting by that.

**Comment by bpatrik** [comment]
I'm closing this due to does not fit the philosophy of the app.
