### ISSUE TITLE
Top part of settings page hidden by navbar

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#629]
**Describe the bug**

In the newest nightlies, the top navbar shows and disappears with scrolling (works quite well and is very welcome by the way!). 

In the settings page, the version, top part of the menu box and the Mode dropdown are partially hidden by it when scrolling down and then back up,

![image](https://user-images.githubusercontent.com/4752390/223720708-822e7d67-afa8-4e66-bfea-2086551cbf76.png)

- docker-nightly

**Comment by bpatrik** [comment]
The current behavior:
* navbar stays on the top of the page while it still visible
* scrolling down, when it gets out of the view, it gets hodden
* scrolling up, it shows up
* scrolling down again, it disapears
Based on this:
* when you scroll down it should go away and make everything visible 
* when you scroll to the very top of the page, you should able to access everything

From this I would say work as expected

**Comment by mrtnbr** [comment]
I've played with it some more now, and with your explanation it seems more logical to me now.

It might be the 'Menu' box on the left that always stays on screen when scrolling down competing for the same bit of screen with the navbar when scrolling back up.

This is a very minor issue of course :)

**Comment by mrtnbr** [comment]
Thank you for the fix! Works well and looks good!
