### ISSUE TITLE
Sharing URLs are malformed on the Admin page

### ISSUE THREAD

**Issue by jdavidpeter** [bpatrik/pigallery2#631]
**Describe the bug**

Shares have sharing URLs on the Admin page frontend like:
< a _ngcontent-rcr-c101="" href="https:/redacted.duckdns.org/sharea9322371">a9322371</a>
Note the missing slash after https: as well as the missing slash between "share" and the share ID
(I have added an extra space after < so github won't embed the HTML)

One error is using Ultis.conatUrls function to create the Share URL as that normalizes away double slashes:
https://github.com/bpatrik/pigallery2/blob/a3f7f200a9e692277d49d77ec8b0714a1f83ce3c/src/frontend/app/ui/settings/sharings-list/sharings-list.component.ts#L21
https://github.com/bpatrik/pigallery2/blob/d11719cc3981b5481abe4333f63ad53fa74edd05/src/common/Utils.ts#L132

I'm not sure what swallows the slashes from the URL part "/share/"

**Photo/video (optional) that causes the bug**

Not related to any media.

**Environment (please complete the following information):**
```
redacted@redacted:~/pigallery$ apt-get  lsb_release -a
E: Command line option 'a' [from -a] is not understood in combination with the other options.
davidpeter@dczero:~/pigallery$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
redacted@redacted:~/pigallery$ grep bpatrik docker-compose.yaml
    image: bpatrik/pigallery2:nightly-alpine

```

**Used app version**:

docker-nightly-alpine

**Context screenshot**:
![image](https://user-images.githubusercontent.com/14619409/224111535-4a50a370-b99b-4c21-be16-fea1537e47e1.png)

**Comment by bpatrik** [comment]
Thank you!
I knew about the issues. The last commit should fix it.

**Comment by bpatrik** [comment]
> I'm not sure what swallows the slashes from the URL part "/share/"

The return line removes the last character. Probably a bug, but I'm afraid to touch it.

**Comment by jdavidpeter** [comment]
Link works now, although the lack of space between the hyperlink and the Sharing root URL is  a little strange, but this might be nitpicking.
Thank you!
Also, nice, well structured code, was super easy to find the offending section with 0 experience in any frontend magic.
