### ISSUE TITLE
Missing quotes in search query in position link on the info box

### ISSUE THREAD

**Issue by SmartFinn** [bpatrik/pigallery2#634]
**Describe the bug**

The link to position in the hoverable info box works fine, except the case when metadata contains:

> metadataPositionDataCountry: Ukraine
> metadataPositionDataState: Donetsk Oblast
> metadataPositionDataCity: Donetsk

In the case, click on "Donetsk"returns photos for "Donetsk" and for "Donetsk Oblast".

Adding quotes to search query `position:"Donetsk"` fixes the issue.

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/819186/224621738-aefeac15-c1c1-4230-9f10-b95c05e3be24.png) ![image](https://user-images.githubusercontent.com/819186/224622183-07dd156b-0b33-4901-82a6-b72425160ba5.png) ![image](https://user-images.githubusercontent.com/819186/224623586-de182a49-8d9c-4035-96c1-11a597394a7c.png)

**Environment (please complete the following information):**
 - OS: Linux (podman)
 - Browser Firefox 110.0

**Used app version**:
- bpatrik/pigallery2:latest-alpine

**Comment by bpatrik** [comment]
Thanks. I will look into it. In the meantime if you are not afraid: i accept PR's.it should be an easy fix:)
