### ISSUE TITLE
Unable to read City from Iptc tag when it equals 14 Cyrillic chars

### ISSUE THREAD

**Issue by SmartFinn** [bpatrik/pigallery2#636]
**Describe the bug**

I faced with really weird bug. The bug is coming from https://github.com/bpatrik/ts-node-iptc

This happens when city in IPTC tags equal 14 Cyrillic chars. It's strange because with 13 (`Старомлинівка`) and 15 (`Завітне бажання`) characters it works as expected.

Here is a list of real Ukrainian villages, for testing:

```
Олександроград
Старомайорське
Новомиколаївка
Новогригорівка
```

**Photo/video (optional) that causes the bug**

[photos_city_14_cyrillic_chars.zip](https://github.com/bpatrik/pigallery2/files/10960695/photos_city_14_cyrillic_chars.zip)

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/819186/224798941-5e12dfd3-e28c-4bb2-b40c-bcdc23cff7f1.png) ![image](https://user-images.githubusercontent.com/819186/224790477-992740f4-62b6-4373-9290-161cbef1d6ad.png) 

**Used app version**:
- docker-nightly

**Comment by SmartFinn** [comment]
It works with ExifReader:
![image](https://user-images.githubusercontent.com/819186/224800973-6aef474f-bb3c-4156-931a-b25a2c8ace51.png)

**Comment by bpatrik** [comment]
that looks very odd. I eventually want to update the MetadataLoader #277. Although I don't know when will that happen. Probably not in the next 6 months.  I'm not sure how much I would want to invest in fixing something like this.

**Comment by grasdk** [comment]
@SmartFinn 

If you build from source now, it seems to work. Here are my results:

![image](https://github.com/bpatrik/pigallery2/assets/115414609/e48ab60b-8575-4b1d-b626-d976c941c0b2)
![image](https://github.com/bpatrik/pigallery2/assets/115414609/7ddbd9e8-257e-404d-87d4-d85716788023)
![image](https://github.com/bpatrik/pigallery2/assets/115414609/49c63899-8c87-4961-aa7a-6bf3cf114593)

**Comment by SmartFinn** [comment]
@grasdk I just tested with docker edge-alpine image. Now, it works as expected. Thank you!
