### ISSUE TITLE
Move to/Support another Docker registry other than Docker Hub

### ISSUE THREAD

**Issue by jacroe** [bpatrik/pigallery2#643]
**Is your feature request related to a problem? Please describe.**
Based on the issues described in [this blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/), Docker Hub is, perhaps, no longer a safe provider of Docker images. Unless the project is willing to pay.

**Describe the solution you'd like**
Support a different Docker registry, in combination or not, with [GHCR.io](https://ghcr.io/) or [Quay](https://quay.io/).

**Describe alternatives you've considered**
N/A

**Additional context**
Quite a bit of additional context can be seen in [Hacker News](https://news.ycombinator.com/item?id=35166317) and this [/r/selfhosted post](https://www.reddit.com/r/selfhosted/comments/11ryub1/fyi_docker_is_deleting_open_source_organisations/).

**Comment by bpatrik** [comment]
Hi,

Thank you for bringing this to my attention. 
To my understanding this repo is not effected as I'm publishing it under my name and there is no organization related to it.
So far I did not get any mail that it will be restricted or I will need to pay any money. 
At docker hub I only see these options, i'm using the free personal plan:
![kép](https://user-images.githubusercontent.com/7512182/226473307-5f2e401b-2a8e-4545-9491-8861b074ee6c.png)

I don't want to touch it until it works. 

I don't want to get into speculations and politics/economics on this forum, but I'm not too surprised on this move given the economical changes in the last few years. heroku also changed to played plan only recenty, so I had to move to onredner, which is way slower and limited, compared to heroku. I hope github will stay as it is with free actions in the future.

**Comment by jacroe** [comment]
> To my understanding this repo is not effected as I'm publishing it under my name and there is no organization related to it.
> So far I did not get any mail that it will be restricted or I will need to pay any money.
> At docker hub I only see these options, i'm using the free personal plan:

Okay that's good to hear. I've not needed to publish to Docker Hub before so I'm not 100% read up on what's offered and how and under what circumstances. However

> ... but I'm not too surprised on this move given the economical changes in the last few years. 

I do feel that the personal plan might be next on the chopping block. They've certainly lost a lot of trust with this move, especially with the 30 days guidance.

That all being said though

> I don't want to touch it until it works.

I can certainly understand and get behind that. So thanks for considering it. I do appreciate it and your work on the project as a whole.
