### ISSUE TITLE
etimedout error

### ISSUE THREAD

**Issue by Meteors27** [bpatrik/pigallery2#649]
**Describe the bug**

Why is my pigallery showing this error? It seems that did nothing and it appeared suddenly. 

**Screenshots (optional)**

<img width="434" alt="image" src="https://user-images.githubusercontent.com/59506669/227730967-05014c0f-fe93-489d-8d6b-318166019f6a.png">

**Comment by bpatrik** [comment]
My guess this is a network connection issue. App does not not do too manuz network class. One instance is when you `5-km-from:` search.

**Comment by Meteors27** [comment]
thanks, this error only appeared once and never shows since then.
