### ISSUE TITLE
Face-tag with German Umlaut

### ISSUE THREAD

**Issue by hajo62** [bpatrik/pigallery2#650]
I've created some face tags with German Umlauts like in Urgro**ß**vater.
I wrote the tags with XnViewMP. There, they are displayed correct: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/15800980/227798812-024571b3-2a86-44cf-a69b-119fa6b346f4.png">

In Pigallery2 the tag is shown as "UrgroÃvater".

I'm running PiGallery2 with mariaDB as docker containers on a Pi running ubuntu 22.04.1

What might cause the strange coding?

**Comment by bpatrik** [comment]
My guess is that you have a character set mismatch between your DB and XnViewMP.

**Comment by hajo62** [comment]
Would adding this parameter `--character-set-server=utf8mb4` to the start command in my docker-compose.yaml solve the problem?


`  command: sh -c 'bin/wait-for 192.168.178.3:${MYSQL_PGDATABASEPort} -- --Server-Database-mysqlhost=192.168.178.3 --Server-Database-mysql-username=${MYSQL_PGUSER} --Server-Database-mysqlpassword="${MYSQL_PGPASSWORD}" --Server-Database-mysql-database="${MYSQL_PGDATABASE}"'`

**Comment by bpatrik** [comment]
I'm not sure. I'm only using sqlite.

I guess is the problem is actually with your exif tool using the wring characterset. I would try using and other one to see if that shows the characters properly.

**Comment by bpatrik** [comment]
Using lightroom for tagging and sqlite as DB, I have no issues having special characters
