### ISSUE TITLE
Problem generating video thumbnail 

### ISSUE THREAD

**Issue by DrPeterVC** [bpatrik/pigallery2#651]
Not sure why some of my videos are generating zero size webp thumbnails - while others are fine.  Here is an output from the logs:

[FFmpeg] Error: ffmpeg exited with code 1: video encoding failed: Cannot allocate memory
Conversion failed!
 executed: ffmpeg -ss 90.1503 -i /app/data/images/Videos/xxxxxx.wmv -y -filter_complex scale=w=trunc(oh*a/2)*2:h=240[size0];[size0]split=1[screen0] -vframes 1 -qscale:v 4 -map [screen0] /app/data/tmp/tc/Videos/xxxxxx.wmv_240q80.webp
3/29/2023, 1:45:35 PM[ERROR][FileJob] Error during processing file:/app/data/images/Videos/xxxxxx.wmv, [FFmpeg] Error: ffmpeg exited with code 1: video encoding failed:

Any ideas (I have xxxxxx the actual file name but otherwise it is exactly from the log).

Many thanks in advance for any help.

**Comment by bpatrik** [comment]
From the error message it looks that you do not have enough ram (or ram on
the graphics card), but otherwise I have no idea. I think the issues is
with the setup/environment

**Comment by DrPeterVC** [comment]
Thanks for your reply.

I only have a lowly Pi2B with 1G RAM and most photo gallery apps won't run at all.  Hence why I think your program is so fantastic.

You are probably right.  I have a workaround which is to convert my wmv files to MP4 using ffmpeg on "bare metal" using default settings. Then delete the wmv files.

On an asside it would be great to have some mechanism to choose the thumbnail for the videos as it looks like the thumbnail is generated by just going a fixed time into each vid.

Keep up the good work!
