### ISSUE TITLE
Language change does nothing

### ISSUE THREAD

**Issue by desertwitch** [bpatrik/pigallery2#652]
**Describe the bug**

When selecting a different language, the language does not change.
Instead the default language of the browser seems to persist no matter what.

**Screenshots (optional)**
<img width="131" alt="pigallery-language-bug" src="https://user-images.githubusercontent.com/24509509/229425787-70d2b626-100e-44e7-bdc0-bbcb3d65b830.png">

**Environment (please complete the following information):**
Chrome, Firefox on Windows 11 Home

**Used app version**:
Docker App Version: v1.9.6-nightly

**Comment by bpatrik** [comment]
Thanks for reporting. Its a caching issues. The last commit hopefully fixes it.
