### ISSUE TITLE
No faces to show.

### ISSUE THREAD

**Issue by hajo62** [bpatrik/pigallery2#656]
I retagged a lot of faces in my photos (because of the umlauts problem I had caused by different character sets of my tagging tool and PG2. See question #650) and everything worked fine.
I made no changes on versions or setup, but
today I see `No faces to show` when I click on the faces link on the top menu.

BUT: When I browse a photo, I see faces tags displayed and when I click on a face tag, other photos haven the same tag attached are displayed.

I see some entries in the settings for logs. But where are those located?

**Comment by rhatguy** [comment]
I'm not sure if this is helpful, but I have lots of photos tagged with Digikam and they show up as per normal in pigallery2.  I'm running the latest container in docker.  Maybe check some of the logs in pigallery2.  It must be something environmental causing the faces not to show up.

**Comment by bpatrik** [comment]
Does anything show up on the faces tag? Like the list of faces are there
just photos are not shown or the list is empty?

Does it show up if you check back a bit later?

What happens if you hit the generate preview job in the settings? Does that
ever finish?


-- Sorry for being brief, sent from my phone.

**Comment by hajo62** [comment]
Yes, the message, that there is nothing to show.
Also there is no search in that view.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/15800980/233666829-f0ff996e-878a-41ac-9269-feb372cc6425.png">

Situation unchanged since it occurred 3 days ago.

Here a photo with faces tags:
![image](https://user-images.githubusercontent.com/15800980/233668371-1e3cbf2f-d8fd-4c26-a5d9-daa9a82133dc.png)

When I click on one of the tags, I see other photos tagged the same:
![image](https://user-images.githubusercontent.com/15800980/233668947-88c2a483-747d-432b-80e2-821871dc8252.png)


> Preview job:

I have never started one of those jobs. For me it was okay for a long time, when I browsed first a folder and the previews are generated on the fly. Which job shall I run?
<img width="973" alt="image" src="https://user-images.githubusercontent.com/15800980/233667760-9503e6b5-6478-43d5-a1ec-72c49a413bc2.png">

**Comment by rhatguy** [comment]
I think you just need to kick off indexing.  The others should run "after" indexing finishes. I schedule mine to run every night whether it needs it or not.

**Comment by hajo62** [comment]
The first two jobs `Indexing` and  `Preview Filling after Indexing` are done;  `Thumbnail Generation after Preview Filling` is nearly ready and - as expected, because I had faces before I first run the jobs - **unchanged**. Still nothing in the faces view...

**Comment by bpatrik** [comment]
> Also there is no search in that view.
Is works as intended. Search is only for the gallery view.

I'm not sure what is the issue. I would need to see some debug logs. 
Can you set `NODE_ENV=debug` in your docker compose file. restart the app and navigate to the faces tab and port here the debug log from the server (you will need these command to get there: `docker ps`, `docker logs <container id>`, etc.. )?

**Comment by hajo62** [comment]
[Here](https://nc.hajo62.duckdns.org/s/sia66WdzFqMWQj2) is the log - removed the password.

Might it be, that there is a tag in one photo causing this problem? 
`TypeError: Cannot read properties of undefined (reading 'name')`

**Comment by bpatrik** [comment]
Added more logging to the problematic part. Can you try it on the latest version to see which photo / name causing the issue?

**Comment by hajo62** [comment]
The log shows a file causing the problem.
Shall I just remove or repair the file or are you interested in some more details...
```
ErrorDTO {
pigallery2  |   code: 36,
pigallery2  |   message: 'Error during postprocessing result: adding thumbnail info for persons. Failed on: person HÃ¼ttl, at 1944-Album 111.jpeg ',
pigallery2  |   details: "TypeError: Cannot read properties of undefined (reading 'name')",
pigallery2  |   request: { method: '', url: '' },
pigallery2  |   detailsStr: "TypeError: Cannot read properties of undefined (reading 'name')"
pigallery2  | }
```

Additional question: Because I now had run the indexing and preview generating jobs, I now have used more than 6 GB in the `tc` folder. Is it okay to just remove the content and the previews are regenerated on demand?

**Comment by bpatrik** [comment]
Is it possible to send me the photo, so I test it?

-- Sorry for being brief, sent from my phone.

**Comment by hajo62** [comment]
Pls. look [here](https://www.dropbox.com/s/472cictl50xm3tf/1944-Album%20111.jpeg?dl=0):

**Comment by hajo62** [comment]
My followup question: 

- Because I now had run the indexing and preview generating jobs, I now have used more than 6 GB in the tc folder. Is it okay to just remove the content and the previews are regenerated on demand?

**Comment by bpatrik** [comment]
I had a look to the photo and issue is not with that photo.
I can also guess that maybe the file path or some symlink can cause the issue.


Yes feel free to remove the temp folder.

**Comment by 02015678** [comment]
Thanks, using [nightly-alpine](https://hub.docker.com/layers/bpatrik/pigallery2/nightly-alpine/images/sha256-5fd1e780bad03d303fdb12cf31ae2a4ece1e5d159a9e228844505a6acc89f53c?context=explore), I can finally identify the problematic photo.
I can then use `exiftool -all ""  /path/to/image.jpg` to remove all (corrupted) EXIF/IPTC/XMP tags.
Then re-add EXIF/IPTC/XMP tags using exiftool or any GUI photo management software, then the problem get solved.
