### ISSUE TITLE
[Feature] .mov playback support

### ISSUE THREAD

**Issue by dan0v** [bpatrik/pigallery2#66]
**Is your feature request related to a problem? Please describe.**
Many mobile phone cameras record videos in .mov format. Videos in this format are not even displayed in pigallery2, making some folders appear empty and being one of the greatest things holding me back from using pigallery2 as my main photo and video album service. If pigallery2 is to be a photo/video service like google photos for example, it should support commonly used formats.

**Describe the solution you'd like**
Provide video playback for .mov files (as many image and video formats as possible, really) to ensure that all photos and videos can be viewed as they should. If it is not possible to support full playback (I don't see why not for .mov), at least display these items in the interface instead of hiding them and provide the option to download the source files.

**Describe alternatives you've considered** (optional)
All .mov videos could be reencoded to mp4 using FFMPEG, but this is wasteful to both time and resources and will reduce source quality.

**Comment by bpatrik** [comment]
Hi,

Unfortunately .mov files ar not supported by any browser. Only mp4, WebM and Ogg files are supported. [More details here.](https://www.w3schools.com/html/html5_video.asp). I cannot really do anything to fix it. 

I would like to keep the app clean and simple. I feel that showing a file that the app cannot handle would cause confusion. The aim of the app is not a file browser but a photo gallery. (So not like google drive, but more like google photos) Therefore, at the moment, I would not like to list .mov files without full support. 

I'm actually planning to make it possible to reconvert original photos/videos, so that I can support more extensions (like raw  photos, .mov-s, etc..) and also my raspberry has difficulties streaming hi-res video files. So scaling down would be also good. 
(Yes it would probably come with some quality loss, but you have the same issue if you upload to YouTube. The time should be ok. I'll build a task scheduling in the app, so you can schedule the conversions to like between 1am-6am)
See more about this at issue #50.

**Comment by civita** [comment]
I would like to have converting function with ffmpeg. Regarding the .mov files, I could play them with Safari browser with minor modifying to the existing codes.

![Screen Shot 2019-05-11 at 4 28 54 AM](https://user-images.githubusercontent.com/14911217/57554966-71f21780-73a5-11e9-9e4b-79b79734482d.png)

**Comment by bpatrik** [comment]
Hi

It is relatively easy to add supported extensions to the app:
You need to add `.mov` to the folder reader, here: https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/backend/model/threading/DiskMangerWorker.ts#L25
And to the fronted here: https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/frontend/app/ui/gallery/lightbox/media/media.lightbox.gallery.component.ts#L132

ffmpeg will create a  thumbnail for you, so it will more or less work on the UI, but most likely the video wont play. 

Unfortunately, there is no straightforward way now to automatically convert `mov`-s with ffmpeg .

Patrik

**Comment by civita** [comment]
> Hi
> 
> It is relatively easy to add supported extensions to the app:
> You need to add `.mov` to the folder reader, here:
> 
> https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/backend/model/threading/DiskMangerWorker.ts#L25
> 
> 
> And to the fronted here:
> https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/frontend/app/ui/gallery/lightbox/media/media.lightbox.gallery.component.ts#L132
> 
> ffmpeg will create a thumbnail for you, so it will more or less work on the UI, but most likely the video wont play.
> 
> Unfortunately, there is no straightforward way now to automatically convert `mov`-s with ffmpeg .
> 
> Patrik

Thank you for providing the way to support `.mov` temporary. I am still using stable version (1.5.6), and the files I modified were:
`backend/routes/GalleryRouter.js`
`backend/model/threading/DiskMangerWorker.js`
`common/entities/MediaDTO.js`
Sounds like the same way to modify.

As for converting via `ffmpeg`, I am not sure how to do it simply and cleverly (I would like to make things simple as well!) Is it possible to provide "optimize" option to the `.mov` video like Plex does? Sounds like it needs another database table to record all the converted files.

**Comment by bpatrik** [comment]
Hi,

Started working on a task scheduler within the app (like crontab in Linux). Once it's ready it should be easy to do things like this.
Without that task scheduler, I dont see any easy way of converting the files.
Unfortunately I'm super-super busy with finishing my PHD, until that's done, I cant spend reasonable time on this project. sorry :/

**Comment by bobobo1618** [comment]
Actually MOV and MP4 are essentially the same thing, just with a different file extension, so it should have the same support.

Where you might run into difficulty is if the device that created the file uses an unsupported codec or puts the MOOV atom at the end of the file.

**Comment by bpatrik** [comment]
Hi,

The app now supports video transcoding with ffmpeg. 
Therefore more video formats are supported.
See the full list here: https://github.com/bpatrik/pigallery2/blob/f2faa4cd25be53dd76ce750ea05f3181652f758d/src/common/SupportedFormats.ts#L21-L39

Please note that transcoding should be done manually in the settings. (or schedule it in advanced setting mode)

Best,
Patrik

**Comment by 2ge** [comment]
just add 2 cents - there is no support MOV mentioned here: https://bpatrik.github.io/pigallery2/
