### ISSUE TITLE
[Feature] Allow language selection at installation

### ISSUE THREAD

**Issue by dan0v** [bpatrik/pigallery2#67]
**Is your feature request related to a problem? Please describe.**
Installation in any form takes a long time on weak hardware like a Raspberry Pi. Specifically, installing using the [arm32v7 docker file](https://github.com/bpatrik/pigallery2/blob/master/docker/arm32v7/debian/stretch/Dockerfile) took over an hour on my Pi 3b+ running Nextcloud. Of this total installation time, building languages took around 16 -18 minutes per language, followed by another approximately 4 minutes initializing each language.

**Describe the solution you'd like**
Seeing as users will likely use only one or two languages, allow users to select languages to install (or provide different installation scripts for each language) when installing.

**Comment by bpatrik** [comment]
Hi,

I'll look into it. (sorry, but cannot promise any deadline. Probably it will take up months. Super busy lately. :/)
In the meantime you can:
- If you delete files from the [translate folder](https://github.com/bpatrik/pigallery2/tree/master/frontend/translate) the app wont translate to that language. (Dont delete the english one, it might give an error)
- you can download a [precompiled release](https://github.com/bpatrik/pigallery2/releases/tag/1.5.6) and install that one.

In both cases you will need to download the source manually and `COPY` it to the container and not using the `git clone` in the Docker file.

**Comment by bpatrik** [comment]
The latest commit should add this feature.
Usage:
`npm run create-release -- --languages=fr,ro` to build & zip the release from source (potentially on a strong computer and then transfer release to the server)
`npm run build-prod-- --languages=fr,ro` to build it from source
