### ISSUE TITLE
Compatibility to Node.js greater V18.1

### ISSUE THREAD

**Issue by knalltuete86** [bpatrik/pigallery2#670]
**Describe the bug**
I did install PiGallery2 V1.9.0 from latest release.zip according to installation instructions. While running `npm start` at install-folder I got the following output:

> pigallery2@1.9.0 start
> node ./src/backend/index.js
> 
> node:internal/modules/cjs/loader:1078
>   throw err;
>   ^
> 
> **Error: Cannot find module 'reflect-metadata'**
> Require stack:
> - /home/horst/pigallery2/src/common/config/private/PrivateConfig.js
> - /home/horst/pigallery2/src/common/config/private/Config.js
> - /home/horst/pigallery2/src/backend/server.js
> - /home/horst/pigallery2/src/backend/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
>     at Module._load (node:internal/modules/cjs/loader:920:27)
>     at Module.require (node:internal/modules/cjs/loader:1141:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Object.<anonymous> (/home/horst/pigallery2/src/common/config/private/PrivateConfig.js:14:1)
>     at Module._compile (node:internal/modules/cjs/loader:1254:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
>     at Module._load (node:internal/modules/cjs/loader:958:12)
>     at Module.require (node:internal/modules/cjs/loader:1141:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/horst/pigallery2/src/common/config/private/PrivateConfig.js',
>     '/home/horst/pigallery2/src/common/config/private/Config.js',
>     '/home/horst/pigallery2/src/backend/server.js',
>     '/home/horst/pigallery2/src/backend/index.js'
>   ]
> }
> 
> Node.js v18.16.0

I guessed the issue is according my environment (freshly Debian Bookworm) and tried to install the missing dependencies:

`npm install reflect-metadata`

But I got the following Error:

> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'pigallery2@1.9.0',
> npm WARN EBADENGINE   required: { node: '>=12.0 <15.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }

Is there any way to get it working for Node.js greater than v18.1?
I don't like to downgrade to 15.0 as there're many deprecated packages.

Thanks!

**Comment by martadinata666** [comment]
The front page README had the install step you need, and that is a warn , doesn't really matter as long as the application work correctly. I'm on node v18.16

**Comment by knalltuete86** [comment]
Thanks for your comment. Which step do you mean? The README tells to install Node V12.x - i skipped this as I already hat V18 installed. Do you mean I have to build from source to get all the depedencies?

**Comment by martadinata666** [comment]
https://github.com/bpatrik/pigallery2#121-a-install-from-release
```
cd ~
wget https://github.com/bpatrik/pigallery2/releases/download/1.9.0/pigallery2-release.zip
unzip pigallery2-release.zip -d pigallery2
cd pigallery2
npm install
```

**Comment by knalltuete86** [comment]
Thanks again ... I did exactly this. But after your comment I worried may to miss something. So I removed everythin (`~/pigallery2`) and started again.

Everything works fine until `npm install`:

> npm ERR! code 1
> npm ERR! path /home/horst/pigallery2/node_modules/sharp
> npm ERR! command failed
> npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> npm ERR! info sharp Using cached /home/horst/.npm/_libvips/libvips-8.8.1-linux-armv7.tar.gz
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@18.16.0 | linux | arm
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/horst/pigallery2/node_modules/node-gyp/lib/configure.js:484:19)
> npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/horst/pigallery2/node_modules/node-gyp/lib/configure.js:406:16)
> npm ERR! gyp ERR! stack     at F (/home/horst/pigallery2/node_modules/which/which.js:68:16)
> npm ERR! gyp ERR! stack     at E (/home/horst/pigallery2/node_modules/which/which.js:80:29)
> npm ERR! gyp ERR! stack     at /home/horst/pigallery2/node_modules/which/which.js:89:16
> npm ERR! gyp ERR! stack     at /home/horst/pigallery2/node_modules/isexe/index.js:42:5
> npm ERR! gyp ERR! stack     at /home/horst/pigallery2/node_modules/isexe/mode.js:8:5
> npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
> npm ERR! gyp ERR! System Linux 6.2.13-sunxi
> npm ERR! gyp ERR! command "/usr/bin/node" "/home/horst/pigallery2/node_modules/.bin/node-gyp" "rebuild"
> npm ERR! gyp ERR! cwd /home/horst/pigallery2/node_modules/sharp
> npm ERR! gyp ERR! node -v v18.16.0
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok

May I missed this at the first time. In order to fix it I ran `export PYTHON="/usr/bin/python3"`. After this, I ran `npm install` again:

> npm ERR! code 1
> npm ERR! path /home/horst/pigallery2/node_modules/sharp
> npm ERR! command failed
> npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> npm ERR! info sharp Using cached /home/horst/.npm/_libvips/libvips-8.8.1-linux-armv7.tar.gz
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@18.16.0 | linux | arm
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack   File "<string>", line 1
> npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
> npm ERR! gyp ERR! stack 
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
> npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
> npm ERR! gyp ERR! stack     at Socket.emit (node:events:513:28)
> npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:322:12)
> npm ERR! gyp ERR! System Linux 6.2.13-sunxi
> npm ERR! gyp ERR! command "/usr/bin/node" "/home/horst/pigallery2/node_modules/.bin/node-gyp" "rebuild"
> npm ERR! gyp ERR! cwd /home/horst/pigallery2/node_modules/sharp
> npm ERR! gyp ERR! node -v v18.16.0
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok


After some reading I found it is may caused from an old version of `node-gyp` - so I tried to update for latest Version: `sudo npm install node-gyp@latest`. But even this ends up with an error.

I guess I have to this problem about node-gyp first, it seems not to be related to PiGallery2 at the moment ..

I will share my results. Regards

**Comment by martadinata666** [comment]
So few things to consider, try 
* release v0.9.5, it will use newers deps.
* Install `libvps-dev` from OS repo.

Essentially, it try to build `sharp` modules, and it need `libvips` that is where the problem arise. ☕

**Comment by knalltuete86** [comment]
Dear martadinata666,

thanks a lot - this solved it! Just to correct your typing error in case some other users are reading this and struggling:

> - release v**1**.9.5, it will use newers deps.
> - Install libv**i**ps-dev from OS repo.

by the way: the README may have to be updated to refer to the latest Release file.

Kind Regards

**Comment by knalltuete86** [comment]
Closed
