### ISSUE TITLE
Gallery sorting

### ISSUE THREAD

**Issue by sugatam** [bpatrik/pigallery2#675]
To simulate google photo's behavior, I have my galleries sorted in descending date order, and then using a simple script I set the mtime of the folder to the most recent CreateDate from the photos' EXIF. Unfortunately, the gallery sort code uses the most recent of ctime and mtime in its "calcLastModified" function, and one cannot set ctime explicitly, so this sort mode is not very useful (to me). I have worked around it via a local mod, but it would be great to have an official fix - either by changing the sort like I have, or to have an additional option to sort by mtime only.

**Comment by bpatrik** [comment]
Last commit should enable this. You need to enable it in the settings for now
