### ISSUE TITLE
admin user recreation on restart (1.9.5.)

### ISSUE THREAD

**Issue by knalltuete86** [bpatrik/pigallery2#677]
**Describe the bug**

Message "You are using the default admin/admin user/password, please change or remove it." and "Restart the server to close this message".

Default admin user has been deleted before (does not appear in admin panel anymore). After restart, default admin user reappears.

It seem to be the same as #408 which has been marked as fixed for this version already?

**Environment (please complete the following information):**
 - OS: Debian Bookworm
 - Browser: Vivaldi

**Used app version**:
- release 1.9.5

**Comment by bpatrik** [comment]
Can you check what is in you `config.json` for `"enforcedUsers"` ? 
You can also try to look at enforced user from UI, but config.json is the authoritative source of truth,

**Comment by knalltuete86** [comment]
Dear @bpatrik 
the enforcedUsers Object from `config.json` looks as follows:

```
"enforcedUsers": [
            {
                "name": "horst",
                "role": "Admin",
                "//[password]": [
                    "Unencrypted, temporary password. App will encrypt it and delete this."
                ],
                "password": "",
                "encryptedPassword": "XXX",
                "encrypted": true
            },
            {
                "name": "nadine",
                "role": "User",
                "//[password]": [
                    "Unencrypted, temporary password. App will encrypt it and delete this."
                ],
                "password": "",
                "encryptedPassword": "XXX",
                "encrypted": true
            }
        ]
    }
```
Meanwhile I found that I often cannot delete anything like e.g. albums, users - it just happens nothing while hitting the Delete-Button.
But there's neither a error in the development console in the browser nor some notification in the logs.

Regards

**Comment by bpatrik** [comment]
The problem was that the app could not load the config. The latest push should fix it. (should be available in 40 mins in the niglty build)

**Comment by knalltuete86** [comment]
Thanks, it's working now!
