### ISSUE TITLE
Orientation is not fixed if installed as app (PWA)

### ISSUE THREAD

**Issue by migumigu** [bpatrik/pigallery2#681]
我有用手机浏览的习惯，目前，手机的浏览器可以支持将页面添加到桌面，就像一个APP一样使用。这样很方便。
不过，有一点困扰着我，通过桌面直接打开的话，手机陀螺仪就会生效，即使我是锁定屏幕的情况下。
我可能是躺在床上使用，但它就会自动变成横屏模式。苹果手机和安卓手机都存在此情况。
从浏览器访问进入，没有这个问题，但不方便，需要好几步才能访问pigallery2页面。
如果这个能解决的话，就太感谢了。它就可以像一个手机APP一样，在桌面占1个独立的位置。🙏🏻

I have the habit of browsing on mobile phones. At present, the browser of mobile phones can support adding pages to the desktop, which can be used like an APP. This is very convenient.
However, there is one thing that bothers me. If you open it directly through the desktop, the phone's gyroscope will take effect, even if I lock the screen.
I may be using it in bed, but it will automatically go to landscape mode.
Accessing from the browser does not have this problem, but it is inconvenient. It takes several steps to access the pigallery2 page.
It would be very grateful if this could be resolved. It can occupy an independent position on the desktop just like a mobile app. 🙏🏻

**Comment by bpatrik** [comment]
Just to confirm, this is the issue:

1. You open the app in chrome
2. click settings -> add to home screen (as PWA application)
3. Open the app from the homescreen
4. Orientation lock does not work

I can reproduce the issue on Pixel 6

This is a platform and more likely Chrome bug.
Here is a similar thread for that: https://github.com/photoprism/photoprism/issues/3413

There is not much I can do on the App side.

**Comment by bpatrik** [comment]
Having a second look, would setting orientation to natural work here? https://stackoverflow.com/questions/68522783/web-app-manifest-orientation-property-what-is-the-difference-between-its-proper

**Comment by bpatrik** [comment]
Or it should be just deleted like photoprism do it: https://demo.photoprism.app/manifest.json

And then the app should be deleted and reinstalled

**Comment by bpatrik** [comment]
Removed the orientation lock. I dont think I can do more for this topick, apart from waiting for chrome to fix it.

**Comment by bpatrik** [comment]
I did some change.  It properly works now on my samsung tablet but only patrially on my pixel phone.


I guess that is the best we can have.

**Comment by migumigu** [comment]
You're really amazing
