### ISSUE TITLE
Feature: Send (Mail,DM) top pick photos from the past

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#683]
# Main effort
I want to improve engagement and memory discovery in the app. This feature falls into this category

# Vision of this Feature
As a family we use Facebook Messenger to communicate. I would like pigallery2 to send every Monday 10AM a set of photos that happened on the same week, but years earlier. 

# Prerequisite
Nothing by now. It was blocked on #660.

# Design

## Getting the photos
I will create a new Job that can run periodically. Users can set a search query, sort order and number of photos/videos to pick.
(It will use the same logic as random photo in the background, but it will allow sorting and more than just one photo)

## Sending the photos
This is the tricky part. I will def. support sending over e-mail and I would like to at least support FB Messenger. I understand that everyone uses different way of messages (IMessage, WhatsApp, Telegram, etc.). I will try to look if there is any free and simple messenger hub that offers an API to send photos to group chats on a given platform. If anyone know one, please don't hesitate to share. 
If such easy and common hub does not exists, I will just support e-mail and FB Messenger and try to make the architecture easy enough, so others can send a PR for other services.

**Comment by ltctceplrm** [comment]
> I will try to look if there is any free and simple messenger hub that offers an API to send photos to group chats on a given platform. If anyone know one, please don't hesitate to share.

The only such hub that I'm aware of (and have tried myself) is [Apprise](https://github.com/caronc/apprise/wiki), it has email support as well as several chat apps like Telegram but I don't see Facebook Messenger on the list unfortunately so you'd still have to add that

**Comment by bpatrik** [comment]
So the e-mail sending part I was able to create, but that is only half success. 

Thanks for the Apprise, but its not necessary what I'm looking for. 1) i would prefer not to add python dependency to the app to keep is simple. 2) I wanted something I send a HTTP request to and forwards the message to the right place. Like an external messaging hub.

I tried to understand FB messenger and it seems that officially it is not possible to send messages to a group. Bot can only reply on pages: https://stackoverflow.com/questions/53598526/facebook-graph-api-how-to-send-chat-message-to-all-members-of-a-group

**Comment by bpatrik** [comment]
Having a second though. 
I will probably hack the FB Messanger call in with: https://www.npmjs.com/package/facebook-chat-api, https://www.npmjs.com/package/luna-messenger-api and tag the feature as experimental and dangerous in the short term (if these packages even work)

In the long term, I will try to come up with some add-on methods, where every can implement their own messaging method.

**Comment by bpatrik** [comment]
kinda works. Good enough for this release. UX can be improved as it is a bit hard to use. But it will evolve as I use it more often.

**Comment by knalltuete86** [comment]
Great Feature! I just tested on 2.0.0 and it works well so far!

Just one question: Is there any template file or something similiar to modify the Mail-Design for my needs?

**Comment by bpatrik** [comment]
There is no such option for now.

I'm working on extensions, where you can implement your own "messenger"
logic. You can do whatever you want there. That would be a bit more complex
than just supporting a mail design, but also more flexible.

**Comment by iball** [comment]
Some of us are running our own email bridge locked down to specific IP addresses with no authentication required.
Any way to mod it so we can save the connection info *without* requiring a password since the bridge doesn't require it?
