### ISSUE TITLE
Suggestion: Search for photos with a particular rating (xmp:rating)

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#69]
I would like to suggest to add a search for a certain photo rating to the search box. Ratings are usually done with 0-5 stars and written down to the xmp metadata (xmp:MicrosoftPhoto:Rating or xmp:Rating).
Example query: Search for photos in the directory Puerto Rico which have a 4 stars rating: 
"Puerto Rico ****" 
or alternatively 
"Puerto Rico *4"

**Comment by bpatrik** [comment]
Hi 
Thank you for the suggestion.
I can add this once I'm touching the search as mentioned in #58.
(but again: sorry no deadly promise, probably it will take up several months, until I get there)

Best,
Patrik

**Comment by bpatrik** [comment]
Pushed a few changes to the advanced search #58. It should support rating now.

**Comment by bpatrik** [comment]
Closing this as it is supported now.
