### ISSUE TITLE
Question: How to make a systemd service with pigallery2?

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#70]
Hi there,
In order to make a systemd service on my Debain 9 NAS with pigallery2 I tried to use the pm2 package according to the[ tutorial of digitalocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-debian-9). Unfortunately, I failed. I must admit that the node npm world is rather new for me. However I tried "pm2 start node /my_directory/pigallery2/backend/index.js" but it threw errors. Perhaps someone could offer me a hint or a more suitable tutorial? Thanks in advance.

**Comment by bpatrik** [comment]
Hi,

Unfortunately pigallery does not work with pm2. (PM2 is basically an instance/process manager for node, and pigallery manages its own instances).

There was an issue (#42) about the same topic earlier. You can try reading that one:
https://github.com/bpatrik/pigallery2/issues/42#issuecomment-458340945.

Short: I recommend running the app with systemctl on port like 3000 and using nginx as reverse proxy for that.

**Comment by wechsler42** [comment]
Thanks Patrik for the hint with #42 , I will try that. Just one question towards the reverse proxy. I thought I would skip that part due to the fact that my pigallery use case is restricted to to a LAN, so no WAN/Internet connections to pigaller2 are intentend. So is there any need of pigallery2 for a reverse  proxy besides anonymisation, load balancing, etc?

**Comment by bpatrik** [comment]
Hi
As far as I understand nginx helps for:
 * decreasing the load on node (well nginx is a heavily optimized app, while node runs javascript)
 * a recommended way of having HTTPs
 * hides your node, so probably better for security purposes

But if you only run it LAN for 1-2 users. you don't really need nginx.

**Comment by wechsler42** [comment]
Thanks Patrik for clarification.
