### ISSUE TITLE
Navbar link wrong when directory name occurs more than once

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#700]
I have a directory structure in which names are sometimes used a few times in different places:

![Screenshot from 2023-08-25 12-13-08](https://github.com/bpatrik/pigallery2/assets/4752390/f31d197b-e8bd-497d-84a3-b625e8f9e425)

Now the breadcrumb links go to:

Home: URL/gallery/%2F
Maarten: URL/gallery/Maarten
2000: URL/gallery/Maarten%2F2000
2000-12-07 Diversen: URL/gallery/Maarten%2F2000%2F2000-12-07%20Diversen
**Maarten: URL/gallery/Maarten**
Maarten: (not a link)

So the secont 'Maarten' link goes to /gallery/Maarten while I would expect something like /gallery/Maarten%2F2000%2F2000-12-07%20Diversen%2FMaarten

I'm using 1.9.6 docker-nightly

**Comment by bpatrik** [comment]
Thanks, the latest push should fix this.
