### ISSUE TITLE
Problem on display of the GPS track

### ISSUE THREAD

**Issue by lythandas** [bpatrik/pigallery2#703]
**Describe the bug**

There's a strange issue in the displaying of the GPS track, it shows a direct path to the starting point. It should be added that this gpx file is a concatenation of several paths, and it appear that if a path's ending point isn't the same as the start point, it will show a path to the starting point of the complete path.

**Screenshots (optional)**
![image](https://github.com/bpatrik/pigallery2/assets/90504445/1b78b2cf-c4d7-4a5c-b5f1-99877431560c)
the should be only one path from Faroe to Iceland on this map

used path 
[islande.zip](https://github.com/bpatrik/pigallery2/files/12446093/islande.zip)
The issue doesn't show on any GPS editing software

**Environment (please complete the following information):**
 - OS: Docker
 - Browser : brave and firefox

**Used app version**:
- docker-nightly-bullseye

**Comment by bpatrik** [comment]
That is a feature. The app draws an arch of two points are far away from
eachother. You can costumize it in tbe settings

-- Sorry for being brief, sent from my phone.

**Comment by lythandas** [comment]
Yes I saw that. The problem isn't the arched path, it's that there shouldn't be a path at all at that place.
Here's how it shows without the arch, on v1.9.5
![image](https://github.com/bpatrik/pigallery2/assets/90504445/ec1b7325-fc7c-4b09-9a55-ff5dd46c6905)
and here how it shows on any GPS editing software.
![image](https://github.com/bpatrik/pigallery2/assets/90504445/d25be2c1-3e10-4151-8555-9d2c8cff29af)

**Comment by bpatrik** [comment]
That is also a gpx compression issue. You can disable it while it's broken.
( you might need to delete the compressed files in the temp folder)

-- Sorry for being brief, sent from my phone.

**Comment by lsaintier** [comment]
Hey again. 

I tried disabling the GPX compression, and used the new jobs to delete the compressed files and clean the temp folder. 
However, now the map either doesn't load at all or makes the tab crash after loading for +30s.
I also tried disabling an re-enabling gpx handling in the parameters and resetted the db, but still no difference. 

I also tried disabling the GPX compression in v1.9.5 and I still have the problem.

**Comment by bpatrik** [comment]
Can you please check server logs and send a gpx track that causes the issue.

**Comment by lythandas** [comment]
Sorry, last comment was from my work account. 
The gpx track is zipped and available in my first comment, as for server logs, here's all that I have : 

```
8/28/2023, 10:24:06 AM[WARN_] Handled error:
ErrorDTO {
  code: 5,
  message: 'credentials not found during login',
  details: TypeError: Cannot read properties of null (reading 'password')
      at UserManager.findOne (/app/src/backend/model/database/UserManager.js:13:81)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async login (/app/src/backend/middlewares/user/AuthenticationMWs.js:148:46),
  request: { method: '', url: '' },
  detailsStr: "TypeError: Cannot read properties of null (reading 'password')"
}
/app/src/backend/model/fileprocessing/GPXProcessing.js:82
            const timeDelta = (Date.parse(list[i].time[0]) - Date.parse(list[i - 1].time[0])); // mill sec.
                                                      ^

TypeError: Cannot read properties of undefined (reading '0')
    at gpxEntryFilter (/app/src/backend/model/fileprocessing/GPXProcessing.js:82:55)
    at Array.filter (<anonymous>)
    at GPXProcessing.compressGPX (/app/src/backend/model/fileprocessing/GPXProcessing.js:87:51)
    at async compressGPX (/app/src/backend/middlewares/MetaFileMWs.js:24:30)

Node.js v18.13.0
```

**Comment by bpatrik** [comment]
The last commit should fix. 

yes on v1.9.5 the compression does not work and fails as fix was done later.

**Comment by lythandas** [comment]
Hey again, I confirm this is working great since your last commit. Thank you very much ! 

However I cannot get rid of the bend now. It ends up breaking the browser when opening the map or just not working. I tried to remove the compressed GPX files and nothing changed. When the map is broken, I have to remove config.json. 
I setup a test instance with only the gpx file and it behaved the same. Then again, nothing showed in the logs.

**Comment by bpatrik** [comment]
You can disable bending if you put this number to a high value: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/af8bd5fe-cd83-4b51-8053-544501699072)

Although the issue should not be with the bending. It only adds a few more points. I think your problem that your gpx file is just huge for the app. Yours is 6MB. I usually have only a few hundred KB.
You can try making the compression stronger by making these numbers bigger: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/1386f0bf-087d-4827-9391-38a1e5c6532a)

You wont see anything in the logs because the issue is in the browser as it cannot render the file. The server works without an issue.

**Comment by lythandas** [comment]
Hello, I'm sorry I misunderstood those values, and put smaller values instead of higher, that's why it was always crashing... 
It's all working great now and I'm down to a 1Mb file with heavier compression. 
The bend is also gone now, I just had to empty the browser cache after setting a high value. What is the unit of the bend value ? 

Thank you again for your time
