### ISSUE TITLE
Album Cover Sorting options documentation

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#709]
This might be WIP, but the new  Album Cover Sorting options are a bit technical:

`[{"method":30,"ascending":false},{"method":20,"ascending":false},{"method":40,"ascending":false}]`

What are all the options? What do they mean :)

**Screenshots (optional)**
![image](https://github.com/bpatrik/pigallery2/assets/4752390/85f2b48b-e1ca-4ed4-8ed2-e1f44d3a5b06)

**Environment (please complete the following information):**
 - OS: Docker container on Debian / LMDE client
 - Browser: Chromium

**Used app version**:

- docker-nightly

**Comment by bpatrik** [comment]
should be already fixed.

**Comment by mrtnbr** [comment]
I use the latest version I can find (nightly/edge bpatrik/pigallery2:nightly-debian-buster), built today. Must be something in my setup then. I have done a few things:

- removed any relevant settings from the Docker compose environment
- stop container
- deleted config.json
- start container

With a fresh config file the admin page stays the same. 

This is the (I think) relevant part from my new config.json:

'
    "//[AlbumCover]": [
        "Specify a search query and sorting that the app can use to pick the best photo for an album and folder cover. There is no way to manually pick folder and album cover in the app. You can tag some of your photos with 'cover' and set that as search query or rate them to 5 and set sorting to descending by rating."
    ],
    "AlbumCover": {
        "//[SearchQuery]": [
            "Filters the sub-folders with this search query. If filter results no photo, the app will search again without the filter."
        ],
        "SearchQuery": {
            "type": 100,
            "text": ""
        },
        "//[Sorting]": [
            "If multiple cover is available sorts them by these methods and selects the first one."
        ],
        "Sorting": [
            {
                "method": "Rating",
                "ascending": false
            },
            {
                "method": "Date",
                "ascending": false
            },
            {
                "method": "PersonCount",
                "ascending": false
            }
        ]
    },
'

**Comment by bpatrik** [comment]
Indeed you are right. Obfuscation broke my reflection code. Latest commit should fix it. 

FYI: I renamed nightly to edge today. Same thing just different name.

**Comment by mrtnbr** [comment]
Thank you! And, thank you for all the improvements the last few weeks!
