### ISSUE TITLE
Nightly build does not fetch faces

### ISSUE THREAD

**Issue by ldy985** [bpatrik/pigallery2#713]
**Describe the bug**

The code on master currently disables face previews from rendering. I believe it is some debug code accidentally pushed :)
See https://github.com/bpatrik/pigallery2/blob/master/src/frontend/app/ui/faces/face/face.component.html#L9-L14
Part of https://github.com/bpatrik/pigallery2/issues/587

Also, thank you, very much for this project! I will be looking more into it as it fits very well with some use-cases I have.

**Comment by bpatrik** [comment]
Thanks for reporting.Yeah I know about the issue.

-- Sorry for being brief, sent from my phone.

**Comment by bpatrik** [comment]
Ah you also found the culprit:D thanks!

-- Sorry for being brief, sent from my phone.
