### ISSUE TITLE
Feature: add option to change grid size

### ISSUE THREAD

**Issue by bpatrik** [bpatrik/pigallery2#716]
Tracking bug for grid size changes:

![kép](https://github.com/bpatrik/pigallery2/assets/7512182/6e2a0069-3171-4219-b7f5-371deff10c7f)

User should be able to change photo and video sizes on the grid.

**Comment by bpatrik** [comment]
The icons are not the best. Asked a FR, maybe they add better onces: https://github.com/ionic-team/ionicons/issues/1277

**Comment by mrtnbr** [comment]
I'm on the latest edge version, the option is visible in the NavBar, if I change the option the icon changes also, but there is no change in the actual grid. Is this already working or still in development?

**Comment by bpatrik** [comment]
Yes it should work. Can you reproduce on the demo page.

Please send a screenshot of the issue

-- Sorry for being brief, sent from my phone.

**Comment by mrtnbr** [comment]
Right, figured it out. I  tried it on a page only containing Albums, but this option is for previews.
