### ISSUE TITLE
Maps display weird on directories with only GPX file

### ISSUE THREAD

**Issue by mblythe86** [bpatrik/pigallery2#718]
**Describe the bug**

In some of my directories, I have a `*.gpx` file with a GPS track, but none of the images in that directory are GPS-tagged.  The Maps still work, but not as well as when there are GPS-tagged pics.  On the gallery view, there's no thumbtack on the map, and when clicking through to the map, it's zoomed out to the whole world, instead of zoomed to fit.  See the screenshots below...

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

Working directory with both GPX and GPS-tagged photos:
![image](https://github.com/bpatrik/pigallery2/assets/751675/19e11f17-501c-462e-854e-8539432489c4)
![image](https://github.com/bpatrik/pigallery2/assets/751675/5eb62564-326a-43da-b881-9fc460dffe80)

Oddly-behaving directory with only GPX file:
![image](https://github.com/bpatrik/pigallery2/assets/751675/4977c735-1909-45bc-b5fc-4acead5ad310)
![image](https://github.com/bpatrik/pigallery2/assets/751675/bb7e250e-9ec8-4c21-8b90-c4b577d9ad1e)

When I manually zoom in, it shows the track from the GPX fine:
![image](https://github.com/bpatrik/pigallery2/assets/751675/40661e20-517e-4fc2-87f9-6fc5ab510311)
...but I don't want to have to zoom in.

**Server logs (optional)**

N/A

**Environment (please complete the following information):**
 - server OS: Ubuntu 22.04.3 LTS
 - Browser: firefox 117.0 on Ubuntu 22.04.3 LTS

**Used app version**:
```
> sudo docker images
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
bpatrik/pigallery2      latest    43b6c3bfc6f4   8 months ago   730MB
```

**Comment by bpatrik** [comment]
The small map does not have info about the GPX tracks, that cannot show it, but the big map can fit the bounds better.

**Comment by bpatrik** [comment]
Last commit should fix this. (not the small map, that requires more refactoring)
