### ISSUE TITLE
Document existing API

### ISSUE THREAD

**Issue by mblythe86** [bpatrik/pigallery2#719]
**Is your feature request related to a problem? Please describe.**

I'm trying to integrate pigallery2 with my existing photo management (I use digiKam to rate, label, categorize, recognize faces, etc.).  I find that I'm writing scripts to try to automate syncing data from digiKam into pigallery2 (e.g. only directories with category=Public are visible to pigallery2, set thumbnails, etc).  For several of the things that I'm doing, I'm hacking on the pigallery2 database directly.  It's possible that there are API methods I could use to accomplish the same things.

**Describe the solution you'd like**

Could you document the existing API methods so that power-users can utilize them?

**Describe alternatives you've considered** (optional)

Alternatively, documenting the database schema would be helpful.  e.g. what does the `validPreview` column in the `directory_entity` table do, and how is it used?

-----------
...a quick aside...
I know I'm commenting and filing a bunch of issues recently.  Sorry about that, I'm just really excited about this software.  It's great stuff, and fits with what I'm looking for like 95% (which is far better than any of the other self-hosted photo gallery projects I've tried out).  I'm just trying to see what we can do about that last 5% that (in my opinion) would make this software perfection.

**Comment by bpatrik** [comment]
Here you will find answers for some of your questions: https://github.com/bpatrik/pigallery2/discussions/738

**Comment by mblythe86** [comment]
Relevant portion of #738:

> I would like to keep the developer velocity as high as possible. This means there are certain features that I just can't support. I prefer to move fast and break things. In the end that is more fun than writing docs :)
> 
> I'm not adding proper api documentation.
> 
>     The best I can do is code comments.

Makes sense.  I think #743 would probably accomplish the goals I have.

With that, I'm OK to close this issue.
