### ISSUE TITLE
Some GPX files aren't shown

### ISSUE THREAD

**Issue by hajo62** [bpatrik/pigallery2#723]
I have some gpx-files exported from Garmin basecamp. Some are shown, others not.
I'm running a v1.9.6-nightly build

```
9/17/2023, 12:43:22 PM[WARN_] Handled error:
ErrorDTO {
  code: 35,
  message: 'Error during compressingGPX: /app/data/images/Tag 03.GPX',
  details: TypeError: Cannot read properties of undefined (reading '0')
      at gpxEntryFilter (/app/src/backend/model/fileprocessing/GPXProcessing.js:84:59)
      at Array.filter (<anonymous>)
      at GPXProcessing.compressGPX (/app/src/backend/model/fileprocessing/GPXProcessing.js:108:49)
      at async compressGPX (/app/src/backend/middlewares/MetaFileMWs.js:26:34),
  request: { method: '', url: '' },
  detailsStr: "TypeError: Cannot read properties of undefined (reading '0')"
}
```

**Comment by hajo62** [comment]
[Archive.zip](https://github.com/bpatrik/pigallery2/files/12642852/Archive.zip)

Tag 02 is shown, Tag 03 not.

**Comment by bpatrik** [comment]
I'm seeing this:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/30af0369-7069-4579-b771-5a13390673d4)
I made this change to 02 so it shows up in a different color:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/7cba9801-ee6b-4d09-9926-ca834fc1b750)


Is this the expected path?
Are you using edge?

**Comment by bpatrik** [comment]
I guess its a duplicate of #703 and already fixed.

**Comment by hajo62** [comment]
Firefox 117 on Mac.
Yes, should look something like that.

Shall I pull a nightly build? If

**Comment by bpatrik** [comment]
It's called 'edge' now. As the build is actually built from the main branch
all the time, not only during the nigh. (Note the docker tag also changed)
Please use that for future bugreports. It takes me 30min to figure out that
an issue is already potential fixed. I can use that time to fix an other
big.

-- Sorry for being brief, sent from my phone.

**Comment by hajo62** [comment]
duplicate of https://github.com/bpatrik/pigallery2/issues/703
