### ISSUE TITLE
Update Dutch translation before release v2.0.0

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#726]
I wish to update the Dutch translation of pigallery2 before the release of v2.0.0.

**Comment by bpatrik** [comment]
Sounds good. Thank you. Please go ahead.

You only need to update the https://github.com/bpatrik/pigallery2/blob/master/src/frontend/translate/messages.nl.xlf
It should already contain all the text available in the app.
If you want to do it the easy way, you can try github's built in developer idea.

**Comment by bpatrik** [comment]
Did you have any progress with this? I'm planing to hit that release button next week :)

TBH, I think its enough to only translate gallery UI. I think translating the settings does not add much value. Unfortunately, its not easy to tell which one if gallery witch one is settings.

**Comment by mrtnbr** [comment]
Yes, I have started work and I hope to finish it tonight or tomorrow!

**Comment by mrtnbr** [comment]
https://github.com/bpatrik/pigallery2/pull/737
