### ISSUE TITLE
Suggestion: Allow choice between markers and thumbnails representaion of photos with GPS coordinates on maps

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#73]
Hi there,
at the moment photos with GPS coordinates are represented on a map as thumbnails. I would suggest that there is a choice to represent geotagged photos as thumbnails or as markers. The markers could be blue or red and when I click on a marker it should open the thumbnail of the corresponding photo and if possible display  some more meta information.
The ratio for this is to speed up the response time. So I have image directories with ~800 geo tagged photos and it takes a bit of time until the map with all the thumbnails is loaded. Pigallery2 seems somewhat stalled although I work on AMD64 NAS.

**Comment by bpatrik** [comment]
Hi,

As far as I've experienced the main issue here is not with the server, but with the client.
I also see that if I have too many photos (>300) in one folder, it start slowing down. A solution to it is actually to group the photos together.
I was considering solving it, but haven't got the time for that yet.

Patrik

**Comment by bpatrik** [comment]
Hi,

I've made a config (visible in advanced mode) to disable map thumbnail icons and use the default pin markers instead.

P
