### ISSUE TITLE
Implement folder sorting by date

### ISSUE THREAD

**Issue by krifpvlic** [bpatrik/pigallery2#730]
**Is your feature request related to a problem? Please describe.**
I have set up a pigallery2 instance with home consisting of only folders and the folders containing images. Every folder has images taken within a specific day or 2 days, not overlapping. The selected sorting mechanism is date ascending. While the pictures inside the folders are being sorted this way, the folders in home are sorted by name, not date. 

**Describe the solution you'd like**
Would it be possible for folders to be sorted by date as well?

**Describe alternatives you've considered**
Starting the folder name with the date, which is functional but not ideal.

**Comment by bpatrik** [comment]
Hi,

There is a settings to enable that. Also look for previous issues for
explanation

Patrik

-- Sorry for being brief, sent from my phone.

**Comment by kfpv** [comment]
I didn't notice it was there, thank you.
