### ISSUE TITLE
Suggestion: add zoom in and zoom out overlay to map

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#74]
this could be realized via "+" and  "-" symbols or some sort of magnifying glass at the left or right border of the map.

**Comment by bpatrik** [comment]
Hi,

Thanks. I'll consider adding it in the future. 

Patrik

**Comment by bpatrik** [comment]
Hi,

I've added this feature with the latest commit. It will be part of the release (1.7)

P
