### ISSUE TITLE
Suggestion: add layer selector box to map to switch to satellite view

### ISSUE THREAD

**Issue by wechsler42** [bpatrik/pigallery2#75]
Hi there,
it would be a nice addition to the map functionality when there would be a map layer selector box where one could switch to a satellite map like it is done here:
![image](https://user-images.githubusercontent.com/19371424/58964577-71d01680-87af-11e9-9779-6f1a4b654b1e.png)
and 
![image](https://user-images.githubusercontent.com/19371424/58964721-a3e17880-87af-11e9-8c58-1c91d2b30a30.png)
and finally an ESRI satellite map
![image](https://user-images.githubusercontent.com/19371424/58964949-089cd300-87b0-11e9-876f-d4560b3abf34.png)

**Comment by bpatrik** [comment]
Hi 

Thanks for the suggestion. I might add this feature in the future. 

Patrik

**Comment by bpatrik** [comment]
Hi,

I've added this feature with the latest commit. It will be part of the release (1.7)
It only works with MapBox or custom tiles. I could not find any (registration) free tile provider for satellite map.

P
