### ISSUE TITLE
Pigallery2 deleted all media and server files after trying to force libaom-av1(?)

### ISSUE THREAD

**Issue by minchka** [bpatrik/pigallery2#755]
Trying to implement video encoding leads to all media files and the entire database gets deleted, running the docker file again opens a fresh server. 

I tried to force ffmpeg in Pigallery2 to use libaom-av1 encoding but im not sure if this caused the issue.

[Docker Log]
[pigallery.txt](https://github.com/bpatrik/pigallery2/files/13269075/pigallery.txt)

[Server]
OS: Debian GNU/Linux 12 (bookworm) aarch64 
Host: Raspberry Pi 3 Model B Rev 1.2 
Kernel: 6.1.0-rpi4-rpi-v8 

[Client]
OS: elementary OS 7.1 Horus x86_64  
Host: Aspire A515-51G V1.17 
Kernel: 6.2.0-34-generic 

Mozilla Firefox x64 119, Flatpak 1.0 

-Docker version 24.0.7, build afdd53b
- release v2.0.0

**Comment by bpatrik** [comment]
I assume just the temp video files got deleted after running the cleanup
job .

Database reset might come from that the app did not have access to the
gallery itself (like hdd failure, unmount,etc) so it dropped from the db.

Otherwise I would need more info to provide any more help

-- Sorry for being brief, sent from my phone.

**Comment by minchka** [comment]
Im a novice so please tell me what i need to do to help.

**Comment by bpatrik** [comment]
I would look into the server logs with full debug logs

-- Sorry for being brief, sent from my phone.

**Comment by minchka** [comment]
Where are the logs stored? I will change the ENV and try to replicate the problem since i suppose there are no logs now.

**Comment by bpatrik** [comment]
They are printed to std output.

**Comment by bpatrik** [comment]
Ah I did not see in mail that you updated your answer. 

Great to hear that you were able to fix it!
I will close this issue for now. Feel free to reopen.
