### ISSUE TITLE
Showing both short and long captions in the sidebar

### ISSUE THREAD

**Issue by nk9** [bpatrik/pigallery2#760]
### Is your feature request related to a problem? Please describe.
I have used digiKam to add both titles and captions to a bunch of photos. The digiKam UI looks like this:

<img width="384" alt="image" src="https://github.com/bpatrik/pigallery2/assets/3646730/0caeb63b-0d04-423c-b6fc-91070ba60cc7">

And according to https://jimpl.com/, it produces EXIF output like this:

Field | Value
-- | --
Title | Baby Olga
UserComment | Age 6 months
Caption | Baby Olga
Caption-Abstract | Age 6 months

Initially, neither of these fields were visible in pG2. Then I turned on "Caption first naming", and now I can see the "UserComment" or "Caption-Abstract" string as an overlay in the UI:

<img width="769" alt="image" src="https://github.com/bpatrik/pigallery2/assets/3646730/03c8e270-634e-4365-b534-9253a49d2e03">

But the "Title"/"Caption" is still missing. And to be honest, the "title" is what I'd probably expect to see as an overlay, with the longer caption visible in the metadata sidebar if a user opens it. The [IPTC spec says](https://iptc.org/std/photometadata/specification/mapping/iptc-pmd-newsmlg2.html) that, despite the misleading suffix "-Abstract," this is the "Description" field. So it's where I'd expect to see longer text associated with the image, vs the short, pithy "Title."

### Describe the solution you'd like
I would expect both the "title" and the "caption" (as named by digiKam, whichever non-duplicative fields these map to) to be visible in the metadata sidebar. This seems pretty obvious to me, to the point that I would argue that the current behavior could be considered broken. Even if one of the two caption fields is available in that potentially hard-to-read and definitely-not-selectable overlay, I'd still expect both to be visible and selectable in the sidebar. (If a photo doesn't have any of these fields, then I wouldn't expect them to show in the sidebar.)

Here's [more info](https://www.iptc.org/std/photometadata/documentation/userguide/#_natural_language_free_text_descriptions) on how IPTC expects these fields to be used. It turns out what I'm imagining is actually the [Headline](https://www.iptc.org/std/photometadata/documentation/userguide/#_headline) field, *not* the [Title](https://www.iptc.org/std/photometadata/documentation/userguide/#_title). However, this seems to be [a very longstanding issue](https://mail.kde.org/pipermail/digikam-users/2012-November/017031.html) with digiKam, and arguably other DAMs. So perhaps the spec will never be properly implemented. I have tried to get DK to write its "Title" to the suggested `Xmp.photoshop.Headline` field, but it's not working so… 🤷 

I would point out that my preferred behavior would neatly solve the issue raised in #524.

### Describe other solutions you've considered
I suppose it would be possible to add some kind of setting or template structure to let users modify the metadata sidebar. But that strikes me as more trouble than its worth. The data is there; pG2 should be showing it.

### Test image
https://drive.google.com/file/d/10Y33gSFUX8qcefeMRK5ebbYpW_hqmxli/view?usp=sharing

**Comment by nk9** [comment]
A bit more on headlines vs titles:

DublinCore seems to expect that the [`Xmp.dc.title` field](https://exiv2.org/tags-xmp-dc.html), which IS being written by DK, is a localized "name by which the resource is formally known". If you think about it like an artwork, then this could be the considered the equivalent of the headline; it's the work's title ("Afghan Girl", "Niña afgana"), not e.g. its unlocalized filename ("afghan_girl.jpg", that's the "Identifier").

So I guess I'm going to stick with this as the location for the pithiest summary of how to refer to the image. This really seems like it should be the tag presented to the viewer as the overlay at the top of the image. Apart from anything else, a long caption could easily interfere with actually viewing the image. I don't think there's a way to hide the caption overlay right now? Plus, as above: it's unselectable.

**Comment by nk9** [comment]
I'm working on trying to implement my solution. I've gotten a development build of pG2 running on my system, and identified where to place this [in the frontend](https://github.com/bpatrik/pigallery2/blob/master/src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.html). I also see that both the title and the caption are already being extracted by iptcParser, because both `object_name` and `caption` are in the field map.

The problem I'm running into is how to add this new value to the metadata so that it can be reflected in the UI. When I add a `title` text column to `MediaMetadataEntity`, I get:

```
17/11/2023, 01:12:32[WARN_] Handled error:
ErrorDTO {
  code: 31,
  message: 'Error during listing the directory',
  details: SqliteError: no such column: media.metadataTitle
      at Database.prepare (/Users/nick/Projects/pigallery2/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
      at BetterSqlite3QueryRunner.getStmt (/Users/nick/Projects/pigallery2/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:37:43)
      at async BetterSqlite3QueryRunner.query (/Users/nick/Projects/pigallery2/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:74:22)
      at async SelectQueryBuilder.loadRawResults (/Users/nick/Projects/pigallery2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2157:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/Users/nick/Projects/pigallery2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2013:26)
      at async SelectQueryBuilder.getRawAndEntities (/Users/nick/Projects/pigallery2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:681:29)
      at async SelectQueryBuilder.getOne (/Users/nick/Projects/pigallery2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:708:25)
      at async GalleryManager.getParentDirFromId (/Users/nick/Projects/pigallery2/src/backend/model/database/GalleryManager.js:257:21)
      at async GalleryManager.listDirectory (/Users/nick/Projects/pigallery2/src/backend/model/database/GalleryManager.js:85:20)
      at async listDirectory (/Users/nick/Projects/pigallery2/src/backend/middlewares/GalleryMWs.js:35:31) {
    code: 'SQLITE_ERROR'
  },
  request: { method: '', url: '' }
}
```

This looks like a DB-schema-out-of-date error to me, but I have never used Angular or TypeORM, so I'm not sure how to resolve this. I also don't know where the DB is stored, so I can't just blow it away (although having a seamless migration path is of course essential for a finished PR).

I'd appreciate a pointer. I can commit some code to show the problem tomorrow if necessary, but thought I'd ask first in case this there's an easy answer.

**Comment by bpatrik** [comment]
I mean something like this: https://github.com/bpatrik/pigallery2-sample-extension/blob/b24f9b3b8fab66bbd737527a25559b3de05def58/server.ts#L86

It would not be as neat solution if it would be part of the main app, but you would mostly achieve what you want with minimal headache. (Also avoiding a long back and forth on the PR review)

**Comment by nk9** [comment]
Thanks for the suggestion. However, I need to add a `title` property to the `PhotoMetadata` object in order to set it in the extention like you're doing in the example. I've also had to change the DTOs so that the title info can be saved in addition to the caption, which means I've had to update the DB `DataStructureVersion`. I think those are both outside the scope of an extension?

I've put everything together in a PR, but I expect you'll want some changes. In particular, the PR doesn't engage at all with using the title as the display string for an image. I didn't see an obviously clean and backwards-compatible way to add an option for that, given that "Always show captions" is a boolean. But if the user is using the "punchy title, lengthy caption" approach, they will probably want to be able to replace the image filename with the *title*, not the paragraphs-log caption. Let me know your thoughts.

![Screenshot 2023-12-06 at 16 21 22 Large](https://github.com/bpatrik/pigallery2/assets/3646730/82b33739-2473-4ad3-a63a-738f5d6abeb6)

**Comment by bpatrik** [comment]
Just seeing this.

Thanks for the contribution!

Yeah I agree that we should clean up the title vs caption question in the long term. I see two solutions for that:
1. Make the `use caption` an enum with 3 states: filename, caption, title. Should be relatively easy to add an enum to the clientconfig.
2. Do something like this to the grid photos: https://github.com/bpatrik/pigallery2/issues/801 where all 4 texts can be customized. It would a more complex approach.

**Comment by nk9** [comment]
The changes for #801 look great! Given that, I'm happy to close this.
