### ISSUE TITLE
Stop using `VOLUME` in the Dockerfile

### ISSUE THREAD

**Issue by nk9** [bpatrik/pigallery2#777]
**Describe the bug**

Dockerfiles have a `VOLUME` directive, but it's quite problematic and has no benefits over describing the volumes at runtime using `-v` or `docker compose`.

- Here's [an article](https://boxboat.com/2017/01/23/volumes-and-dockerfiles-dont-mix/) that goes over the issues. "So go ahead, use volumes, they are a great feature of Docker. Just don't define them inside your Dockerfile."
- And [a StackOverflow answer](https://stackoverflow.com/a/62068396/1749551) which also highlights these same problems

The recommended way to use piGallery2 with Docker is to use the `docker-compose.yml` file, which declares the volumes itself. Given that, it may be possible to just remove the `VOLUME` directive entirely.

**Comment by bpatrik** [comment]
Hi,

Thank you for the notice!
Can send a PR fixing the docker build files and the compose files that
removes volumes from the build files, but keeps the current compose
behavior? (I mean keeps exposing config and images folder)

-- Sorry for being brief, sent from my phone.

**Comment by nk9** [comment]
I lost track of this. Thanks for jumping in and fixing it, @grasdk!
