### ISSUE TITLE
Language switch ignores UrlBase

### ISSUE THREAD

**Issue by grasdk** [bpatrik/pigallery2#793]
**Note:** Please always try reproducing the issue on the `:edge` build. There is a chance that it was already fixed. If it's an UI issue, you can try reporducing it on the [demo page](https://pigallery2.onrender.com/). 

----------------------------------------------------------------------------------

**Describe the bug**

- Host pigallery behind a proxy (I use Caddy2) using a path, e.g. "gallery"
- Configure pigralleryt BaseUrl to "/gallery"
- Restart to take effect
- login
- switch language and you're at your root

Expected
- https://www.example.com/gallery/gallery?ln=sv
Actual
- https://www.example.com/?ln=sv

**Used app version**:
- docker:latest

**Comment by bpatrik** [comment]
The last commit should fix this.

**Comment by grasdk** [comment]
Perfect. I will test the :edge next time. It was a bit late here ;)
