### ISSUE TITLE
Alternative Directory Thumbnail 

### ISSUE THREAD

**Issue by d00astro** [bpatrik/pigallery2#80]
Currently the first image in a directory is used as its thumbnail.
It would be nice if it was possible to use other images instead.
For my use-case* it would be great if I could change the behaviour to take the middle image instead.
More advanced option would be to be able to set a fractional index of the thumbnails (so that 0.0 would be first image, as per now. 0.5 would be middle image and 1.0 would be last image).

Not ideal for me, but maybe useful to others if it was possible for each directory to specify exactly which image to use as thumbnail.

I'm not frontend developer but I looked at the code and did some 'debugging' and i see that the directory component has access to the two first images as 'media'. However, I also see that the backend directory scanning adds all images as media to the directory object, but I fail to understand how it gets reduced / selected to only two for the component. 
With some pointers on how this is done, I might be able to sort it out on my own.

'* I am using pigallery2 for listing images sampled every 5 minutes every day between 6 am an d 7 pm, with one new directory per day. My 'problem' is that the thumbnail for each directory is currently black, as the sun has not yet risen when the first image of each day / directory is taken. 

Thanks for a neat project!

**Comment by bpatrik** [comment]
Hi,

Thank you for the suggestion. It this point I don't find this feature to be the best fit in my current plans, but I would leave this issue open and If you get some likes on it I don't mind implementing it.

You can also alter the app for you own taste:
The sub directories only get a partial list of its photos.
This partial list generated in two ways:
1) not yet indexed:
 At [the DiskMangerWorker:scanDirectory function ](https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/backend/model/threading/DiskMangerWorker.ts#L44) there is a recursive function call at [line:77](https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/backend/model/threading/DiskMangerWorker.ts#L77)  that fills the subdirectories.
This is where the subdirectories are filled with photos
2) already in db:
[GalleryManager:fillParentDir:300 fills the sub directories](https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/backend/model/sql/GalleryManager.ts#L300)

On the frontend side: Data is stored in locale cache. If a dir is not in the local cache, it request from the server otherwise from the cache, It is possible that the cache contains full photo list for a sub directory than the fronted works with that.

At the fronend the sample dir photo is selected [here](https://github.com/bpatrik/pigallery2/blob/1bf538f818e11b50e2a08614c0fe826944c69312/frontend/app/ui/gallery/directories/directory/directory.gallery.component.ts#L31). 

To solve your issue: you need to make sure that on the server side the desired photo is in the media list and on the frontend you need to select that photo from the list.

I hope it helps.

Best,
Patrik

**Comment by Wdavery** [comment]
What do you think about setting a thumbnail via hidden file in the parent directory?

Consider the following directory:

`>ParentFolder`
`>ExampleFolder >FolderB >.ExampleFolder.png`

`ExampleFolder` would create a thumbnail from `.ExampleFolder.png`, and FolderB would use the current default behaviour.

This would allow using custom album covers or any image whether it is in the subdirectory or not. Crude example: 
![image](https://user-images.githubusercontent.com/12989893/115260664-f789b080-a100-11eb-95aa-727bf5d07ae9.png)

**Comment by bpatrik** [comment]
I'm not sure if `.` files would work. There is some issue with files that start with dot. (cannot recall what, but comes from nodejs, so I cannot do anything with that).

From the top of my mind, I do not know any elegant solution for this one, but I welcome any contribution.

It should  work (eventually) consistently here:
1. Loading it from the DB:
  * https://github.com/bpatrik/pigallery2/blob/8ec734dfb7fdd98a5fa1a60070e944840b335ac8/src/backend/model/database/sql/GalleryManager.ts#L273-L283
  * If the given folder does not have a photo, it tries to populate it from subfolders:  https://github.com/bpatrik/pigallery2/blob/8ec734dfb7fdd98a5fa1a60070e944840b335ac8/src/backend/model/database/sql/GalleryManager.ts#L218-L234
 2. Loading from disk directly: https://github.com/bpatrik/pigallery2/blob/8ec734dfb7fdd98a5fa1a60070e944840b335ac8/src/backend/model/threading/DiskMangerWorker.ts#L145-L152

pigallery works the following way:

checks if a folder is indexed:
 * if no, reads from the disk and returns with that and saves to the DB asynchronously
 * if yes, reads from the DB

(Its a bit more complicated, but this is the important part)

**Comment by Wdavery** [comment]
> I'm not sure if `.` files would work. There is some issue with files that start with dot. (cannot recall what, but comes from nodejs, so I cannot do anything with that).

Just spitballing, but what about `photoname.png.pg2cover` or something along those lines? The gallery would ignore the file for having an incompatible extension, but we could do a quick probe for `*.pg2cover` in the directory, then if not found move on to creating the thumbnail as default.

BTW, thanks for all your work on this project and being so welcoming to tweaks and features. Linking to relevant code is great for understanding how these things could be implemented or not (even if some of it goes over my head).

**Comment by bpatrik** [comment]
I gave some thought to it and I think a good solution would be that admins would be able set up a search query and the latest photo that that query returns should be the preview icon/image.
(Of course only from a given dir or from subdirs if there is no result in the given dir, or discard the search query if that does not return a result from any of the subdirs)

With this admins could do: `file_name:cover.jpg` or `min_rating:3 and keyword:"top photos"`. 

It works now very similarly for the new logical (saved search) albums: https://github.com/bpatrik/pigallery2/blob/f2ab96faaf0593319912fb0da737b6d50f45ac67/src/backend/model/database/sql/SearchManager.ts#L226-L238

**Comment by bruce30262** [comment]
So I ran into a similar issue recently, and decided to post it here.   

I notice that the "photo with the latest creation date" will be selected as the thumbnail of the directory. However, I would like the thumbnail to be "the first photo sorted by the ascending name". Is there any way I can achieve this by just changing the default settings ? It seems that pigallery2 doesn't support customized thumbnail for each folder currently.

**Comment by wechsler42** [comment]
> 
> 
> I gave some thought to it and I think a good solution would be that admins would be able set up a search query and the latest photo that that query returns should be the preview icon/image.
> (Of course only from a given dir or from subdirs if there is no result in the given dir, or discard the search query if that does not return a result from any of the subdirs)
> 
> With this admins could do: `file_name:cover.jpg` or `min_rating:3 and keyword:"top photos"`.
> 
> It works now very similarly for the new logical (saved search) albums:
> 
> https://github.com/bpatrik/pigallery2/blob/f2ab96faaf0593319912fb0da737b6d50f45ac67/src/backend/model/database/sql/SearchManager.ts#L226-L238

Thanks for the this good idea bpatrik. From my point of view it is a fully flexible solution with which I would really like to work with. Another solution would be that I just choose a thumbnail in the gallery view to become the directory thumbnail via right-click on it and mark it as the directory thumbnail. However, for that context menus needed to be implemented first and this might be a load of work to do.

**Comment by bpatrik** [comment]
#43343b2 adds the ability to set the preview with a search query and custom sorting amoung the results.
Config:
https://github.com/bpatrik/pigallery2/blob/bae5559356e4d4320425415696e6fd6d24e5fc04/src/common/config/private/PrivateConfig.ts#L301-L309

Setting this config is not yet visible on the UI, you can only do it through the `config.json`

Search query expect the search query data structure, not the string. You can get that from the UI too. This is what you need: 
![kép](https://user-images.githubusercontent.com/7512182/124657822-472b7d00-dea3-11eb-8868-3e1ecd42ee72.png)

**Comment by bpatrik** [comment]
Now there is also a search entry to set preview. This feature should be complete
