### ISSUE TITLE
Use Imaginary for previews?

### ISSUE THREAD

**Issue by rhatguy** [bpatrik/pigallery2#807]
Has any consideration been given to using [Imaginary](https://github.com/h2non/imaginary) for preview generation instead of generating them inside PiGallery2?  Nextcloud (and the Nextcloud AIO) offer Imaginary now so I feel like its fairly well tested (and speedy).  I realize this would add an outside dependency which might not be desirable, but it might also offload some code maintenance around image manipulation onto an outside tool/API.  Not sure if this is a good idea or not?

imaginary can deal efficiently with up to 20 request per second running in a multicore machine, where it crops a JPEG image of 5MB and spending per each request less than 100 ms

**Comment by bpatrik** [comment]
imaginary uses the same library as pigallery in the background. I'm not
sure if adding an extra indirection in the middle would help with the
performance.

**Comment by rhatguy** [comment]
I was not aware of that.  Obviously using imaginary would break the self contained nature of PiGallery2 somewhat also.  I was not coming at the question from a performance perspective but from an ease of maintainability perspective.  Move image resize operations to an API that didn't need to be maintained inside PiGallery2.

I just hadn't seen anything documented about imaginary here so just asking the question.  Should we close this issue?

**Comment by bpatrik** [comment]
What I meant that pigallery2 uses sharp that is a binary binding to
libvips. Imaginary also uses libvips for photos.
Sharp is one of the best performing lib and performance is very important
if I want to keep supporting low-end devices.

I think we can close this.

-- Sorry for being brief, sent from my phone.

**Comment by rhatguy** [comment]
Thanks for the information and thanks for the great product!  PiGallery2 fills a much needed niche in the self hosting space.
