### ISSUE TITLE
Ascending/descending date order doesn't work for some photos

### ISSUE THREAD

**Issue by tkedwards** [bpatrik/pigallery2#82]
I have a folder of about 380 photos and 15 videos from a recent holiday. For most of the photos the sort by 'Ascending/descending date order' works fine. But there are several photos (about 10) that appear out of order right at the end (i.e after the newest photos from the end of the holiday). For example there's about 5 photos taken 30 May 2019 that appears ordered *after* photos taken 23 June 2019.

I've looked over the metadata (Exif, XMP, IPTC) and all the date/time settings look correct. I've also tried re-indexing and even starting with a new sqlite DB file. No matter what the same photos still show out of order. As a test I uploaded the entire folder to my Flickr account and the ordering of the photos is shown correctly.

I'm using the Docker image

**Comment by bpatrik** [comment]
Hi,

Can you please check if the app reads the correct date&time for the photos/videos?
Like opening the right info panel on the photos and checking if the dates are correct.

Thank you!

Best,
Patrik

**Comment by tkedwards** [comment]
The weird thing is it reads the correct date/time for the photos that are *out of order* (e.g the 31 May photos that appear after the 23 June ones). But for the photos that are *in order* (e.g the 23 June ones) it just shows 'January 19, 1970'. 

Another difference: the photos are are correctly in order show the GPS location on Openstreetmap, but none of the photos that are out of order show the GPS location

**Comment by tkedwards** [comment]
I had a look in the sqlite database. The metadataCreationDate field in media_entity contains the correct value (31 May for the photo)

**Comment by bpatrik** [comment]
Hi,

Thank you!
It indeed looks weird.
Can you maybe send me photos produce that this error?
It's okay if you scale them down to 1x1px (in that case can you make sure
that they still produce the error)

Best,
Patrik

**Comment by tkedwards** [comment]
Thanks for looking into it, it's a very strange problem since it only affects a few photos seemingly at random.

As soon as I edited the problem photo in Gimp and exported it from the problem seemed to go away. So here are the original files (the link expires after 2 downloads, please don't attach here since you can't delete attachments from Github): https://send.firefox.com/download/804625a9c703d5e1/#r7klF3RZiypByueb_HhWNA

**Comment by bpatrik** [comment]
Hi,

Thanks, I got them. You can remove them. 
I'll take a look at them in a week or so. If the issue is a fault exif data, I might not be able to do anything with it tho :/

Patrik

**Comment by tkedwards** [comment]
Thanks!

**Comment by bpatrik** [comment]
Hi,

I checked the photos that you have sent me and I could not reproduce the error.

I suspect the following: 
- the photo sorting part of the app is correct, and the photo reader part has an error:
- the one you have sent me are actually the correctly recognized photos. 
- the rest have an error. You mentioned that some of the photos recognized as 'January 19, 1970'. This date means that the app could not recognized the date on the photos, so the default '0' timestamp was used.
You can try sending me one from that erroneous photo so I can check what's wrong with the photo reader.

Best,
Patrik

**Comment by tkedwards** [comment]
I think you're right, basically all the photos (in multiple different folders and sub-folders, including photos taken 10 years ago or more) show as '19 January 1970' in the UI. 

Here are two fairly recent photos that show as that date, and screenshots showing what they look like in the UI: https://send.firefox.com/download/306be685ef66f4f7/#4t7xVPLRHQ14htnZF2bJlw

**Comment by bpatrik** [comment]
Hi

I've checked your photos and I could not reproduce the error.
Can you let me know what platform are you using  to run the server?
Also witch version are you using? v1.5.6.
I made a fix on date parsing after releasing v1.5.6. You can try building from source /using docker nightly. Or wait a few weeks until a create a new release.

Patrik

**Comment by tkedwards** [comment]
Thanks! I switched to using 'bpatrik/pigallery2:nightly-stretch' in Docker and that's resolved the problem. Thanks for your work on this!
