### ISSUE TITLE
Question: How should I handle keyword updates?

### ISSUE THREAD

**Issue by b-a0** [bpatrik/pigallery2#822]
Sometimes I add/remove keywords to photos in Lightroom or Bridge. The photo itself remains the same, but the keyword data is updated. While this is reflected in the file itself, pigallery2 does not pick up that change, even after clicking "Run now: Indexing" with the indexing sensitivity set to medium.

What is the recommended way of letting pigallery2 know about a metadata change?

**Comment by bpatrik** [comment]
Do you write back the keyword change to the jpg?

It works for me with Lightroom?

-- Sorry for being brief, sent from my phone.

**Comment by b-a0** [comment]
Yes, I use Lightroom and write back to the JPEG (I can see the keyword in the file). Just now I did the search again, did not get the required results, but after a refresh of the search results page the photos did come up! 
so issue is resolved, but I am not sure what changed between when I opened the issue and now...

**Comment by bpatrik** [comment]
The app only reindexes a folder if you navigate to it or click the inedxing
button. (Eg just searching won't trigger a reindex).

Even after the indexing only runs for folder where the folder modification
date changed.

-- Sorry for being brief, sent from my phone.

**Comment by b-a0** [comment]
> Even after the indexing only runs for folder where the folder modification
date changed

Thanks for the clarification. How can I ensure the folder modification date changes? Does a file need to be added/removed to the folder?
