### ISSUE TITLE
Error installing with npm on FreeBSD ARM

### ISSUE THREAD

**Issue by dkaparis** [bpatrik/pigallery2#828]
Trying to install the current release 2.0 on FreeBSD 13.2-RELEASE-p9 with npm gives error:

```
npm ERR! code 1
npm ERR! path /usr/local/pigallery2/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-freebsd-arm64v8.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: Prebuilt libvips 8.13.3 binaries are not yet available for freebsd-arm64v8
```

Any chance this could work under FreeBSD/arm?

**Comment by bpatrik** [comment]
From the error message I guess you need to manually build libvips.


Also the official recommend way to use the app with docker.

-- Sorry for being brief, sent from my phone.

**Comment by dkaparis** [comment]
> From the error message I guess you need to manually build libvips. Also the official recommend way to use the app with docker.

Docker is not directly usable under BSD. Regardless, after installing `vips` from packages or ports, Pigallery2 installs and runs with npm.

Thanks for your work on the project.
