### ISSUE TITLE
API exposes absolute server paths

### ISSUE THREAD

**Issue by flesser** [bpatrik/pigallery2#84]
This *might* be a minor security issue in some settings, giving a possible attacker insight into your internal server file structure:

Example:
`curl -X GET https://pigallery2.herokuapp.com/api/gallery/content/non-existing-image.jpg`
returns:
`{"error":{"code":7,"message":"no such file:/app/demo/images/non-existing-image.jpg"},"result":null}`

https://github.com/bpatrik/pigallery2/blob/master/backend/middlewares/GalleryMWs.ts#L170

**Comment by bpatrik** [comment]
Thank you . I'll try to fix it as soon as possible.

Patrik

**Comment by bpatrik** [comment]
Hi

Commit [2cad224](https://github.com/bpatrik/pigallery2/commit/2cad2241e1d3e8f2a758d7ba472902e7d25be43f) should solve this issue and be part of the next release.

Best,
Patrik
