### ISSUE TITLE
Gallery doesn't load with mixed videos and photos until time for each video are retrieved

### ISSUE THREAD

**Issue by evrial** [bpatrik/pigallery2#840]
When gallery has mixed videos and photos the loading icon displays until `ffprobe --show-streams --show-format filename.mp4` in process list is gone. In case if you have 80% of small videos, well you have to wait some time. Only photo directories are rendering photos on demand (on scroll).
Running on everything latest. Also could run multiple workers for ffprobe.

**Comment by bpatrik** [comment]
That is expected. The on demand load only applies to thumbnail load. The
app loads all metadata at one go. So a full directory parse is required
before showing anything on client side.

I recommend running indexing once so the experience will be more smooth

-- Sorry for being brief, sent from my phone.

**Comment by evrial** [comment]
Ok thanks
