### ISSUE TITLE
Extension configuration is broken

### ISSUE THREAD

**Issue by mblythe86** [bpatrik/pigallery2#847]
**Describe the bug**

The values from `extension.config.getConfig()` no longer reflect what is present in `config.json`, nor what is shown on the admin page.

**Screenshots (optional)**

This is present in my config.json:

```
    "Extensions": {
        "enabled": true,
        "//[folder]": "Folder where the app stores all extensions. Individual extensions live in their own sub-folders.",
        "folder": "/app/data/config/extensions",
        "extensions": [
            {
                "enabled": true,
                "//[path]": "Folder where the app stores all extensions. Individual extensions live in their own sub-folders.",
                "path": "dk-extension",
                "configs": {
                    "//[digikamShowCollection]": "DigiKam Directory Category",
                    "digikamShowCollection": "Public",
                    "//[digikamDbType]": "DigiKam Database Type (MySQL or SQLite)",
                    "digikamDbType": "MySQL",
                    "//[digikamSqliteDb]": "DigiKam SQLite DB filename",
                    "digikamSqliteDb": "/app/data/digikam/digikam.db",
                    "//[digikamMysqlHost]": "DigiKam MySQL DB hostname",
                    "digikamMysqlHost": "192.168.42.3",
                    "//[digikamMysqlPort]": "DigiKam MySQL DB port",
                    "digikamMysqlPort": 3306,
                    "//[digikamMysqlDb]": "DigiKam MySQL DB name",
                    "digikamMysqlDb": "digikam",
                    "//[digikamMysqlUser]": "DigiKam MySQL DB username",
                    "digikamMysqlUser": "dk_ro",
                    "//[digikamMysqlPassword]": "DigiKam MySQL DB password",
                    "digikamMysqlPassword": "redacted"
                }
            }
        ],
        "//[cleanUpUnusedTables]": "Automatically removes all tables from the DB that are not used anymore.",
        "cleanUpUnusedTables": true
    },

```

This is what the admin page shows:

![image](https://github.com/bpatrik/pigallery2/assets/751675/2cf84239-8144-45f1-9ea2-d4a04ae8d1be)

**Server logs (optional)**

When I have the extension dump the `extension.config.getConfig()` object, the state has the default values, not my real values:

```
pigallery2_dev  |   __state: {
pigallery2_dev  |     digikamShowCollection: {
pigallery2_dev  |       description: 'DigiKam Directory Category',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'Public',
pigallery2_dev  |       default: 'Public',
pigallery2_dev  |       hardDefault: 'Public'
pigallery2_dev  |     },
pigallery2_dev  |     digikamDbType: {
pigallery2_dev  |       tags: [Object],
pigallery2_dev  |       description: 'DigiKam Database Type (MySQL or SQLite)',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'MySQL',
pigallery2_dev  |       default: 'MySQL',
pigallery2_dev  |       hardDefault: 'MySQL'
pigallery2_dev  |     },
pigallery2_dev  |     digikamSqliteDb: {
pigallery2_dev  |       description: 'DigiKam SQLite DB filename',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: '/app/data/digikam/digikam.db',
pigallery2_dev  |       default: '/app/data/digikam/digikam.db',
pigallery2_dev  |       hardDefault: '/app/data/digikam/digikam.db'
pigallery2_dev  |     },
pigallery2_dev  |     digikamMysqlHost: {
pigallery2_dev  |       description: 'DigiKam MySQL DB hostname',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'localhost',
pigallery2_dev  |       default: 'localhost',
pigallery2_dev  |       hardDefault: 'localhost'
pigallery2_dev  |     },
pigallery2_dev  |     digikamMysqlPort: {
pigallery2_dev  |       description: 'DigiKam MySQL DB port',
pigallery2_dev  |       type: 'float',
pigallery2_dev  |       value: 3306,
pigallery2_dev  |       default: 3306,
pigallery2_dev  |       hardDefault: 3306
pigallery2_dev  |     },
pigallery2_dev  |     digikamMysqlDb: {
pigallery2_dev  |       description: 'DigiKam MySQL DB name',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'digikam',
pigallery2_dev  |       default: 'digikam',
pigallery2_dev  |       hardDefault: 'digikam'
pigallery2_dev  |     },
pigallery2_dev  |     digikamMysqlUser: {
pigallery2_dev  |       description: 'DigiKam MySQL DB username',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'digikam',
pigallery2_dev  |       default: 'digikam',
pigallery2_dev  |       hardDefault: 'digikam'
pigallery2_dev  |     },
pigallery2_dev  |     digikamMysqlPassword: {
pigallery2_dev  |       description: 'DigiKam MySQL DB password',
pigallery2_dev  |       type: 'string',
pigallery2_dev  |       value: 'password',
pigallery2_dev  |       default: 'password',
pigallery2_dev  |       hardDefault: 'password'
pigallery2_dev  |     }
pigallery2_dev  |   },
```

**Environment (please complete the following information):**
 - OS: Server & browser: Ubuntu 22.04
 - Browser: Firefox

**Used app version**:
Compiled from source: github commit 3811fc3c

**Comment by bpatrik** [comment]
I had a look. Unfortunately it not simple to fix so it will take a while.

I had to restructure the config lib to have UI generation support for extensions too, but that apparently broke some config loading.

**Comment by mblythe86** [comment]
I think I found the problem in [this change](https://github.com/bpatrik/pigallery2/commit/4352ff89b76bda8c803c670c158fd51749f568dc?diff=split&w=1#diff-0678bcacef834e66eb120492f774d3ae1cb9613533512eb6c148d05d3cdf24beL49).

Previously, `__loadJSONObject()` was called to populate the config values into the newly-created extension configuration object.  After the change, the extension configuration object is placed as-is (i.e. with the default values) into the passed-in `PrivateConfigClass` object.

I think the fix is to `load()` or `loadSync()` the config again afterwards.  I don't know whether this is best done within the `loadToConfig()` function itself, or if it should be done by the calling function.  It looks like `ExtensionConfigWrapper::original()` and `ExtensionConfig::setTemplate()` are the only places where `loadToConfig()` is called, and `original()` already calls `load()` afterwards.  With that in mind, in my local codebase, I added a `loadSync()` to `setTemplate()`.  It seems to fix it.

I'll put together a pull request with my fix shortly.

**Comment by mblythe86** [comment]
Hmm, my simple change only fixes the case where some extension config already exists in the `config.json` file.  If that file is deleted, or if an extension is added to an existing install, then the extension config is not created.

**Comment by mblythe86** [comment]
I might know what's going on now with regards to the empty/new extension config.  I think it will need to be fixed in typeconfig.

[This](https://github.com/bpatrik/pigallery2/blob/master/src/common/config/private/subconfigs/ServerExtensionsConfig.ts#L69) is where the extension configurations are added - an array of `ServerExtensionsEntryConfig`.

[This is the code](https://github.com/bpatrik/typeconfig/blob/master/src/decorators/class/base/ConfigClassBase.ts#L227-L236) responsible for filling arrays from JSON.  It has a special case to try JSON-decoding a string within an array, but aside from that, it will end up calling `set()`.  In this case, it will end up clobbering the array of FIXME with null or something.

We're basically guaranteed that the `config.json` file exists by the time we initialize the extensions (and they call `setTemplate()`).  So, even if the extension config objects are added to the global `Config`, they'll be removed the next time `Config.load()` is run.

**Comment by mblythe86** [comment]
It looks like typeconfig doesn't have this problem when a key is a nested `@SubConfigClass` because it should enter [this condition](https://github.com/bpatrik/typeconfig/blob/master/src/decorators/class/base/ConfigClassBase.ts#L238-L240), recursively call itself, and [immediately return](https://github.com/bpatrik/typeconfig/blob/master/src/decorators/class/base/ConfigClassBase.ts#L205-L207) without clobbering anything (and I assume it uses the default values at that point).

Along that line, is there a way to dynamically add a `@ConfigProperty` to a `@SubConfigClass`?  If so, instead of pushing extension configs into an array, we could add it as a new key (using the extension_id?) directly in `ServerExtensionsConfig` (or a nested `@SubConfigClass` that we use only as a container for extensions).

If that's not possible, then (and I'll be the first to admit this is an ugly hack), then maybe we could add a bunch of these to the `ServerExtensionsConfig` class:

```ts
  @ConfigProperty({
    tags: {
      name: $localize`Installed extension 1`,
      priority: ConfigPriority.advanced
    }
  })
  extension1?: ServerExtensionsEntryConfig;

  @ConfigProperty({
    tags: {
      name: $localize`Installed extension 2`,
      priority: ConfigPriority.advanced
    }
  })
  extension2?: ServerExtensionsEntryConfig;

...and so on...
```

**Comment by bpatrik** [comment]
added [d4d8dcf](https://github.com/bpatrik/pigallery2/commit/d4d8dcfcdb3241b774fe53ee9c79263181ee3621) that hopefully fixes the issue.

Long story short, with the nice UI support I had to make fundametnal changes to the config library that created a circular depdenency between the config and extensions. I need to major code rafactor around the extensions handling to undo the circular dependency. I found it hard to test so far, so its just "best effort now".

Also **note** the extension interface changed. There is now a separate function to set the config template. See example.

**Comment by mblythe86** [comment]
I tried d4d8dcf, and got an error.  The next commit without the error is 7f65dfd, and extension configuration is still broken.  When starting from an empty config, the admin page doesn't populate anything.  When starting with a known-good config, the admin page shows the extension location, and that's it:
![image](https://github.com/bpatrik/pigallery2/assets/751675/042a0032-7aae-4307-b937-93b166039487)
It also doesn't seem to make the config available to the extension:
```
pigallery2_dev  | 3/31/2024, 6:58:52 AM[SILLY][Extension][pigallery2-extension-digikam-connector] extension.config.getConfig(): undefined
```
Can you re-open this?  Or should I open a new issue?

**Comment by bpatrik** [comment]
Ahh annoying.

I got quiet busy with life until like July, but I'll try to fix it.

Let's reopen this.

**Comment by bpatrik** [comment]
tagging #743 and #784 as the main issue

**Comment by bpatrik** [comment]
> I tried [d4d8dcf](https://github.com/bpatrik/pigallery2/commit/d4d8dcfcdb3241b774fe53ee9c79263181ee3621), and got an error. The next commit without the error is [7f65dfd](https://github.com/bpatrik/pigallery2/commit/7f65dfd1b2a40ffcfae7ea4a51b1ef1ee19cc99d), and extension configuration is still broken. When starting from an empty config, the admin page doesn't populate anything. When starting with a known-good config, the admin page shows the extension location, and that's it: ![image](https://private-user-images.githubusercontent.com/751675/318247597-042a0032-7aae-4307-b937-93b166039487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzQ5ODAsIm5iZiI6MTcxMjMzNDY4MCwicGF0aCI6Ii83NTE2NzUvMzE4MjQ3NTk3LTA0MmEwMDMyLTdhYWUtNDMwNy1iOTM3LTkzYjE2NjAzOTQ4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNjMxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGZlMGYyZTJhODhkMzg4NjRiY2IxNzMyZjIzY2Y5ZWI5NjkyMDA4MDAwODA2ZWExMDY5MWRhZTljYzMyYzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0FgzeBjhbOfn2VnOIHhGprB6txEx7yw_wlf3rZoAW4k) It also doesn't seem to make the config available to the extension:
> 
> ```
> pigallery2_dev  | 3/31/2024, 6:58:52 AM[SILLY][Extension][pigallery2-extension-digikam-connector] extension.config.getConfig(): undefined
> ```
> 
> Can you re-open this? Or should I open a new issue?

Did you update your extension after the commit? Setting the config template changed with that and also the extension `pigallery2-extension-kit`

**Comment by mblythe86** [comment]
> Did you update your extension after the commit? Setting the config template changed with that and also the extension `pigallery2-extension-kit`

Yes, I updated my `package.json` to depend on `"pigallery2-extension-kit": "2.0.3-edge6"`, and I implemented the `initConfig` function.

I realized today that my issue might have been that I didn't run `npm install` after updating `package.json`, but that didn't have any effect.

Just to check that my `initConfig` function is getting called at all, I added a `console.log()`, but I don't see that printing out anywhere.

I also tried the sample extension.  The first issue I hit with that was this:

```
> npm run build

> pigallery2-sample-extension@1.0.1 build
> tsc

server.ts:19:36 - error TS2307: Cannot find module 'pigallery2-extension-kit/src/backend/model/extension/IExtension' or its corresponding type declarations.

19 import {IExtensionConfigInit} from 'pigallery2-extension-kit/src/backend/model/extension/IExtension';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in server.ts:19
```

After fixing that locally, it still wouldn't load the extension.  In fact, it didn't even recognize that a new extension had been added at all!

**Comment by mblythe86** [comment]
It looks like `loadExtensionList` in `ExtensionManager.ts` used to add any directories it found into `Config.Extensions.extensions`, but it doesn't do that anymore.  This feels like the root cause of these issues I mentioned:

> When starting from an empty config, the admin page doesn't populate anything.

> it still wouldn't load the extension. In fact, it didn't even recognize that a new extension had been added at all!

I haven't examined the most recent refactor of the extension loading code, so maybe the process to discover new extensions happens somewhere else now?

**Comment by bpatrik** [comment]
I made  #885 (also some commits to typeconfig) that brings us one step closer to the solution

**Comment by bpatrik** [comment]
The last commit should (mostly) fix this issue.

There are still 2 outstanding TODOs to fully fix it:

1. If the extension order in the config changes (like you install a new one), that will mess things up:
https://github.com/bpatrik/pigallery2/blob/055862f2753f621fb521b8c9b68731cbc709dc2e/src/backend/model/extension/ExtensionConfigTemplateLoader.ts#L112-L114
2. If the json config does not contain a extension, it wont load it (basiacally the empty or partial array, overrides the given config):
https://github.com/bpatrik/pigallery2/blob/055862f2753f621fb521b8c9b68731cbc709dc2e/src/backend/model/extension/ExtensionConfigWrapper.ts#L23-L30

+1 there is some issue with the default values if the config is not loaded form JSON. And default values can mess up for extension. 

Default values are only used for making the UI bold blue, so not a big issue.

Solving 1. by using an Map instead of an array, should also solve 2.

**Comment by bpatrik** [comment]
I had to change the extension interface again:

config has now a separate config.js file to set it up. (I had to separate it, so just setting up the config does not need running npm install an all extensions. This would have delayed the app startup).

See sample extension.

**Comment by bpatrik** [comment]
@mblythe86 Made some comments here and also at one of your PR and your comment in the other repo.
Sorry, but I might end up rejecting most of your PR. :/ 

The not-so-technical root cause of the whole issue is that:
1. typeconfig is overcomplicated. If it works its awesome, because it validates input config and provides a lot of metadata to the UI. (like the default value of the config, so the UI can show if it has been changed)
2. seting up config is the least fun of this project, so it hard to find motivation to working on it
3. setting up this extension config takes waay more time than I expected (at lest 3-4 month more)
4. I'm getting overwhelmed in private life, so I just have less time recently to this project. 
    1. and typeconfig is a complex, generic lib, that needs significant focus time to untangle all the dependencies.

**Comment by mblythe86** [comment]
>  Sorry, but I might end up rejecting most of your PR. :/

No worries!  It sounded from a previous comment like you were pretty busy in your private life, so I was just trying to do what I could.

If you have an idea about what still needs to change in typeconfig and/or pigallery2 to get this fully working, please share.  I'm happy to learn more about the codebase and give it a try.  It sounds like the `GenericConfig` type in typeconfig is the direction you want to go?

**Comment by bpatrik** [comment]
I think now extension config is more or less working for majority of the cases. 

To fix the outstanding issues, I think the best approach would be to actually use a Map like object then a array. But as I mentioned in typeconfig that is not really supported, so just changing to it might not work out of the box.

If that is the case, I plan to add a "addNewProperty" to the generic configtype that does all the magic.

**Comment by mblythe86** [comment]
I still need this tweak in order for pigallery2 to find my extensions at all:

```
> git diff
diff --git a/src/common/config/private/Config.ts b/src/common/config/private/Config.ts
index 7a14e5c0..1c1ccc85 100644
--- a/src/common/config/private/Config.ts
+++ b/src/common/config/private/Config.ts
@@ -10,6 +10,6 @@ try {
   pre.loadSync({preventSaving: true});
 } catch (e) { /* empty */
 }
-ExtensionConfigTemplateLoader.Instance.init(path.join(__dirname, '/../../../../', pre.Extensions.folder));
+ExtensionConfigTemplateLoader.Instance.init(pre.Extensions.folder);
 
 export const Config = ExtensionConfigWrapper.originalSync(true);
```

I'm not sure if this is due to some oddity in how I'm building my Docker image for testing (I'm using a slightly modified version of `docker/debian-buster/selfcontained/Dockerfile`) or if it's a real bug.

Aside from that, it's working well!  Naturally, my settings didn't transfer from a previous `config.json` where extensions were still in an array, but once I made some changes to the values and saved, it updated `config.json` to the new map-based structure.

I also tested with a non-existent `config.json` file, and it correctly creates the file without any problem.

Also, I tested adding & removing extensions, and it works as expected - showing the default values for any newly-added extensions, not showing settings for deleted extensions, and preserving values for unchanged extensions.

**Comment by mblythe86** [comment]
> I'm not sure if this is due to some oddity in how I'm building my Docker image for testing (I'm using a slightly modified version of docker/debian-buster/selfcontained/Dockerfile) or if it's a real bug.

I think it's a real bug.  I just pulled the `bpatrik/pigallery2:edge-debian-bullseye` image from hub.docker.com, and it has the same issue.  I was able to work around it by duplicating my config volume:

```
    volumes:
      - "./pigallery2/config:/app/data/config"
      - "./pigallery2/config:/app/app/data/config" # This one is necessary to work around the issue
```

I'll submit a pull request with the fix from my previous comment.

**Comment by bpatrik** [comment]
Can you try with [278eb86](https://github.com/bpatrik/pigallery2/commit/278eb86579ab905bc16dd0923a02863de7000a16)?

copying from the #897 review: 
> yeah so the docker used absolute path, while my test setup used a relative one.
> Your PR fixes it for absolute path (eg the docker build), but breaks it for absolute.
> My last commit should fix it for both.

**Comment by mblythe86** [comment]
That seems to fix it, thanks!
