### ISSUE TITLE
Missing elements in the translation process

### ISSUE THREAD

**Issue by wikijm** [bpatrik/pigallery2#85]
Hi @bpatrik 

**Describe the bug**
Some elements of the frontend are not present in the language files, and therefore have not been translated, at least not in French. See the examples below. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10724809/61315279-b7e0b700-a7fe-11e9-9f2f-fb812d96074f.png)
https://pigallery2.herokuapp.com/gallery/%2F

![image](https://user-images.githubusercontent.com/10724809/61315633-7d2b4e80-a7ff-11e9-9500-c3e44665b0a2.png)
https://pigallery2.herokuapp.com/admin

**Environment (please complete the following information):**
 - OS: Windows 10 Professional
 - Every browser

**Used app version**:
- Heroku demo

**Comment by bpatrik** [comment]
Hi
Thanks! I'll try to look into it soon. 
I can fix the english part, but as I don't speak french I cannot fix that one.

Patrik

**Comment by wikijm** [comment]
Don't worry for the French part, I'll handle it 😃 

Gallery => Galerie
Faces = >Visages
Simplified => Simplifié
Advanced => Avancé
Enabled => Activé
Disabled => Désactivé
Ascending name =>Nom croissant
Descending name => Nom décroissant
Ascending date => Date croissant
Descending date => Date décroissant
Random => Aléatoire

**Comment by bpatrik** [comment]
Hi
I've added the missing translation to the app.
I left the words in the french localization file with original english text.
You can find the new words after line 1530: https://github.com/bpatrik/pigallery2/blob/a42674376a1f7e2ce3699390ecccea3d9b161f3f/frontend/translate/messages.fr.xlf#L1532
You can change the text between the `<target>`-tag to translate the page.

Patrik

**Comment by wikijm** [comment]
And done for the french version: https://github.com/bpatrik/pigallery2/pull/90

**Comment by bpatrik** [comment]
Merged, thanks!

**Comment by wikijm** [comment]
You're welcome :-)
