### ISSUE TITLE
Regardless of the urlBase settings, reverse proxy access thru NGINX does not work with domain/subfolder

### ISSUE THREAD

**Issue by Tos26** [bpatrik/pigallery2#854]
Hello,

I have Nginx as front end in my server (based on raspberry pi).
Several services work well with reverse proxy configured in Nginx with subfolder in URL : 

https://mydomain.com/app1
https://mydomain.com/app2

So I would like to do the same thing with pigallery2 but it fails.

Here is my conf on nginx side:

>       # Reverse Proxy PiGallery2 server
>         location /photos {
>                 proxy_pass http://127.0.0.1:port;
>                 proxy_http_version 1.1;
>                 proxy_set_header X-Forwarded-Fpigallery2or $proxy_add_x_forwarded_for;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>        }

and I set config.json like that:

> "urlBase": "/photos",

( I also try without / at the beginning, with / at the end, no effect)

The result in Firefox for https://mydomain.com/photos:
![image](https://github.com/bpatrik/pigallery2/assets/23366980/6a3b56ab-6078-4561-ab31-f92b2161b70b)

I already posted about this behavior : #388 but I couldn't go deeper after that.

Today, I restart this discussion in order to try to fix this issue.
I can't know if the failure comes from nginx or pigallery2 configuration (config.json)

Environment:
 - OS: Raspberry pi OS based on Debian 11 32 bits.
 - Firefox 123.0.1
 - Pigallery2 v2.0.0
 - Not docker
 - Node.JS v18.19.1
 - NGINX v1.18.0-6.1

Can I have some help on this topic?

Here is the debug console when I try to access to the server:
![image](https://github.com/bpatrik/pigallery2/assets/23366980/340dafdf-e975-447a-894d-85cceb11ac9f)
![image](https://github.com/bpatrik/pigallery2/assets/23366980/078d9fce-aea0-4af8-a82b-8d4350e37872)

Let me know what kind of test I can perform to help the investigation.

Thank you in advance.

**Comment by bpatrik** [comment]
I don't have a proper nginx config at hand. If you want to set up manually,  I would look at the sample nginx configuration in the docker folder of this repo.

If you use nginx proxy manager, setting this should work:

![Screenshot_20240330_205228_Chrome.jpg](https://github.com/bpatrik/pigallery2/assets/7512182/13ad644f-0897-436e-86da-3e8f186694db)

And on the Advanced tab:

```
gzip on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_types
		text/css
		text/plain
		text/javascript
		text/markdown
		application/javascript
		application/json
		application/gpx+xml
		application/x-javascript
		application/xml
		application/xml+rss
		application/xhtml+xml
		application/x-font-ttf
		application/x-font-opentype
		application/vnd.ms-fontobject
		image/svg+xml
		image/x-icon
		application/rss+xml
		application/atom_xml;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # Only allow all methods (GET,POST,PUT,etc..) for root (/pgapi).
    # see https://github.com/bpatrik/pigallery2/issues/214
    location /pgapi { #<--- might need to change here 
      proxy_pass http://pigallery2:80; # forwarding to the other container, named 'pigallery2'
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location / { # <--- might need to change here
      limit_except GET {
        deny  all;
      }
      proxy_pass http://pigallery2:80; # forwarding to the other container, named 'pigallery2'
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

```

**Comment by Tos26** [comment]
Hello bpatrik,

Thank you for your help.

I have continued my tests and I'm not sure that is a issue from nginx.

Explanation of tests:

I set that in the config.json:
```
{
    "Server": {
        "applicationTitle": "PiGallery 2",
        "//[publicUrl]": [
            "If you access the page form local network its good to know the public url for creating sharing link."
        ],
        "publicUrl": "",
        "//[urlBase]": [
            "If you access the gallery under a sub url (like: http://mydomain.com/myGallery), set it here. If it is not working you might miss the '/' from the beginning of the url."
        ],
        "urlBase": "/photos",
        "//[apiPath]": "PiGallery api path.",
        "apiPath": "/pgapi",
```

When I try to access to pigallery2 through my local network (then without nginx) at the address : 192.168.1.14:3900/photos, I get: 

![image](https://github.com/bpatrik/pigallery2/assets/23366980/e89caaa3-19b5-49e4-8358-47a0e0a55810)

And if I try to access at the address without /photos in the URL, I get that ("loading" continuously):

![image](https://github.com/bpatrik/pigallery2/assets/23366980/08ebed75-7df0-4fa8-8f4d-c245188f7c37)

I don't know the right config for apiPath but I tested to put /photos/pgapi with the same result.

So it seems to me that is a bad redirection due to a misunderstanding of the urlBase parameter...

What is your opinion about that ?

**Comment by bpatrik** [comment]
To make it work you need two thing:

1. have a reverse proxy that send traffic to the roor (i.e.: '/') of pigallery2, so it can load the index.html
2. set the urlbase to the same thing that you set your reverse proxy too, so the calls from index.html contain the right url.

**Comment by Tos26** [comment]
Hi @bpatrik 

Thank you for your help.
I still don't understand what is wrong.

I'm going to detail exactly my config:

1. Install folder of pigallery2: /var/www/pigallery2
![image](https://github.com/bpatrik/pigallery2/assets/23366980/6366e34a-38c6-47dd-ad1e-0474f4c79317)

2. Content of nginx dedicated to pigallery2:

```
location /pigallery2 {
                 limit_except GET {
                    deny  all;
                 }
                 proxy_pass http://127.0.0.1:3900;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection 'upgrade';
                 proxy_set_header Host $host;
                 proxy_cache_bypass $http_upgrade;
}

```
3. urlBase in config.json:

```
{
    "Server": {
        "applicationTitle": "PiGallery 2",
        "//[publicUrl]": [
            "If you access the page form local network its good to know the public url for creating sharing link."
        ],
        "publicUrl": "",
        "//[urlBase]": [
            "If you access the gallery under a sub url (like: http://mydomain.com/myGallery), set it here. If it is not working you might miss the '/' from the beginning of the url."
        ],
        "urlBase": "/pigallery2",
        "//[apiPath]": "PiGallery api path.",
        "apiPath": "/pgapi",
```
3. Tests:
- NOK with external url = https://mydomain.com/pigallery2.
- NOK with internal url = http://192.168.1.14:3900
- NOK with internal url = http://192.168.1.14:3900/pigallery2
- OK if nginx and config.json are set without subfolder.
- No index.html in the root folder of pigallery2 install.

So, maybe I didn't understand something in your explanation but to me:

- location /pigallery2 should set the subfolder of the url for nginx
- proxy_pass setting is localhost at port 3900, witch is the port I set in the config.json
- Exactly the same kind of config in nginx works through subfolder with my other services (navidrome, calibre-web...)

From your point of vue, is it relevant to test with the docker version of pigallery2 or it will be the same behavior?
Can you confirm that my installation and configuration is correct?
What about the host configuration in the config.json?
```
        "port": 3900,
        "//[host]": [
            "Server will accept connections from this IPv6 or IPv4 address."
        ],
        "host": "0.0.0.0",
```



Thank you.

**Comment by Tos26** [comment]
Somebody can help me please ?

**Comment by bpatrik** [comment]
Hi,
just checked. This worked for me:

```
  location /urltest/ {
```

and: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/caef0c79-894b-4836-90b2-4ba5363ddf89)
You can also set in the env variables: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/5a22ad38-abb6-4332-839f-5ca65245a8b3)



This is how the nginx setting works on nginx proxy manager: 
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/0e87ae23-3ce9-4044-9e28-b92de02146bf)

Which generated this file:

```
<...>
  location /urltest/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://pigallery2:80/;
    
<...>
```

**Comment by Tos26** [comment]
Ok, thanks. I'm going to test quickly...
Pigallery2 isn't installed thru Docker, did you test without Docker ?

**Comment by bpatrik** [comment]
without docker it should work the same way.
Also docker is supported way of using the app. I cannot confidently comment on issues that do not use docker.

**Comment by onw4rd** [comment]
Hi - I am seeing the same behavior as @Tos26. I am trying to use ```baseUrl=/gallery```.
My docker-compose.yml:
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=debug # set to 'debug' for full debug logging
      - Server-urlBase=/gallery
      # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend for development
    volumes:
      - "/usr/share/pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/usr/share/pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
      - "/var/tmp/pigallery2/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 5050:80
    restart: always

volumes:
  db-data:
``` 
my nginx reverse proxy:
```
upstream pigallery2 {
        server 192.168.1.235:5050;
}

server {
        listen 80;
        listen [::]:80;

        server_name anthonyhoak.com www.anthonyhoak.com;

        root /var/www/anthonyhoak.com;
        index index.html;

        location / {
                try_files $uri $uri/ =404;
        }

        location /images/ {
                try_files $uri /images/560A1296_5472_3648_b1.jpg;
        }

        location /gallery/ {
                #rewrite /gallery/(.*) /$1 break;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;

                proxy_pass http://pigallery2;
                proxy_redirect off;
       }

}
```
I am using docker but only the pigallery2 container (not the nginx container).
I have modified the ports for the pigallery2 container as I already have a web server running on port 80.
When I use ```urlBase=\gallery``` I get stuck at this loading screen on the website:

![website_loading](https://github.com/bpatrik/pigallery2/assets/173969342/1c2ea261-28bf-496d-84ef-591ec1f62423)

And when I visit the pigallery2 server on my local network using ip and port number:

![ip_port_loading](https://github.com/bpatrik/pigallery2/assets/173969342/a19696ee-69ed-4f99-9c4a-89cb4d68d1f1)

If I change ```baseUrl=/``` in my docker-compose.yml, the website behavior is the same, however, I am able to load the log in screen, log in, and then have full access to the pigallery2 server:

![ip_port_login](https://github.com/bpatrik/pigallery2/assets/173969342/1ef5154f-b124-42c2-8e6e-fa9eb9ba012c)

It seems like the reverse proxy is set up correctly as it redirects to the pigallery2 server but for some reason it doesn't get passed the loading screen. And it seems like pigallery2 is set up/configured correctly as I can log in and view my images on the local network when I don't use ```baseUrl=/gallery```.

Any thoughts? Any advice is appreciated.

Thanks!

**Comment by bpatrik** [comment]
This is how you can try debugging it:

When you set the urlbase parameter in the app, you should see:
(Using chrome developer console, FF should have the same. I open it with F12 or right click)
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/127db9ba-e5a0-4960-8fe0-d26dc4289f28)

Then the app loads the resources from under the right path:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/39b06c3c-a528-43b8-8825-c7aa0303d226)

If the app does not load, it means that i cannot load the resources, so:
* so make sure it uses the right path to load it. So you see this `<domain>/gallery/runtime.js` in your network tab (like in the screenshot)
* make sure that your reverse proxy handles that path properly
  * i.e: rev. proxy should convert `<domain>/gallery/runtime.js` to `<domain>/runtime.js`
  * pigallery2 listens on `<domain>/runtime.js`, so your reverse proxy should this conversion.

**Comment by onw4rd** [comment]
Thank you @bpatrik @Tos26 for replying and all the info.

Unfortunately, I am still having issues.
I am trying to debug in the way suggested above.
Using the developer tools in Firefox, I am able to see the urlbase parameter /gallery/ in the html file:

![website_loading_gallery](https://github.com/bpatrik/pigallery2/assets/173969342/72774454-4666-426e-9deb-d5798f611b61)

But it doesn't appear that the app is able to load the resources:

![website_loading_network](https://github.com/bpatrik/pigallery2/assets/173969342/baeee710-63b3-412d-9b5d-dc3c27c6aae9)

Here are the associated errors:
![website_loading_network_errors](https://github.com/bpatrik/pigallery2/assets/173969342/637f0218-f2c4-4039-be6f-faf10c0fce8a)

The error message for the runtime.js:

```Loading module from “https://anthonyhoak.com/gallery/runtime.558cbc029a6c41c4.js” was blocked because of a disallowed MIME type (“text/html”).```

@bpatrik just to follow up on what you suggested if the resources aren't loading:

> If the app does not load, it means that i cannot load the resources, so:
> so make sure it uses the right path to load it. So you see this <domain>/gallery/runtime.js in your network tab (like in the screenshot)

Yes, it appears that it is using the correct path to load:

![website_loading_network_path](https://github.com/bpatrik/pigallery2/assets/173969342/8caf9715-1999-4c5b-b032-c6ffafa6bbe8)

> make sure that your reverse proxy handles that path properly
> i.e: rev. proxy should convert <domain>/gallery/runtime.js to <domain>/runtime.js

I don't know how to verify this without being able to load the app. Right now I am assuming this works because it is attempting to load the app. When I change the reverse proxy settings, for example, changing the location directive to something other than ```/gallery/```, I don't see the pigallery2 loading screen. So I am assuming the reverse proxy is directing me to the correct location for pigallery2 just because I am seeing the loading screen - is this valid or is it possible for to arrive at the loading screen and the reverse proxy config to still be incorrect?

> pigallery2 listens on <domain>/runtime.js, so your reverse proxy should this conversion.

Can you explain this part in more detail? maybe I am not understanding this. The way I was able to access the app before the reverse proxy was on my local ip and port (e.g. ```192.168.1.235:5050```) and this is what I have the reverse proxy pointing to. Should this be different/do I need to change this somehow if I am setting up the reverse proxy?

I will spend some time reading about the errors above and digging more into your suggestions.

Otherwise, if you have any insight or advice on how to resolve or where to look next, it is much appreciated.

Again, thank you both for your help.

**Comment by bpatrik** [comment]
Honestly I have no clue what is the issue. I'm not an nginx expert.

I would try:

```
  location /gallery/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://192.168.1.235:5050/; #<----------- note the end /
```

I'm not sure why you get the mim time errors. Reading online does not give a good answer. This looks very odd tho:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/d1c9e50b-a5e3-45c8-b15c-733b9c50bbce)

How do you run the app?
have you tried docker with one of the edge tags?

------------------------------
A totally different note: I can't help here because I use nginx proxy manager (NPM) (traefik should be just as good or better) and i use subdomains:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/f05d0026-e7d7-4414-9752-41508e0dad42)

(the blackout part is <mydomain>, so home.mydomain.com)
This way I let NPM deal with the routing.

**Comment by onw4rd** [comment]
Hi @bpatrik @Tos26,

The problem was in the nginx config.

I was missing the trailing "/" in the proxy_pass line.

I changed

```
proxy_pass http://pigallery2;
```
to
```
proxy_pass http://pigallery2/;
```
and everything is working now.

Thank you both for your help!
