### ISSUE TITLE
Not displaying captions/description from PNG

### ISSUE THREAD

**Issue by grainsoflight** [bpatrik/pigallery2#857]
**Note:** Please always try reproducing the issue on the `:edge` build. There is a chance that it was already fixed. If it's an UI issue, you can try reporducing it on the [demo page](https://pigallery2.onrender.com/). 

----------------------------------------------------------------------------------

**Describe the bug**

Face metadata is displaying from PNG files, but caption and date//time original are not

**Environment (please complete the following information):**
 - OS:Unraid
 - Browser chrome

**Used app version**:
- docker v2.0.0

**Comment by grainsoflight** [comment]
IPTC fields "Description" and "Date Created"

**Comment by grainsoflight** [comment]
Date issue seems to be fixed in the edge build, captions are still giving me issues

**Comment by grainsoflight** [comment]
Checked a test file with Exiftool, description field is populated. Additionally tested numerous other fields in light room just to see if I was filling out the wrong one, none of them would get a caption to appear in pigallery2. Currently on 2.0.3-edge

**Comment by grainsoflight** [comment]
I've spent some time testing previous versions and am unable to find a version in which it is functioning properly.

**Comment by grainsoflight** [comment]
Does the metadata need to be written in old ITCP standard instead of XMP? Im kinda at a loss

**Comment by grasdk** [comment]
@grainsoflight 
If you can add a test picture here, with example data, I will try and take a look at it. I did some rework of the metadata loader, so maybe I can help with making this work.
It will be a few days before I have the time, but I'm sure that we can find a solution.

**Comment by grainsoflight** [comment]
@grasdk you can try this one, I have information entered in the several fields because I wasnt sure which PiGallery was pulling from, though the rest of the images in my collection target the "Description" field 
![family-220](https://github.com/bpatrik/pigallery2/assets/29415011/f60cb9b7-c0df-4bfb-8f58-170070b01e77)

**Comment by grasdk** [comment]
@grainsoflight I have something ready for test soon. Solution will be:
  "caption": "Hulda and John's Wedding" (from the description field)
  "title": "The Wedding" (from the title field)
  
  Question, is the picture copyrighted or can I commit it to the pigallery test folder as useful test-data?

**Comment by grainsoflight** [comment]
@grasdk Original artist has been dead for like 100 years, so have at it XD

**Comment by grasdk** [comment]
@grainsoflight Should be ready in next edge build:
https://github.com/bpatrik/pigallery2/pull/876

**Comment by grasdk** [comment]
@bpatrik I think this is merged, so should probably be added to the "Next (probably v2.5)" milestone?

**Comment by bpatrik** [comment]
@grainsoflight can you confirm that the original issue is fixed? If so, pls close the issue.
