### ISSUE TITLE
Question: Metadata xmp.rating values

### ISSUE THREAD

**Issue by grasdk** [bpatrik/pigallery2#865]
Question1: What are valid values of `xmp.rating`?

Background:
- [Adobe defines](https://developer.adobe.com/xmp/docs/XMPNamespaces/xmp/) the legal values as `{-1, 0, 1, 2, 3, 4, 5}` with `[1, 5]` as rating values, `-1` as a special "rejected" value and `0` meaning "unrated". Furthermore, adobe specifies that no rating is assumed to be a `0`.

The UI seems to direct the user towards values 0 to 5 only.

Question2: Assuming that pigallery adopts the range as specified by adobe: If a value outside the range `-1` to `5` is read, what is the expected behavior of pigallery: Default to `0` or to nearest valid value?
Example ideas for "nearest value":

- `-10` will map to `-1`
- `-100` will map to `-1`
- `10` will map to `5`
- `100` will map to `5`
- `2.1` will map to `2` (rounding)
- `2.4` will map to `2` (rounding)
- `2.5` will map to `3` (rounding)
- `2.9` will map to `3` (rounding)
- `3.1` will map to `3` (rounding)
- any non-numerical value will map to `0`
- no rating defined will map to `0`

**Comment by bpatrik** [comment]
I think for now the app support rating of 0 to 5 and undefined (null in db). If null nothing is shown on the UI otherwise the given numbers of starts.

I'm only mediumly certain about this, need to double-check. (Null and 0 maybe handled the same way, which is probably a bug)


I don't mind if we change this, but then grouping, sorting and searching should be updated and kept consistent. ( Preferably in one PR).

In Adobe case what is the difference between rejected and unrated?

Or reverted is when you hit 'x' and the photo turns gray in Lightroom?
That sounds to me a Lightroom specific UI feature and I think pg2 should not follow it, unless it's a more widely adopted feature.

 
Answer 2:

That mapping sounds more or less good to me.

**Comment by grasdk** [comment]
> I'm only mediumly certain about this, need to double-check. (Null and 0 maybe handled the same way, which is probably a bug)
There was a recent PR, where actual 0 values were treated like not present. So if a value 0 was read from actual metadata, the pigallery metadata would show nothing. The opposite of what the [spec](https://developer.adobe.com/xmp/docs/XMPNamespaces/xmp/) says: 
_If xmp:Rating is not present, a value of 0 should be assumed_

> I don't mind if we change this, but then grouping, sorting and searching should be updated and kept consistent. ( Preferably in one PR).
Ok, I don't think there is a lot of impact here. The only new value is -1.

> In Adobe case what is the difference between rejected and unrated?
-1 (rejected): someone viewed it and found it bad (maybe bad quality, or maybe they use it for filtering)
0 (not rated): noone viewed it, or if they did, they didn't care to give it a rating.

> Or reverted is when you hit 'x' and the photo turns gray in Lightroom? That sounds to me a Lightroom specific UI feature and I think pg2 should not follow it, unless it's a more widely adopted feature.
I have no clue how Lightroom works, I just read the spec and the spec says values -1, 0, 1, 2, 3, 4, 5 are valid. So I thought it would be suitable to represent them faithfully. It doesn't mean pigallery needs to represent -1's in any particular way. It's just data :) . And of course, in the end, you're the boss ;)

> Answer 2:
> That mapping sounds more or less good to me.
Cool. I'll work on that. Did some of it already, but will create some extra test-data.

**Comment by bpatrik** [comment]
I did some reading and put some thoughts in it:

Adobe rejected is special case with special UI feature ( Lightroom set a the photo gray and adds a black flag. I usually use it to virtually delete the photo). Lightroom supports also an inverse rejected flag, which is 'picked' and has a white flag as UI indicator.

On a separate UI surface Lightroom supports rating between 1-5 and non-rating. ( this also agrees with documentation that you also referenced).

Scanning through this https://exiftool.org/forum/index.php?topic=3567.0, it seems to me xmp rating is very much not standard and eg. Windows does support rating.

It looks to me rejected is Lightroom specific only ( I could not find anywhere else). I don't think pigallery2 should be an other UI for Lightroom. 

+1 each metadata info (that is sent to the client side, like rating) linearly increases the gallery ( each folder/search) load time.

Based on this I think rating **should work as follows**:

* Undefined,  null and 0 are equivalent  and  metadat.rating should not be set.
   * searching for 0 rating should list all of these photos 
* Valid ratings are 1-5. UI only shows rating if its between 1-5.
* -1 mapped to 0



That said:
I don't mind if you would like to support rejected,  but UI should also reflect it.

**Comment by grasdk** [comment]
Thanks. I'm fine with this. It's an edge case with -1 anyway. I just like specification and it appears that a lot of this xmp-stuff is adobe's invention. However, when the bulk of support is for 1-5 (and 0), no reason to let pigallery suffer from that. Especially if it can impact performance :)

I'll close the question, but it's a good reference for later.

**Comment by grasdk** [comment]
Closing the question with the current state being as described below:

> Based on this I think rating **should work as follows**:
> 
>     * Undefined,  null and 0 are equivalent  and  metadat.rating should not be set.
>       
>       * searching for 0 rating should list all of these photos
> 
>     * Valid ratings are 1-5. UI only shows rating if its between 1-5.
> 
>     * -1 mapped to 0
