### ISSUE TITLE
mp4 videos not listed / shown?

### ISSUE THREAD

**Issue by rsend** [bpatrik/pigallery2#866]
I just installed PiGallery2 to try it out. I  used the direct install method, not the Docker way, everything works fine except for one thing:

Videos (mp4 files, in this case) are not shown at all when browsing the gallery, even though they are definitely present in the directories.

I have ffmpeg and ffprobe on the system, and the "Enable" toggle is turned on. I tried toggling it back and forth and restarting the server to no avail.

The only thing I can think of is that I installed ffmpeg AFTER I installed PiGallery2, so maybe it's not getting picked up by the application now?

**Comment by bpatrik** [comment]
Try resetting your DB to trigger a full reindex once you change the video
support

-- Sorry for being brief, sent from my phone.
