### ISSUE TITLE
[Security issue] Download local files thanks to a directory traversal attack on v1.5.6

### ISSUE THREAD

**Issue by wikijm** [bpatrik/pigallery2#88]
Hi @bpatrik 

**Describe the bug**
Thanks to a specific web request, it's possible to download a file located on the host server.

**Screenshots**
![SecVuln](https://user-images.githubusercontent.com/10724809/61395663-40765a80-a8c6-11e9-828c-f5ab9f664e0b.png)

**Environment (please complete the following information):**
 - OS: N/A
 - Browser: N/A

**Used app version**:
- release v1.5.6

How can I safely contact you to provide more information?
If you want to contact me, please use Twitter with the same pseudo.

Sincerely,
WikiJM

**Comment by bpatrik** [comment]
Hi

This or a similar bug was fixed after the realase of v1.5.6.
Can you check if you can reproduce it by building the app from source?

Best,
Patrik

-- Sorry for being brief, sent from my phone.

**Comment by wikijm** [comment]
Sure, i just won't be able to test it today.

**Comment by wikijm** [comment]
Hi @bpatrik 

For information, the attack seems ineffective on Heroku demo.

**Comment by wikijm** [comment]
I confirm that this seems to have been fixed in version 1.5.9.
Would it be possible to let this issue open until v1.5.9 release?

**Comment by bpatrik** [comment]
Hi,
I made a new release, so I'm closing this.
