### ISSUE TITLE
Search by date filters by UTC timestamp

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#892]
Search example: `after:2024-04-18 before:2024-04-19`

Expected result:
  * any media where timestamp was taken on '2024-04-18', regardless of timezones

Actual result:
  * media without a timezone offset shows as expected, because pigallery has assumed it to be in UTC.
  * media that has a timezone offset in metadata is excluded if it falls outside of the converted UTC timestamp of '2024-04-18`

**Comment by mcdamo** [comment]
This is somewhat related to #871

**Comment by bpatrik** [comment]
Yeah. This needs clean up.
We should fix this before the next release. (which I have no idea when will happen, but today I dont think it will before sept.)

@grasdk FYI. If you feel that you have the time for this. :)

**Comment by grasdk** [comment]
@mcdamo I would say this bug is resolved in the latest edge version, if you leave the timestamp offset setting on "ignore". See https://github.com/bpatrik/pigallery2/pull/902

**Comment by mcdamo** [comment]
Thanks @grasdk, however with "ignore" setting on, search by date now appears to exclude all images without timezones.

For example search `after:2024-04-13 and before:2024-04-15` is missing the `4MinsAroundTheWorld/20240413-203800-Unknown.jpg` image in search results.

**Comment by grasdk** [comment]
@mcdamo 
Good spot. `null * 60000` is still `null` in SQLite (and others I guess), so had to add the coalesce-function to the "ignore" queries: `(coalesce(creationDateOffset,0) * 60000)`

I made a PR (https://github.com/bpatrik/pigallery2/pull/913), but the test is failing. Looks like a container error though, hopefully not caused by my code. You're welcome to pull and build my branch and see if it works for you.

**Comment by grasdk** [comment]
@mcdamo my fix was merged last night and it appears that it was released unto the latest edge-version. Care to take it for a spin to see if you agree that it's fixed? :)

https://hub.docker.com/r/bpatrik/pigallery2/tags

**Comment by mcdamo** [comment]
Thanks @grasdk, I tested the latest code and the search works with your fix.
