### ISSUE TITLE
Node error starting pigallery2

### ISSUE THREAD

**Issue by scottsavarese** [bpatrik/pigallery2#899]
**Describe the bug**

Unable to start pigallery2

**Screenshots (optional)**

> 
> root@web:/data/pigallery2# bash startup 
> node:buffer:646
>     slice: (buf, start, end) => buf.utf8Slice(start, end),
>                                     ^
> 
> RangeError: Index out of range
>     at Object.slice (node:buffer:646:37)
>     at Buffer.toString (node:buffer:865:14)
>     at Object.readFileSync (node:fs:515:41)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1273:18)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> 
> Node.js v18.18.1

**Server logs (optional)**

Installed docker (apt install docker)

Made volumes:

> root@web:/data/pigallery2# ls -la
> total 24
> drwxr-xr-x 6 root root 4096 Apr 29 19:09 .
> drwxr-xr-x 8 root root 4096 Apr 29 19:09 ..
> drwxr-xr-x 2 root root 4096 Apr 29 19:09 config
> drwxr-xr-x 2 root root 4096 Apr 29 19:09 db
> drwxr-xr-x 2 root root 4096 Apr 29 19:09 images
> drwxr-xr-x 2 root root 4096 Apr 29 19:09 tmp
> 

Tried starting up pigalery2

> 
> root@web:/data/pigallery2# more startup 
> docker run \
>    -p 80:80 \
>    -e NODE_ENV=production \
>    -v /data/pigallery2/config:/app/data/config \
>    -v /data/pigallery2/db:/app/data/db \
>    -v /data/pigallery2/images:/app/data/images \
>    -v /data/pigallery2/tmp:/app/data/tmp \
>    bpatrik/pigallery2:latest
> 

After downloading all parts of the container, I get the above error.

**Environment (please complete the following information):**

> root@web:/data/pigallery2# cat /etc/debian_version 
> 10.13
> root@web:/data/pigallery2# dpkg -l | grep docker
> ii  docker-compose                   1.21.0-3                      all          Punctual, lightweight development environments using Docker
> ii  docker.io                        18.09.1+dfsg1-7.1+deb10u3     amd64        Linux container runtime
> ii  golang-docker-credential-helpers 0.6.1-2+deb10u1               amd64        native stores to safeguard Docker credentials
> ii  python3-docker                   3.4.1-4                       all          Python 3 wrapper to access docker.io's control socket
> ii  python3-dockerpty                0.4.1-1                       all          Pseudo-tty handler for docker Python client (Python 3.x)
> ii  python3-dockerpycreds            0.3.0-1                       all          Python3 bindings for the docker credentials store API
>

**Comment by martadinata666** [comment]
docker version too old, look into docker guide https://docs.docker.com/engine/install/debian/

**Comment by scottsavarese** [comment]
Still not working... Tried doing the docker update as per the doc you referenced. Used the apt install method.

> root@web:/data/pigallery2# bash startup 
> Unable to find image 'bpatrik/pigallery2:latest' locally
> latest: Pulling from bpatrik/pigallery2
> e67fdae35593: Pull complete 
> 7e37ba7d55cf: Pull complete 
> c4adb971b2fc: Pull complete 
> 8fc7c2802e88: Pull complete 
> 7b35e22698fa: Pull complete 
> 9dbbf5383165: Pull complete 
> dcd36f995986: Pull complete 
> daaf7043be9b: Pull complete 
> ec8c51016d66: Pull complete 
> Digest: sha256:317a50a5d1b81ad3469ac534c39e4c8022b13b8e504a30bc279716ceabed1e1f
> Status: Downloaded newer image for bpatrik/pigallery2:latest
> node:buffer:646
>     slice: (buf, start, end) => buf.utf8Slice(start, end),
>                                     ^
> 
> RangeError: Index out of range
>     at Object.slice (node:buffer:646:37)
>     at Buffer.toString (node:buffer:865:14)
>     at Object.readFileSync (node:fs:515:41)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1273:18)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> 
> Node.js v18.18.1
> root@web:/data/pigallery2# docker version
> Client: Docker Engine - Community
>  Version:           26.1.0
>  API version:       1.45
>  Go version:        go1.21.9
>  Git commit:        9714adc
>  Built:             Mon Apr 22 17:06:58 2024
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          26.1.0
>   API version:      1.45 (minimum version 1.24)
>   Go version:       go1.21.9
>   Git commit:       c8af8eb
>   Built:            Mon Apr 22 17:06:58 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.31
>   GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
>  runc:
>   Version:          1.1.12
>   GitCommit:        v1.1.12-0-g51d5e94
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

**Comment by scottsavarese** [comment]
Nothing special about the machine. I don't consider being a VM anything special at this point in time. As for the library you are referring to:

> root@web:/data/pigallery2# dpkg -l libseccomp2
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name              Version      Architecture Description
> +++-=================-============-============-================================
> ii  libseccomp2:amd64 2.3.3-4      amd64        high level interface to Linux se

What about directory permissions? Is it OK if the directories for config, images, etc. are owned by root?

**Comment by martadinata666** [comment]
As for VM, something about missing cpu features may affect nodejs. Just ensure CPU setting to passthrough mode. About the library, install debian 11(bullseye) or 12(bookworm). Are any reasons to stay ata debian 10 (buster)?

**Comment by scottsavarese** [comment]
Upgrading the VM solved the issue. Thanks.
