### ISSUE TITLE
sort photos in ascending/descending order

### ISSUE THREAD

**Issue by tomikais** [bpatrik/pigallery2#9]
Can you please provide an option to switch sorting mode (ascending/descending) in the gallery. It would really nice to have the latest added photos at the top of the main page.

**Comment by bpatrik** [comment]
Its there.
You can change the default sorting method under the other settings (in advanced mode)
Watch out, the latest commit breaks the settings. Its recommended to recreate the `config.json`.

**Comment by tomikais** [comment]
OH SORRY! I've got it!

**Comment by bpatrik** [comment]
nothing to sorry. I made the changes after you requested it. :)

**Comment by tomikais** [comment]
👍 okay^^ :)
