### ISSUE TITLE
Cannot start pigallery2 after a node upgrade

### ISSUE THREAD

**Issue by sugatam** [bpatrik/pigallery2#900]
I've been running pigallery2 natively on a sbc running debian trixie. A recent upgrade pulled in a new version of node and npm, and now I cannot start the app:

`
5/4/2024, 10:32:20 AM[WARN_][ConfigDiagnostics] [SQL error] Error: The module '/srv/pigallery2/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 109. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
`

I wiped node_modules, cleared the npm cache, did a new npm install and an npm rebuild, all to no avail. Finally, I even did a fresh git pull and build, but I'm still getting this. Any ideas?

**Comment by bpatrik** [comment]
Hi

The latest node is not supported yet. Pls use node 18.

-- Sorry for being brief, sent from my phone.

**Comment by sugatam** [comment]
Thanks for your reply Patrik. I don't think trixie pulled in a new major version of node, its still node v18.
```typescript
> process.versions
{ 
  node: '18.20.1',
  modules: '109',

``` 

and on another installation where I haven't upgraded:

```typescript
{ 
  node: '18.19.1',
  modules: '108',
}

``` 
I'm not familiar with the node dev/release pipeline, but it appears that despite what I'm trying I can't get that one module - better_sqlite3 - to rebuild in the new pipleline.

**Comment by martadinata666** [comment]
can you please test using `-d`, `npm -d rebuild` likely *or* what I assume is missing build deps and can't build the module from the source.

**Comment by sugatam** [comment]
Hi, npm -d rebuild didn't help, nor did clearing out node_modules and running 
```shell
npm install --build-from-source
``` 
How can I get more insight into build deps? You may be right in that I can't build better_sqlite3 from source, just want to know why and address that. Messing around with various revisions of better_sqlite3 (9.x.x) led to npm run build failing, so that was a no go.

**Comment by martadinata666** [comment]
`-d` is debug mode, so there should be more insight what wrong? or at least why it don't compile from source. Can you please paste the log, here 🤔

**Comment by sugatam** [comment]
I was able to fix it by

```shell
cd node_modules/better_sqlite3
node-gyp rebuild --release 
```

**Comment by bpatrik** [comment]
Happy to hear. Closing this bug.
