### ISSUE TITLE
question: How to filter out "ignored" folder after the fact

### ISSUE THREAD

**Issue by kruthers64** [bpatrik/pigallery2#909]
First: pigallery 2 is awesome.  I looked at many, MANY, different photo gallery implementations and this is just the perfect one.  It's hard to believe how many of my "required" features you have, because there is just an infinite number of ways to do this.

Anyway, after I set pigallery2 to view my entire photo collection I realized, oh wait, there are a few subfolders I don't want to be browseable.  So I went and added an ".ignore" file to those directories.

But that doesn't make them disappear right away.  So how do I refresh the particular parent folders so that the ignored subfolders disappear?

**Comment by mrtnbr** [comment]
Manually running Indexing again from the Admin page might be enough, if that doesn't work you can try a Gallery reset from there.

**Comment by kruthers64** [comment]
Yes thank you, that worked.

For future reference for anyone seeing this, I ran indexing in the "Jobs" section of the admin page, and I turned off "index changes only". At least I believe that's what got it working.

**Comment by KarstenHahn** [comment]
I've opened the test gallery for everyone. Not a good idea :-) I've set a password for the gallery now. Please contact me, if you want to see the problem "live"...

Here are screenshots of the gallery:
![grafik](https://github.com/bpatrik/pigallery2/assets/33198302/584637a6-3e92-427d-b57a-79e62631727e)

and

![grafik](https://github.com/bpatrik/pigallery2/assets/33198302/eb91c3c9-4dc9-4421-931e-c8b2fdbec309)

Here is the index.md file:


```
Test-Reise in den Garten
<!-- @pg-date 2024-05-28 -->
Blumen
<!-- @pg-date 2024-05-29 -->
Wolken

```

**Comment by bpatrik** [comment]
Yeah some actions does not trigger re-indexing automatically. (Apparently this either, which is a bit surprising).
In that case you can just drop (rest) the db and reindex.
