### ISSUE TITLE
Is there a maximum limit on field metadataKeywords?

### ISSUE THREAD

**Issue by miguelius1966** [bpatrik/pigallery2#914]
I have an image with a long text in the **subject** field and a long text in the **keywords** field. For example: 

```
$ exiftool -subject -keywords image.jpg
Subject                         : Madrid,Comunidad de Madrid,España
Keywords                        : Carreras,Media de Fuencarral
```

When indexing is carried out, the union of the two text strings is not obtained. It seems that the **keywords** field is ignored. It can be seen in the database:

```
sqlite> select id, directoryid, metadataKeywords from media_entity where directoryid=2286;

166390|2286|,Madrid,Comunidad de Madrid,España
200429|2286|,Madrid,Comunidad de Madrid,España
200430|2286|,Madrid,Comunidad de Madrid,España
```

Maybe, is there a maximum limit on field metadataKeywords and therefore, the union of the two fields of the image cannot be performed?

Thanks in advance.

**Comment by bpatrik** [comment]
The issue most likely lies here:
https://github.com/bpatrik/pigallery2/blob/1fd07a640c9f7593c23389cf1ae6a23eeb71d72a/src/backend/model/fileaccess/MetadataLoader.ts#L328-L356

The app does not load keywords from exif data.
FYI: @grasdk

**Comment by bpatrik** [comment]
@miguelius1966 Can you provide a broken image to test on?

**Comment by miguelius1966** [comment]
Yes, of course. 

![media-fuencarral-2023-01](https://github.com/bpatrik/pigallery2/assets/62244960/5d0c51fe-272b-429c-8a70-1e8835bc223d)

**Comment by grasdk** [comment]
@miguelius1966 I think you're running an older version of pigallery. I cannot reproduce the problem. I included your photo in my test-image folder and it was indexed correctly, here is a screenshot from SQLite browser:

![image](https://github.com/bpatrik/pigallery2/assets/115414609/22fba478-fa7e-4623-b492-7777c4a64015)

You can try to update to the latest edge-version and see if that doesn't fix the problem :)

**Comment by miguelius1966** [comment]
I execute:

```
$ sudo docker compose stop
$ sudo docker pull bpatrik/pigallery2:edge-debian-bookworm
$ sudo docker compose up -d

```
I create a new directory (Fuencarral_backup) and copy the same images with different names and I obtain the same:

166390|2286|Media de Fuencarral 2023|,Madrid,Comunidad de Madrid,España
200429|2286|Media de Fuencarral 2023|,Madrid,Comunidad de Madrid,España
200430|2286|Media de Fuencarral 2023|,Madrid,Comunidad de Madrid,España
**209190|2461|Fuencarral_backup|,Madrid,Comunidad de Madrid,España**
**209191|2461|Fuencarral_backup|,Madrid,Comunidad de Madrid,España**
**209192|2461|Fuencarral_backup|,Madrid,Comunidad de Madrid,España**

But if I use the same image with a EXIF keywords with only one letter less, it works:

```
$ exiftool -keywords prueba.jpg
Keywords                        : Carreras,Media de Fuencarra

sqlite> select id,name,metadataKeywords  from media_entity where id=209193;

209193|prueba.jpg|Carreras,Media de Fuencarra,Madrid,Comunidad de Madrid,España

```
