### ISSUE TITLE
Replace exifr by exiftool

### ISSUE THREAD

**Issue by fpellet** [bpatrik/pigallery2#915]
**Is your feature request related to a problem? Please describe.**

exifr is no longer maintained and the latest version is 3 years old.
Some formats are poorly managed, such as avif.

**Describe the solution you'd like**

I suggest using exiftool instead of exifr. exiftool is maintained is a reference for this type of use.

I'm willing to work on it if it has a chance of being merged.

**Comment by bpatrik** [comment]
We had an attempt doing so a few years ago. Back then exiftool was 2-3x
slower (if i recall correctly) than the used tools. Since then I haven't
checked if it got faster or if there is any config that would disable some
things on it to make it faster.

**Comment by bpatrik** [comment]
see conversation in #277.

Closing this to reduce duplicates.

**Comment by grasdk** [comment]
Maybe reopen as an enhancement with reference to this: https://github.com/bpatrik/pigallery2/issues/277#issuecomment-2018751573
