### ISSUE TITLE
Non ASCII characters (accents, umlauts) in face tags are displayed incorrectly

### ISSUE THREAD

**Issue by stkr** [bpatrik/pigallery2#917]
In an image that has XMP metadata, non-ascii characters are displayed wrongly for face regions.

In the attached image, the person Lena Forsén is found in the metadata three times:
  * as face region (XMP-mwg-rs:RegionInfo) with the value "Lena Forsén" which is used for PiGallery's "faces"
  * as person in image (XMP-iptcExt:PersonInImage) with the value "Lena Forsén as person in image" which is not used by PiGallery
  * as subject (XMP-dc:Subject) with the value "Lena Forsén as keyword" which is used by PiGallery2 "keyword/tag"
 
The metadata was written with ExifTool 12.76, the character encoding for all three instances is UTF-8.
PiGallery2 displays the "keyword" version of the metadata as expected, for the "faces" version of the metadata the é (e with accent) gets displayed wrongly. I have seen the same happen also for other non-ascii characters - in particular german umlauts.

I am using sqlite as database, the strings found in the database are already unexpected (see screenshot from sqlite), so I am guessing something goes wrong then reading the metadata.

Note, this could be a duplicate of https://github.com/bpatrik/pigallery2/issues/650, however. I do not see a problem with the encoding of my particular image. If there is, please help me to figure out what it is. The image metadata is correctly displayed with digiKam, and Gimp and also on online services like https://jimpl.com/ and even the exifr playground (https://mutiny.cz/exifr/).

The problematic image:
![lenna_unlinked](https://github.com/bpatrik/pigallery2/assets/192204/7d4228b3-0130-421b-a406-61a0159139be)

--------------------

How it looks in PiGallery2:
![screenshot_pigallery](https://github.com/bpatrik/pigallery2/assets/192204/228b304c-efe1-4e10-9d27-155580557179)

--------------------

Screenshot of database contents:
![screenshot_sqlite](https://github.com/bpatrik/pigallery2/assets/192204/0c7fd84e-09b9-4d8a-90dd-ae2db380685e)

--------------------

How Gimp interprets the metadata:
![screenshot_gimp](https://github.com/bpatrik/pigallery2/assets/192204/40d35396-dd69-4e0f-9584-3ec3b19a2125)

--------------------

How digiKam interprets the metadata:
![screenshot_digikam](https://github.com/bpatrik/pigallery2/assets/192204/e8389f2b-853c-4563-8639-cda841cb995f)

Working on linux, browser is firefox.
The used app version is release 2.0.0.

**Comment by bpatrik** [comment]
Last commit should fix it:
![kép](https://github.com/bpatrik/pigallery2/assets/7512182/e1e53a29-6bfb-4fa6-9cfa-9080221fc351)

(please reopen if the issue still persist)

the fix should be in :edge in ~40 mins.
