### ISSUE TITLE
share password not woking

### ISSUE THREAD

**Issue by zx19lucky** [bpatrik/pigallery2#922]
I enabled the shared password in the settings and then created a shared link. However, when I opened the shared link, I could access it directly without being prompted for a password.  I am using the latest docker version 
![image](https://github.com/bpatrik/pigallery2/assets/174412735/4608f962-db15-46a7-a364-74d2975280bb)

**Comment by bpatrik** [comment]
Duplicate of #744
-- Sorry for being brief, sent from my phone.
