### ISSUE TITLE
Couldn't refresh images when overwriting.

### ISSUE THREAD

**Issue by decadance-dance** [bpatrik/pigallery2#935]
**Describe the bug**

I am developing on a remote machine. I do computer vision so I often need to work with images. My case is when I iteratively change a CV algorithm and save result images into a folder. So I don't update folder structure but images itself (their content). I mounted this folder to the gallery but when I overwrite images I don't see changes in the gallery.

**Comment by bpatrik** [comment]
yeah. THere is no content detection implemented. You need weather: a)
delete the image in the tmp folder so the thumbnail will be regenerated b)
rename to photo

Alternatively if you zoom in the photo,. it will load the original image,
so you will see the change
