### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by alopezbu** [bpatrik/pigallery2#95]
Hi, 
if instead of connecting through the ip I wanna connect typing foto.app how should I proceed?

Thank you everyone

**Comment by palitu** [comment]
setup a reverse proxy for a subdomain.  It is a pretty straight forward
config too, nothing extra really.

i used Nginx.

**Comment by bpatrik** [comment]
Hi,
It is more a general server server setup question than a pigallery one.


It depends what you exactly want. 
1) If you only want to access your server **from your home network**, you can [setup a hostname](https://www.cyberciti.biz/faq/ubuntu-change-hostname-command/) like `myserver` on the server and broadcast that. Then you would be able to access your server at http://myserver.

2) **From the 'Web'**
   * Your server is probably behind a router with NAT, you need to do port forwarding (typically port 80 forward to your server IP) on the router.
   * then get a domain name. Potentially something like dyndns (I can recommend [duckdns](https://www.duckdns.org/)) as you probably get dynamic IP from four ISP (internet service provider)
[Here is guide for that](https://www.instructables.com/id/Set-up-your-very-own-Web-server/). Point 10 and 11 are the important ones.

You most likely looking for the 2. option.

**Comment by bpatrik** [comment]
i close this due to inactivity
