### ISSUE TITLE
Face tags don't seem to work for my photos

### ISSUE THREAD

**Issue by cbenning** [bpatrik/pigallery2#99]
**Describe the bug**
I tag my photos using DigiKam on linux (which supports XMP tag) and for some reason, your squirrel photo from the demo shows the face tag but not my photos.

Looking through the code, I don't see any fields being used that aren't in my photo, so I'm stumped. Any idea whats up?

**Photo/video (optional) that causes the bug**
Related XMP metadata from your squrrel photo:

```Xmp.mwg-rs.Regions                           XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:w XmpText     4  1394
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:h XmpText     3  930
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:unit XmpText     5  pixel
Xmp.mwg-rs.Regions/mwg-rs:RegionList         XmpText     0  type="Bag"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]      XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Rotation XmpText     7  0.00000
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Name XmpText    18  Alvin the Squirrel
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Type XmpText     4  Face
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:h XmpText     7  0.28108
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:w XmpText     7  0.21731
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:x XmpText     7  0.57214
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:y XmpText     7  0.42297
```

My photo metadata

````Xmp.mwg-rs.Regions                           XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList         XmpText     0  type="Bag"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]      XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Name XmpText    12 My Person
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Type XmpText     4  Face
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:x XmpText     8  0.422976
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:y XmpText     8  0.207705
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:w XmpText     8  0.245531
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:h XmpText     8  0.168197
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:unit XmpText    10  normalized
Xmp.MP.RegionInfo/MPRI:Regions               XmpText     0  type="Bag"
Xmp.MP.RegionInfo/MPRI:Regions[1]            XmpText     0  type="Struct"
Xmp.MP.RegionInfo/MPRI:Regions[1]/MPReg:Rectangle XmpText    37  0.30021, 0.123607, 0.245531, 0.168197
Xmp.MP.RegionInfo/MPRI:Regions[1]/MPReg:PersonDisplayName XmpText    12  My Person
````

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 64 bit
 - Browser: Firefox

**Used app version**:
- compiled from source, deployed as docker container

**Comment by bpatrik** [comment]
Hi,

I was developing the feature with Lightroom and did not have the chance to test it with other applications.
I would be happy to support other image editors, but I'm super busy lately. Even if I consider this feature with the highest priority most like I wont have the chance to fix it in the next 2 months.
But I would be happy to merge a pull request, if you have the time adding this to the app.

You can try figuring out the XMP difference with this app: http://metapicz.com
I'm loading the face data here: https://github.com/bpatrik/pigallery2/blob/83025f7b32df67c8079d5c3d5aa57c528cef7196/backend/model/threading/MetadataLoader.ts#L198
I'm using this to parse the xmp data: https://github.com/mattiasw/ExifReader

Best,
Patrik

**Comment by cbenning** [comment]
Happy to contribute, I'm just not so great with frontend tools so I'll be a bit slow. I looked through that file and found nothing being accessed that wasn't in the metadata. It needs a step-through I suppose.

**Comment by cbenning** [comment]
Actually looking at that library, it appears that it might only support JPG which might be my issue. All mine are PNGs

**Comment by bpatrik** [comment]
I had a quick look at it and unfortunately you are right. 
I put face data to PNG-s and I could not make that lib to read it (even if I switched off their error check)
We can try asking them to add PNG support or we can try finding a new lib. (or alternatively forking theirs and adding PNG support)

To fix it, you don't need to touch the UI part. Its enough to update that few line of code at the backbend where the process the photos.
For that you can use `npm run run-backend` to build the typescript files to javascript. (or use `tsc` command with optionally `-w` flag to watch for changes while you develop)

Best,
Patrik

**Comment by mattiasw** [comment]
Hi! Maintainer of ExifReader here. Just want to say that the library supports XMP tags in PNGs since earlier this year if you want to try to upgrade.

**Comment by bpatrik** [comment]
Thank you @mattiasw, using the newer version indeed solved the issue.
